### ISSUE TITLE
No syntax colorization for fortran

### ISSUE THREAD

**Issue by CubeTian** [thebaselab/codeapp#10]
Syntax colorization for fortran not work 
![image](https://user-images.githubusercontent.com/42400769/103211772-11319d00-4944-11eb-8660-3ca515f2a0d2.png)

**Comment by bummoblizard** [comment]
Hello. I will add this feature in the coming versions.

**Comment by CubeTian** [comment]
👍

**Comment by bummoblizard** [comment]
Fix released. Please reopen if the problem persists.

**Comment by CubeTian** [comment]
The problem is not completely solved.
I found that the .f files are highlighted correctly, .f90, .f95 are still not highlighted

Some information that might help you:
.f is the source file for Fortran 77 (old but popular version), or called legacy fortran
.f90, .f95, .f03 are source files for Fortran 90 or later, or called modern fortran

There is a large syntax change between the two. 

Alternatively, provide the option for the user to choose a highlighting strategy based on automatic suffix recognition

Translated with www.DeepL.com/Translator (free version)

**Comment by CubeTian** [comment]
> Fix released. Please reopen if the problem persists.

The problem is not completely solved.
I found that the .f files are highlighted correctly, .f90, .f95 are still not highlighted

Some information that might help you:
.f is the source file for Fortran 77 (old but popular version), or called legacy fortran
.f90, .f95, .f03 are source files for Fortran 90 or later, or called modern fortran

There is a large syntax change between the two. 

Alternatively, provide the option for the user to choose a highlighting strategy based on automatic suffix recognition

Translated with www.DeepL.com/Translator (free version)

**Comment by CubeTian** [comment]
The problem is not completely solved.
I found that the .f files are highlighted correctly, .f90, .f95 are still not highlighted

Some information that might help you:
.f is the source file for Fortran 77 (old but popular version), or called legacy fortran
.f90, .f95, .f03 are source files for Fortran 90 or later, or called modern fortran

There is a large syntax change between the two. 

Alternatively, provide the option for the user to choose a highlighting strategy based on automatic suffix recognition

**Comment by CubeTian** [comment]
> Fix released. Please reopen if the problem persists.

The problem is not completely solved.
I found that the .f files are highlighted correctly, .f90, .f95 are still not highlighted

Some information that might help you:
.f is the source file for Fortran 77 (old but popular version), or called legacy fortran
.f90, .f95, .f03 are source files for Fortran 90 or later, or called modern fortran

There is a large syntax change between the two. 

Alternatively, provide the option for the user to choose a highlighting strategy based on automatic suffix recognition

**Comment by bummoblizard** [comment]
I see. This should be easy to fix. Thanks for the report!
