### ISSUE TITLE
The custom font cannot be loaded by UIFontPickerViewController.

### ISSUE THREAD

**Issue by EpsIotaPi** [thebaselab/codeapp#1004]
For example, I installed Monaco by other font app, however, The Code App's UIFontPickerViewController can't found it.

I think UIFontPickerViewController only provides system font by default. The following step may fix this problem:
Add Fonts capability in  iOS app’s target, and select Use Installed Fonts. 

Please see the following article: https://developer.apple.com/documentation/xcode/configuring-custom-fonts

**Comment by EpsIotaPi** [comment]
#527 #804

**Comment by bummoblizard** [comment]
Thanks for the heads up. I have added this entitlement and a new build will be available on TestFlight soon.

**Comment by bummoblizard** [comment]
Custom fonts are shown but not loaded properly even with the entitlement. Investigation needed.

**Comment by bummoblizard** [comment]
@EpsIotaPi Can you confirm if the latest commit fixes the issue? You can try it on TestFlight as soon as the build is available.

**Comment by EpsIotaPi** [comment]
Thank you for your great work! I can confirm the latest commit already fixes this issue!
