### ISSUE TITLE
Terminal & wasm a.out

### ISSUE THREAD

**Issue by gitstudent-000** [thebaselab/codeapp#1009]
Hello, iPhone version of Code app does not show any output when running .c file using terminal. I opened a folder with a .c file and selected the file and pressed the run sign. The terminal displays no information about the .c file. The only information displayed in the terminal window is Documents $ clang then it reloads Documents $. Please help.

**Comment by bummoblizard** [comment]
Please try to restart your device. Also make sure to exit a C program properly before executing another.
