### ISSUE TITLE
How to configure credentials for Git

### ISSUE THREAD

**Issue by ahnhyunjin1** [thebaselab/codeapp#102]
I'm coding on my iPad. 
I want to push GitHub, but I have a credential error.
err name: credential are not configured
I need your help.

**Comment by bummoblizard** [comment]
Hello. In order to push changes to a repository, you'll need to set your credentials. 

This can be done by `Settings > Version Control > Authentication`. Input your GitHub's account name and personal access token (or password).

**Comment by ahnhyunjin1** [comment]
wow .. im solve this problem T^T
Thank you.  have a nice day ^^7
