### ISSUE TITLE
Please upload the newest version as soon as possible.

### ISSUE THREAD

**Issue by Farewe1ll** [thebaselab/codeapp#1020]
I'm a user from China and looking forward to see the newest feature in the app. I've got that version 1.7.0 was released yesterday. However, the version in Chinese App Store hasn't updated yet. Could you please upload it as soon as possible? Cause I couldn't wait to try the bits/stdc++.h header and compile my cpp programmes!

**Comment by bummoblizard** [comment]
@Farewe1ll It is now available on the App Store.
