### ISSUE TITLE
Input not available.

### ISSUE THREAD

**Issue by JUSEOUNGHYUN** [thebaselab/codeapp#104]
I'm using C language using this app, and I'm trying to get input using scanf, but I keep getting weird output and I can't input at all. How do I get input through the terminal?

**Comment by bummoblizard** [comment]
Hi. For languages that are executed externally (for example, C), you'll need to input before the execution.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/38398443/117345527-3b3e3180-aed9-11eb-94e1-1fdc50a10146.png">
