### ISSUE TITLE
Bug with quotes and hashtags

### ISSUE THREAD

**Issue by Arioch-IV** [thebaselab/codeapp#105]
when my cursor is next to a quotation mark (', ") or a #, the application freezes and I can't do anything other than restart the application

![image](https://user-images.githubusercontent.com/78066493/117351411-b1ac4680-ae7b-11eb-9728-2434af56207e.jpeg)

**Comment by bummoblizard** [comment]
Hello. This is a major problem. But I can't seem to reproduce it though. What's your iPadOS version? And can you share the crash log through TestFlight and have me investigate?

**Comment by Arioch-IV** [comment]
> Hello. This is a major problem. But I can't seem to reproduce it though. What's your iPadOS version? And can you share the crash log through TestFlight and have me investigate?

Hi, I'm on iPadOS 14.5.1
And I shared the crash log on TestFlight

**Comment by bummoblizard** [comment]
> > Hello. This is a major problem. But I can't seem to reproduce it though. What's your iPadOS version? And can you share the crash log through TestFlight and have me investigate?
> 
> Hi, I'm on iPadOS 14.5.1
> And I shared the crash log on TestFlight

Thank you! I am looking at it. Can you also check if the editor works on this website? - https://microsoft.github.io/monaco-editor/

**Comment by bummoblizard** [comment]
After further investigation, it seems like this is only affecting Python scripts. I am working on a fix.

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/monaco-tm/commit/5b0cb34f7d5538514593b7e4eff5d46a29d40763
