### ISSUE TITLE
[ Feature request ] Add keyboard toolbox suport for the integrated terminal

### ISSUE THREAD

**Issue by hyhcrh** [thebaselab/codeapp#1064]
I have used the app for a while, and the toolbox besides virtual keyboard really helps me a lot when editing code.
But when operating in terminal, I cannot even move the cursor without a external keyboard.
Could you please add the toolbox support when in terminal? I would really appreciate that.

**Comment by bummoblizard** [comment]
Thanks for reminding me. This is an important feature.
