### ISSUE TITLE
Does port transmit function supportted by code app?

### ISSUE THREAD

**Issue by ohhh-yang** [thebaselab/codeapp#1066]
Whem I train a deep learning python model, I want to watch train loss or other train parameters by 'tensorboard --logdir=./logs', a website '127.0.0.1:6006' should be present in browser. But it does not works, the website can  be assessed. Even I use '--bind-all' parameter. I have not try ssh port mapping.

**Comment by bummoblizard** [comment]
Hi. Instead of using the ssh command, please take a look at the built-in remote SSH feature where port forward can be configured by GUI.

https://code.thebaselab.com/guides/connecting-to-a-remote-server-ssh-ftp

**Comment by ohhh-yang** [comment]
Well, my problem is when I run a web application on server, I can not assess it in my ipad.

**Comment by ohhh-yang** [comment]
Thanks for reply. But my true problem is that when I run a web application in my server, however I can't assess the web in my local borwser with code App opened.
Bulit-in remote ssh can simply add a new server, whereas can't config port forward.
I wonder if the code app can just like VS Code, just Ctrl+click link in the terminal  then we can access the web in local browser.

**Comment by bummoblizard** [comment]
Configure port forwarding here:

![264929732-4c696d9d-518c-4232-a9b3-91cceca04182](https://github.com/thebaselab/codeapp/assets/38398443/9774c191-665c-44ba-bbe6-1c7cf10c0e47)

**Comment by bummoblizard** [comment]
@ohhh-yang Did it work for you?
