### ISSUE TITLE
File duplicate in contextual menus

### ISSUE THREAD

**Issue by pixelthing** [thebaselab/codeapp#107]
Hi - excited to start using code app - it's been developing so rapidly lately!

One small enhancement I would like to add to the list is to be able to duplicate files in the file browser, via the contextual menu. It's one of those small workflow adjustments that could really help!

Many thanks!

**Comment by bummoblizard** [comment]
Thanks for the suggestion! I will add this feature in the next release. Meanwhile, you can select multiple files or folders with a two-finger swipe gesture and duplicate them with the explorer menu.

**Comment by bummoblizard** [comment]
Added in https://github.com/thebaselab/codeapp-source/commits/main
