### ISSUE TITLE
file upload/download

### ISSUE THREAD

**Issue by MoonshineSG** [thebaselab/codeapp#1071]
file transfer to and from on the ssh would be a great addition

**Comment by bummoblizard** [comment]
While there isn't an upload button at the moment, you can download files by holding the file and select "Download".

**Comment by MoonshineSG** [comment]
somehow the upload is more important 😂
(of course there are other apps that can help with that but having all things in one all it's useful)

**Comment by bummoblizard** [comment]
Upload / download are now both available. 

![Image](https://github.com/thebaselab/codeapp/assets/38398443/e19ae42a-a945-4887-8029-1662f9675e57)
