### ISSUE TITLE
Keyboard Toolbar present even if it is turned off in settings

### ISSUE THREAD

**Issue by Drakenroft** [thebaselab/codeapp#1073]
As title, the keyboard toolbar is present even if it is turned off in settings (tried turning it back on->reload app->turning it off->reload app and it didn’t help)

![IMG_4792](https://github.com/thebaselab/codeapp/assets/35116091/4a1120e5-5a26-4de6-8c48-307925e634ec)

![IMG_4793](https://github.com/thebaselab/codeapp/assets/35116091/9be61a58-a0aa-4795-9290-31951859a833)

Also an unrelated question, while on the left of the phone there is the notch, can we remove the border on the right and get a tiny bit of more screen space? Its not a huge deal but since phone have limited screen size it would sure help.
Thanks a lot as always for your amazing app!

(I’m running version 1.7.2)

**Comment by bummoblizard** [comment]
Thank for the report. I can confirm it is a bug introduced in 1.7.2 and I will release a fix soon.

**Comment by bummoblizard** [comment]
This is fixed in 1.7.3, which is now available on the App Store.

**Comment by Drakenroft** [comment]
Thanks a lot!
Closing the issue since, i have updated on both iPhone and iPad and can confirm the fixes is live and working correctly
