### ISSUE TITLE
Terminal folders are hard to read, them for terminal would maybe help

### ISSUE THREAD

**Issue by 0507spc** [thebaselab/codeapp#109]
Folders are blue, which is hard to read on dark schemes:

![B5C974E1-029C-4584-96F4-1FB90E7F486B](https://user-images.githubusercontent.com/10354268/117677478-67420700-b1a6-11eb-8209-e2d169e2cf88.jpeg)

**Comment by bummoblizard** [comment]
It’s a problem with Xcode Theme, I’ll adjust the color of it in the next release.

**Comment by bummoblizard** [comment]
Fix committed: https://github.com/thebaselab/codeapp-source/commit/e46959085a604598af5fb25457a62440dd9fd26a
