### ISSUE TITLE
Can not remove added hostname based credentials

### ISSUE THREAD

**Issue by filiperochalopes** [thebaselab/codeapp#1093]
Version: 1.7.4 Build 278 (there is not version to update on Apple Store)

I just created some credential with test/wrong hostname, tried to remove but there is no option for that.

![image](https://github.com/thebaselab/codeapp/assets/34348097/5d28352e-abaa-4bcc-94b7-ab3b34ac8f39)

**Comment by bummoblizard** [comment]
Swipe to the left to delete.
![image](https://github.com/thebaselab/codeapp/assets/38398443/7b2ccef9-b129-4c30-abcc-e37e44d943f5)

**Comment by filiperochalopes** [comment]
My bad. It worked.
