### ISSUE TITLE
Can't pull repository from github.com using ssh authorization key

### ISSUE THREAD

**Issue by filiperochalopes** [thebaselab/codeapp#1094]
Version: 1.8.0 Build 289  
Previous Issues: I did not find any issue with this content neither on docs  

I generated a rsa 256 key trough alpine ish app as usual and copied public and private key content to the "Hostname Based Credentials" as follows: 

![image](https://github.com/thebaselab/codeapp/assets/34348097/d04ee2b8-7d72-4af2-bd74-d13705edd105)

When I try to copy my public repository `git@github.com:filiperochalopes/calc.filipelopes.med.br.git` it brings me an error:

![image](https://github.com/thebaselab/codeapp/assets/34348097/18b1ab34-d05a-4271-86e4-8f16010eeb12)

Is there a defined key format that codeapp supports?

Obviously I also added the public key to github.

**Comment by bummoblizard** [comment]
Hi. Try this instead: `ssh://git@github.com/filiperochalopes/calc.filipelopes.med.br.git`.


I will update the code to properly parse the url you used.

**Comment by filiperochalopes** [comment]
Tricky and no straightforward way to do but worked. Thanks! May keep this open until parse function release.

**Comment by bummoblizard** [comment]
The fix is now released on App Store.
