### ISSUE TITLE
How do I select lines of code

### ISSUE THREAD

**Issue by EnderRobber101** [thebaselab/codeapp#1119]
![image](https://github.com/user-attachments/assets/a62e81e7-caeb-4d30-b024-4ffea74d63ca)

I cannot select more than one word on this app. Dragging the end things don't work. How could I fix it? Thanks

**Comment by bummoblizard** [comment]
You might enable "Runestone editor".

![IMG_5D2DD23165EF-1](https://github.com/user-attachments/assets/10404525-934e-4640-8e64-2e460d51980f)

**Comment by EnderRobber101** [comment]
How do I copy text in terminal?
