### ISSUE TITLE
Line Numbers and Minimap

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#114]
These settings do not hold to their value when re-springing the app, in UI-Restoration mode, even if disabled...

https://drive.google.com/file/d/1NPVgvs6bpTxAe1QBjmIKWG_ch22-wqzt/view?usp=sharing

**Comment by bummoblizard** [comment]
Hi. Did you try updating to the latest version?

**Comment by bummoblizard** [comment]
I can reproduce this. Thanks for the report, I will fix it as soon as possible.

**Comment by bummoblizard** [comment]
Fix committed: https://github.com/thebaselab/codeapp-source/commits/main
