### ISSUE TITLE
Simple indentation update, should be easy to implement (hopefully)

### ISSUE THREAD

**Issue by LeftClickMage** [thebaselab/codeapp#1155]
https://github.com/user-attachments/assets/30596b20-1ced-4ee6-bfb7-b9639dc50d23

Can you make it so that when you press enter after creating an html tag, have it be on 2 separate lines, and indent in the middle?

Like at the end of the video?

**Comment by bummoblizard** [comment]
This is now supported in the 1.10.0 update!

**Comment by LeftClickMage** [comment]
Thanks! How should I update my app? It doesn’t give the option to update it.

**Comment by bummoblizard** [comment]
It will be available on the App Store shortly.

**Comment by LeftClickMage** [comment]
Okay, thanks so much!
