### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#117]
I would like to possibly see PHP local runtime support similar to what: JS, PY, and HTML support. 
___
EDIT: In the long run, I think there should be support for all files, where it is possible, for offline runtimes. Then add offline support when the app gets a new supported language added. For example, add offline support when it begins to support the programming language. It would make things more simplistic and give the app more quality. I would start with the highly requested programming languages first, then go through the Front End Web Development languages, and finally, go through the Back End Web Development language to add offline support.

**Comment by bummoblizard** [comment]
Thank you for your suggestion! However, adding a language support is not as straightforward as it seems. Many languages require heavy modifications and patches to be able to cross-compile for iOS. Maintaining forked builds of these languages could also be challenging and would also increase the app size by a significant amount. With that being said, it's in the plan to include Java and C runtime, as they are the most popular languages in the app, coming after Python and JS.

**Comment by Lukas-Batema** [comment]
> Thank you for your suggestion! It surely would be great to be able to run these languages offline. However, adding a language support is not as straightforward as it seems. Many languages require heavy modifications and patches to be able to cross-compile for iOS.
> 
> Maintaining forked builds of these languages could also be challenging and would also increase the app size by a significant amount. With that being said, it's in the plan to include Java and C runtime, as they are the most popular languages in the app, after Python and JS.
> 
> For now, I would like to focus on these 4 languages and implement other advanced features such as debugging and auto completion.

I would think if PHP is too hard to do, I am sure Swift is easily done, since it is native to Apple, and I assume the app is written in it, as well.

**Comment by bummoblizard** [comment]
PHP is available in the latest release.
