### ISSUE TITLE
terminal command ssh caused crash

### ISSUE THREAD

**Issue by czln** [thebaselab/codeapp#12]
unable to use command ssh via password. After I enter my password, the hole terminal just crashed.
device: ipad pro a1980
os: IPadOS 14.2

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by bummoblizard** [comment]
Hello.
I can confirm there are indeed issues with the ssh command. I'll need to investigate into the problem.
