### ISSUE TITLE
Git ellipses disappear when cursor hovers over them

### ISSUE THREAD

**Issue by httpjamesm** [thebaselab/codeapp#127]
![image](https://user-images.githubusercontent.com/51917118/119385876-cc145b80-bc94-11eb-8282-c1fd131a14f4.jpeg)

When my cursor hovers over the button to push in the source control tab, it just disappears. I have to touch it in order to push.

**Comment by Lukas-Batema** [comment]
@httpjamesm Why did you close this? I just am wondering, as it doesn't seem like it is solved yet :)

**Comment by bummoblizard** [comment]
This is probably related to SwiftUI again. There was a problem of cursor hover animation that is fixed on iPadOS 14.5.
