### ISSUE TITLE
C++编译时main不能变编译头文件

### ISSUE THREAD

**Issue by 1OZ4** [thebaselab/codeapp#128]
您好，我在使用这个编译c++程序的时候，并不能将我的头文件一起进行编译，我在网上也找不到如何远程编译，如果您有相关的教程的话，希望您能告知我一下，万分感谢

**Comment by bummoblizard** [comment]
￼你好，目前在远端编译时￼头文件需要￼放在源文件的同一directory。￼￼

**Comment by bummoblizard** [comment]
例如这样：￼￼
![image](https://user-images.githubusercontent.com/38398443/119590990-621cc300-be08-11eb-98c3-a957d4e380e3.jpeg)

**Comment by 1OZ4** [comment]
我已经把它们放到同一个文件夹里面了，但是还是会出现错误undifend reference to，我不清楚是不是头文件未能成功编译的原因，如果是多个cpp和头文件，也是放到同一个目录里面然后直接运行main函数就可以成功运行吗

**Comment by bummoblizard** [comment]
￼应该是的，或者你可以提供代码给我尝试￼￼￼￼。

**Comment by 1OZ4** [comment]
我已经将我用到的例程用邮件发送到您在app里面留下的电邮地址上了

**Comment by bummoblizard** [comment]
￼瞭解，如果多個cpp暫時是不支持的，我會嘗試加入這個功能。￼

**Comment by 1OZ4** [comment]
希望可以早点上线这个功能，xp xp n

**Comment by bummoblizard** [comment]
在最新的版本可以使用本地clang编译，解决了这个问题。
