### ISSUE TITLE
Cannot set own class name in java

### ISSUE THREAD

**Issue by baomessi** [thebaselab/codeapp#129]
Hi, 

I am running into an issue that is, if I try to set my own class name in java like “public class Test{}”, and meanwhile I also set my filename to Test.java. It says that it should be declared in a file named Test.java, which rather is my file name. But when I try rename the class name to Main, it works even if the filename is not Main.java. Is this a bug or I miss something? Could you help me with that as soon as possible? Thank you very much

Regards,
Chenxu

**Comment by bummoblizard** [comment]
Hello. It's a limitation of the execution's implementation. Basically, the execution server (https://github.com/judge0/judge0) renames the running code into Main.java. I will see how I can change this behaviour.

**Comment by baomessi** [comment]
Yeah,  hope you can figure out and update, really looking forward to that!

**Comment by bummoblizard** [comment]
This issue was resolved in a previous update. On another note, local Java is now available in the latest TestFlight build. You can use java and javac to run Java programs locally.
