### ISSUE TITLE
Would codeapp always be free?

### ISSUE THREAD

**Issue by zzl-learner** [thebaselab/codeapp#135]
It’s really fortunate for me to find such a convenient developing tool on iPad. Because as far as I know , Apple doesn’t allow new environment on IPadOS, which is really a barrier in making iPad a truly productivity tool. But now I’m wondering if it is possible for us to depend on it all the time. Would there be a premium edition in the future? If so, would it be monthly subscribed or just buyout one time?
Looking forward to your reply.

**Comment by bummoblizard** [comment]
Hey, thank you for your nice word! I'm glad that you find the app useful.

At the moment, I don't plan to publish a premium version or implement any in-app purchases as it's now already a one time purchase for $3.99. Therefore, if you downloaded it for free during the initial release, there won't be any future charges.

**Comment by zzl-learner** [comment]
Thank you for your illustrations! I’ve been using it since it was called VScode. So I don’t know it’s now already a one time purchase app. At that time all codes need to be run on the server. And multiple files seems to be unsupported. It been a interesting experience to witness the app’s development. 

I think your work is remarkable not only because of its convenience  but also because the idea behind it.
Apple launched their laptop and pad products with M1 chips lately. I think maybe they are trying to blur the lines between this two products, which, for iPads, will unlock the possibility to be both portable and productive. As far as I know, the latest version iPad pro performs did a great job  in games and video editing. 

However, it’s a pity that developing tools can hardly be seen in AppStore, especially ones with local complier. I think programming is a key field in productivity. And ones with local complier will be really helpful. But for me I just saw some notebooks app with local python. I know it’s because of the policies due to safety concerns. And I don’t think they will change the rules in the future for Apple is always strict with safety issues. That’s why I highly recommend your work. At least for me, your app released me from carrying a heavy gaming laptop with its charger. And an iPad’s battery  is more durable than a laptop. I have tried remote-control apps but the network sometimes crashes. Considering the possible usage scenario of iPad, such as classroom, libraries ,cafeteria or even on the train, I might recommend it to my classmates with iPads. Because your work is currently the choice with the best experience, and maybe the only choice in certain circumstances.

**Comment by Lukas-Batema** [comment]
> Hey, thank you for your nice word! I'm glad that you find the app useful.
> 
> At the moment, I don't plan to publish a premium version or implement any in-app purchases as it's now already a one time purchase for $3.99. Therefore, if you downloaded it for free during the initial release, there won't be any future charges.

I didn't know that it costs money now either, so I must've gotten it for free at the very end of its initial release...

**Comment by Lukas-Batema** [comment]
> Thank you for your illustrations! I’ve been using it since it was called VScode. So I don’t know it’s now already a one time purchase app. At that time all codes need to be run on the server. And multiple files seems to be unsupported. It been an interesting experience to witness the app’s development. 
> 
> 
> 
> I think your work is remarkable not only because of its convenience  but also because the idea behind it.
> 
> Apple launched their laptop and pad products with M1 chips lately. I think maybe they are trying to blur the lines between this two products, which, for iPads, will unlock the possibility to be both portable and productive. As far as I know, the latest version iPad pro performs did a great job  in games and video editing. 
> 
> 
> 
> However, it’s a pity that developing tools can hardly be seen in AppStore, especially ones with local complier. I think programming is a key field in productivity. And ones with local complier will be really helpful. But for me I just saw some notebooks app with local python. I know it’s because of the policies due to safety concerns. And I don’t think they will change the rules in the future for Apple is always strict with safety issues. That’s why I highly recommend your work. At least for me, your app released me from carrying a heavy gaming laptop with its charger. And an iPad’s battery  is more durable than a laptop. I have tried remote-control apps but the network sometimes crashes. Considering the possible usage scenario of iPad is flexible and don’t have stable network connection , such as classroom, library ,cafeteria or even on the train, I might recommend it rather than remote control apps to my classmates with iPads. Because your work is currently the choice with the best experience, and maybe the only choice in certain circumstances.
> 
> 
> 
> cant wait to see more local functions available.

I agree with this, I got it when it was called Code App (at the very end of the free period it seems like), and have been using it on my iPhone ever since. One complaint, is that it doesn't work on my iOS 12 iPad Air. I realize that it probably is t capable of running it anyways, but if possible, I would love to see the iPadOS/iOS restriction lowered, unless Apple doesn't allow it. Thanks, @bummoblizard!

**Comment by bummoblizard** [comment]
> > Thank you for your illustrations! I’ve been using it since it was called VScode. So I don’t know it’s now already a one time purchase app. At that time all codes need to be run on the server. And multiple files seems to be unsupported. It been an interesting experience to witness the app’s development. 
> > 
> > 
> > 
> > I think your work is remarkable not only because of its convenience  but also because the idea behind it.
> > 
> > Apple launched their laptop and pad products with M1 chips lately. I think maybe they are trying to blur the lines between this two products, which, for iPads, will unlock the possibility to be both portable and productive. As far as I know, the latest version iPad pro performs did a great job  in games and video editing. 
> > 
> > 
> > 
> > However, it’s a pity that developing tools can hardly be seen in AppStore, especially ones with local complier. I think programming is a key field in productivity. And ones with local complier will be really helpful. But for me I just saw some notebooks app with local python. I know it’s because of the policies due to safety concerns. And I don’t think they will change the rules in the future for Apple is always strict with safety issues. That’s why I highly recommend your work. At least for me, your app released me from carrying a heavy gaming laptop with its charger. And an iPad’s battery  is more durable than a laptop. I have tried remote-control apps but the network sometimes crashes. Considering the possible usage scenario of iPad is flexible and don’t have stable network connection , such as classroom, library ,cafeteria or even on the train, I might recommend it rather than remote control apps to my classmates with iPads. Because your work is currently the choice with the best experience, and maybe the only choice in certain circumstances.
> > 
> > 
> > 
> > cant wait to see more local functions available.
> 
> I agree with this, I got it when it was called Code App (at the very end of the free period it seems like), and have been using it on my iPhone ever since. One complaint, is that it doesn't work on my iOS 12 iPad Air. I realize that it probably is t capable of running it anyways, but if possible, I would love to see the iPadOS/iOS restriction lowered, unless Apple doesn't allow it. Thanks, @bummoblizard!

Unfortunately, it's a SwiftUI's limitation. Only iOS 13 or above supports it. But regardless, the OG iPad Air is probably too slow for monaco editor. I tested it before with an iPad mini 2 and it's unusable.

**Comment by zzl-learner** [comment]
> > Hey, thank you for your nice word! I'm glad that you find the app useful.
> > At the moment, I don't plan to publish a premium version or implement any in-app purchases as it's now already a one time purchase for $3.99. Therefore, if you downloaded it for free during the initial release, there won't be any future charges.
> 
> I didn't know that it costs money now either, so I must've gotten it for free at the very end of its initial release...

hahaha, we really picked up a bargain.

**Comment by Lukas-Batema** [comment]
> > > Hey, thank you for your nice word! I'm glad that you find the app useful.
> 
> > > At the moment, I don't plan to publish a premium version or implement any in-app purchases as it's now already a one time purchase for $3.99. Therefore, if you downloaded it for free during the initial release, there won't be any future charges.
> 
> > 
> 
> > I didn't know that it costs money now either, so I must've gotten it for free at the very end of its initial release...
> 
> 
> 
> hahaha, we really picked up a bargain.

Yeah, we sure did :) This is a great app! I would pay at least 7.99 USD, if I wasn't a poor high school student :(
