### ISSUE TITLE
Add support for Node.js Internationalization (I18n) | Failed to run jest (v27.0.3) in the terminal

### ISSUE THREAD

**Issue by momocow** [thebaselab/codeapp#136]
When running `jest` in the terminal I got the following error.

```
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid property name in character class
    /node_modules/jest-validate/node_modules/camelcase/index.js:37:15
```

I found the same error [here](https://github.com/sindresorhus/camelcase/issues/63#issuecomment-632275988) but I have no idea how to apply the solution in Codeapp.

The solution in the link requires an option when building Node, that is, `--with-intl=small-icu` to enable [RegExp Unicode Property Escapes](https://github.com/tc39/proposal-regexp-unicode-property-escapes).

Thank you for a nice App anywhere!

**Comment by bummoblizard** [comment]
I will try to compile Node.js with this flag and see if it works.
