### ISSUE TITLE
my opinion on the new design of the app

### ISSUE THREAD

**Issue by louka-dubois** [thebaselab/codeapp#138]
Hey! This is to give my opinion on the new design of the app.

In my opinion the old design was better even though it looked a lot like vscode (and that's what I liked about this design)

maybe you should make an option to switch from the old design to the new one and vice versa

But question aside, what is this button?

![image](https://user-images.githubusercontent.com/78066493/120705673-1f9d5b00-c486-11eb-8069-a7f6fdc13b03.jpeg)

**Comment by bummoblizard** [comment]
Hi. Thanks for the feedback. I'll bring back the activity bar in the next build and only apply the new interface with compact devices (iPhones) and also make the show keyboard button opt-in as some users reported difficulties opening up their keyboard. 

For now, if you would like to revert to the old interface, you might install a previous version from TestFlight or download the app from App Store.

**Comment by bummoblizard** [comment]
Activity bar (side bar) is now back in the latest build.
