### ISSUE TITLE
Slow Git clone

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#14]
Cloning a repository is pretty slow generally, especially when the repository has a large amount of files. At times, it would even raise error and unable to clone large repositories.

This renders the app unusable for large projects.

**Comment by apwelsh** [comment]
I second this.  My repo takes just a second to clone on Mac, but nearly 40 seconds here.

**Comment by bummoblizard** [comment]
Update: The issue will be fixed in the next version.

**Comment by bummoblizard** [comment]
Fix released.
