### ISSUE TITLE
Credentials callback returned an invalid cred type.

### ISSUE THREAD

**Issue by justiceserv** [thebaselab/codeapp#140]
Hello, I am having issues with Version Control - Credentials part, I typed in username and Private Access Token, but it still says "Credentials callback returned an invalid cred type.". I was trying to commit to my own public repository, and I tried both Private Access Token and password for this, but still same error comes out. Is there anyone who can help me with this?
![image](https://user-images.githubusercontent.com/51410592/120885039-aa668d00-c621-11eb-815d-20a8564d9998.png)

**Comment by bummoblizard** [comment]
Hello. Is it a GitHub repository or from other sites? Also make sure you have given the appropriate permissions to the personal access token.

**Comment by justiceserv** [comment]
> Hello. Is it a GitHub repository or from other sites? Also make sure you have given the appropriate permissions to the personal access token.

Hi, this is a Github repository, and I checked all permission available.

**Comment by justiceserv** [comment]
It was just my ipad’s setting problem, after reinstalling several times, I was able to remove read-only and able to commit push. Thanks and sorry for taking your time.
