### ISSUE TITLE
Add ability to connect to remote server

### ISSUE THREAD

**Issue by aescolastico** [thebaselab/codeapp#144]
Does the app allow you to install Linux tooling on the remote server that also runs c++ go etc? I need to be able to use tools like azure cli heroku and Adobe spark for development.

**Comment by bummoblizard** [comment]
There is no support for installing linux binaries. The latest TestFlight version includes `clang++` though. You can compile C++ code with `clang++` and run with `wasm`.

Heroku requires `git`, which has a GPL license that is incompatible with App Store. As for Adobe spark, it is already available as an iOS app. I will take a look at Azure cli and see if it's possible to include it in the app.

**Comment by bummoblizard** [comment]
SSH remote is now available.
