### ISSUE TITLE
Git Pull from (HTTPS) Gitlab Server results in error.

### ISSUE THREAD

**Issue by arch-linux** [thebaselab/codeapp#147]
When I attempt to clone my gitlab code in this app I receive an error "clone error: credentials returned an invalid cred type" 

Cloning from this location works in all other git clients. 

Thanks.

**Comment by arch-linux** [comment]
If you guys need a gitlab account/example to test this issue on let me know I can provide one.

**Comment by bummoblizard** [comment]
This could be related to #118. Downloading the TestFlight version would solve this.

**Comment by bummoblizard** [comment]
See https://github.com/thebaselab/codeapp/issues/137

**Comment by bummoblizard** [comment]
You might also need to add your credentials by `Settings > Version Control > Authentication`.

**Comment by arch-linux** [comment]
The TestFlight you referred to crashes immediately on my iPad 11 Pro, I "shared" the crashes using apples built-in feature. 

I removed the app completely, reinstalled using TestFlight -> same result. 

As far as the previous #118 reference, this looks like the exact issue I am having, so if we could resolve the crashing problem that would likely resolve this case. 

Would you like me to open a new issue?

Thanks for the support. 

Chris

**Comment by arch-linux** [comment]
Disregard my last comment, I was able to get it by a few uninstalls. Anyhow if you get a crash report it might still be helpful. 

The TestFlight fixed my issue. 🎉

Thank you! This support is excellent
