### ISSUE TITLE
Git Push/Commit (May 2021 TestFlight)

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#148]
When committing changes, it says the were pushed, but never show up on the public repo that I own, and I know I have my credential right and my personal access token permissions correct.

**Comment by Lukas-Batema** [comment]
It just had to be pushed. It used to automatically do that, this still may be a bug. I would keep this open.

**Comment by bummoblizard** [comment]
Git commit and git push are two different operations. I believe this is the expected behaviour.

**Comment by Lukas-Batema** [comment]
> Git commit and git push are two different operations. I believe this is the expected behaviour.

I realize that, I meant that they don't automatically do their job, like they used to.
