### ISSUE TITLE
UI problem: left function buttons blinks when the mouse circle hover on

### ISSUE THREAD

**Issue by iblueer** [thebaselab/codeapp#150]
UI problem: left function buttons blinks when the mouse circle hover on

Version: 1.2.3 Build 12.

Device: 2020 iPad Pro 11(not M1) with Magic Keyboard.

System: iPadOS 14 & iPadOS 15.

**Comment by bummoblizard** [comment]
Can you reproduce it on the latest TestFlight build? 
https://testflight.apple.com/join/EgZ8sE2P

**Comment by iblueer** [comment]
> Can you reproduce it on the latest TestFlight build? 
> 
> https://testflight.apple.com/join/EgZ8sE2P

No, the bug disappeared on the TF build.
