### ISSUE TITLE
Crashing (May 2021 TestFlight)

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#151]
The app crashes when not running any files or using the terminal, but just writing code. I think it may be the JS/TS server dying for some reason; I haven't checked other languages, but it may have similar problems in others. This bug makes the app unusable. It also crashes almost instantly, when copy and pasting. Here is a code from my Google Drive with an example: https://drive.google.com/file/d/1pyS0S2GSUz2cXSsq8IpSk80jcxhFKjf9/view?usp=drivesdk

EDIT: I found that if you have the settings app setting for file location different than "On my iPhone" it crashes it.

**Comment by Lukas-Batema** [comment]
Looks like it got fixed in the newest build.

**Comment by bummoblizard** [comment]
> Looks like it got fixed in the newest build.

Cool! Feel free to reopen if the issue came back.
