### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arvobrendon** [thebaselab/codeapp#155]
Hello there ! 
I’m interested in buying this app 
Am I allowed to use cd ~/documents 
I’m using venv to launch my folder

python manage.py runserver

2. Questions 
Can I upload local file too ?

instead of GitHub

**Comment by bummoblizard** [comment]
`venv` is unsupported for now. As for `cd ~/documents`, the file system on iOS works a bit differently. Every app has their own `Document` folder and the default folder for Code App as the `Document` folder of its own. You can open locations from other apps though.

For the second question, I'm not sure what you mean by uploading local file. You can of course work on local files without uploading to a repository.

You are also welcome to tryout the TestFlight version before deciding to purchase: #137 
Note that there might be crashes as it's not the final version.
