### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by HardeepAsrani** [thebaselab/codeapp#156]
Are there any plans on adding FTP support? So we could FTP into the server, edit the files and send back to it?

That will make this app perfect for half of my work.

Other half is stuck on not having a web inspector but that's not scope of this app. :)

Let me know if there any any such plans to support s/FTP to allow users to edit files on the go.

**Comment by bummoblizard** [comment]
Yes! FTP as well as SSH are something I plan to work on. I'll let you know as soon as the features available for testing.

**Comment by Dids** [comment]
Any news on this? This is currently a "must have" feature for some of the legacy client projects I work with, preferably with automatic uploading when editing files.

If or when this feature hits (hopefully with both FTP and SFTP support), I'd wager it'll be amazing for a lot of people, not just me. :)

**Comment by bummoblizard** [comment]
> Any news on this? This is currently a "must have" feature for some of the legacy client projects I work with, preferably with automatic uploading when editing files.
> 
> 
> 
> If or when this feature hits (hopefully with both FTP and SFTP support), I'd wager it'll be amazing for a lot of people, not just me. :)
> 
> 
> 
> EDIT: I noticed that PRs are enabled, so if you do need/accept help with this, I might be able to contribute as well.

Got it. Making it a priority :)

**Comment by bummoblizard** [comment]
Here's the progress of far. It now supports FTP and FTPS servers.  I'm hoping to release a TestFlight version in the coming days.

![image](https://user-images.githubusercontent.com/38398443/128626416-0ba007ea-9425-4582-8f2e-7c4b316c3936.png)
![image](https://user-images.githubusercontent.com/38398443/128626427-3b6db92a-8a02-4b30-8cf1-ea1ffa0fabaf.png)

**Comment by Tippye** [comment]
Has this feature been added? Why can't I find it?

**Comment by Lukas-Batema** [comment]
It's not added yet, @Tippye
