### ISSUE TITLE
Editor lagging randomly

### ISSUE THREAD

**Issue by FruitPigFoot** [thebaselab/codeapp#158]
I’m learning java for the first time and i was curious about running it on the terminal. Sorry to bother but could you help? Also there’s another issue.  I’m on Ipad pro 4th gen with magic keyboard(not bluetooth ver the expensive one) . The app works great but there’s an issue once everday. I dont know why but after few hours of coding, the app just starts to lag. When trying to type something, is would take more than a minute to type just one word. That issue lasts about a hour and it suddenly disappears. Am i the only one experiencing this? If not, is there any tip you suggest for this issue?

**Comment by bummoblizard** [comment]
Hello. Regarding the lagging, a quick fix would be reopening the app by manually closing the app in the app switcher. However, I would like to know more details so that I can reproduce it. For example, were you opening a large git repository? Does the lag occurs with a specific programming language?

For Java, I am still working on bringing local support to Code App. Currently, it's only possible to run Java code on a server.

**Comment by fuckucode** [comment]
I tried closing the code app task and reopened but still the issue wasn't gone. So I also tried turning the ipad off and turned it back on but still the lagging continued. I haven't used git repository on this app. Just compiled locally on this app only.

**Comment by bummoblizard** [comment]
That is a rather weird issue. Are able to provide me a screenshot and le me investigate? You can also send it to support@thebaselab.com if you wish.

**Comment by fuckucode** [comment]
I'll record the screen once it happens. Thanks!

**Comment by fuckucode** [comment]
I've recorded the issue and sent it to support@thebaselab.com.

**Comment by bummoblizard** [comment]
> I've recorded the issue and sent it to support@thebaselab.com. 
> 

Thanks! I've looked at it. Does the lag only present with the new file sheet? Or it is also affecting the editor itself?

**Comment by fuckucode** [comment]
It affects through everything on this app, not just with the new file sheet.
