### ISSUE TITLE
Problems with trackpad

### ISSUE THREAD

**Issue by AlexGiulioBerton** [thebaselab/codeapp#162]
Hi,
I'm using this app on an ipad with magic keyboard. I have a lot of problems with the trackpad (it doesn't work always, problem with icon on the left bar, text selection, ...).
I hope this comment can be useful, by the way.. great app!!!

**Comment by bummoblizard** [comment]
Hello, I'm sorry for the problems you have encountered. Please see if the TestFlight version improve things: https://testflight.apple.com/join/EgZ8sE2P

**Comment by DaneHoffman** [comment]
Looks like your version 1.2.4 release fixed the issue, I don’t see it on that TestFlight beta

**Comment by bummoblizard** [comment]
This should be fixed in the latest build. Feel free to reopen if issue persists.
