### ISSUE TITLE
Three dot menu in source control section disappears and does nothing when clicked with trackpad

### ISSUE THREAD

**Issue by DaneHoffman** [thebaselab/codeapp#163]
There’s a button in the source control section next to the commit button that looks like three small blue dots in a blue circle. When I touch it with the touchscreen, it gives me the options to push, fetch, or stage all changes. But when the button is hovered over using a trackpad such as the magic keyboard trackpad, the button disappears and then does nothing when clicked. 

Version: 1.2.4

**Comment by bummoblizard** [comment]
I can reproduce. Will fix this soon.

**Comment by bummoblizard** [comment]
This should be fixed in the latest build. Please try it out :)

**Comment by DaneHoffman** [comment]
Yup, issue is fixed!
