### ISSUE TITLE
 Change branch in private repository

### ISSUE THREAD

**Issue by SuhanovO** [thebaselab/codeapp#17]
When I use private repository (not GitHub) I can’t change branch from master to another

**Comment by bummoblizard** [comment]
Changing branch is not yet supported. I will add this feature in the future.

**Comment by apwelsh** [comment]
This s critical.  Please add sooner.  this app is useless otherwise, as it claims it is working on master branch, but it does not appear to be correct.  It appears to be pulling my feature branch.

**Comment by bummoblizard** [comment]
It is indeed. I already have this working in an unreleased version. The update should be released in a few days.

**Comment by bummoblizard** [comment]
Fix released. Please reopen if the problem persists.
