### ISSUE TITLE
github security key

### ISSUE THREAD

**Issue by sonaldo** [thebaselab/codeapp#174]
How can I trust putting my github key? Is any data provided for your server? Do you store this key somewhere?

**Comment by bummoblizard** [comment]
Hello. Your GitHub key is encrypted and stored locally on your device using Apple's [Keychain Services](https://developer.apple.com/documentation/security/keychain_services). You might also limit the permission granted by the Personal Access Token when you create it in GitHub.

**Comment by sonaldo** [comment]
Sorry to ask here, I didn't find it anywhere.
