### ISSUE TITLE
User inputs not working properly in C / C++

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#177]

**Comment by avltree9798** [comment]
I also faced this issue
`// Created on Anthony’s iPad.

#include <stdio.h>

int main() {
   // printf() displays the string inside quotation
   char test[30];
   scanf("%s", test);
   printf("%s\n", test);
   return 0;
} `

That code can be compiled but won’t run

**Comment by bummoblizard** [comment]
Fix will be released in a day or two. It's a strange issue related to compiler optimization and was overlooked in my tests.

**Comment by bummoblizard** [comment]
Fix released.
