### ISSUE TITLE
typescript d.ts 和导入误报错

### ISSUE THREAD

**Issue by smallmain** [thebaselab/codeapp#179]
1.克隆任何一个 typescript 源码库，文件中的导入都会报错找不到模块。

2.d.ts 中 declare namespace cc 会报错 duplicate identifier cc

以上两个问题在 vscode 是正常的

3.应用里显示的是3.7.4，是否只是显示错误

4.下次大版本更新是否能更新到typescript 4.3，增加了 override ，很有用

感谢这么快速地更新到了4.2

**Comment by bummoblizard** [comment]
1. 这个有关多文件的支持￼，需要透过未来更新支援￼。目前编辑器只会分析已经开启的档案￼￼。
2. 应该是bug，会尽快修复￼
3. 对的，只是显示错误￼。￼编辑器的TypeScript版本需要透过app￼更新，但terminal内的tsc 可以用`npm install -g typescript`自行更新
￼4. ￼会的

**Comment by TheSmallMain** [comment]
感谢，比较致命的问题是第一点，导致现在我就算只是想在 ipad 上用 codeapp 预览一下代码都不太实用，希望能解决

**Comment by bummoblizard** [comment]
明白，会尽量改善这问题。

**Comment by Mister-Hope** [comment]
能否进一步更新ts版本，我的项目使用了moduleResolution: NodeNext，目前完全不能正常使用。
![78CC7929-15CB-499D-844E-CE98C65E5A3F](https://user-images.githubusercontent.com/33315834/196355785-1a1d60e1-ee6f-4cb7-bcc3-c8224930855b.png)

**Comment by Mister-Hope** [comment]
我对 ios 开发很不熟悉，所以我没找到 TS 的引入位置，希望能够尽快得到支持（顺便改进了一下中文本地化）

**Comment by Mister-Hope** [comment]
我不认为这个问题被修复了，如果你觉得你已经不存在原问题，计划关闭的话，那我就新开一个。

**Comment by Mister-Hope** [comment]
@bummoblizard 感谢，请问有计划更新一下内置的ts版本么？不太清楚有什么困难，但至少ts不应该有ios适配方面的问题。

能够在ipad上临时应急改个项目还是不错的，（虽然已经有vscode.dev了）

**Comment by bummoblizard** [comment]
@Mister-Hope 上游 Monaco Editor 仍在4.5.5。如果你真的需要，我可以手动更新它。

https://github.com/microsoft/monaco-editor/blob/f20e0c8d472bababab79108dff951ae09460c4ed/src/language/typescript/lib/typescriptServicesMetadata.ts#L5

**Comment by Mister-Hope** [comment]
恩恩，还是建议更新一下吧😅因为我在使用一些新版本的特性。

**Comment by Mister-Hope** [comment]
恩恩，还是建议更新一下吧😅因为我在使用一些新版本的特性。

**Comment by smallmain** [comment]
懒得跟进了，作者有空就加吧
