### ISSUE TITLE
Select All keyboard shortcut don't work

### ISSUE THREAD

**Issue by avltree9798** [thebaselab/codeapp#181]
Hi, I'm loving y'all works, but I have a little problem, the select all (cmd+a) keyboard shortcut can't work at all
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/16130362/124508951-1d1e8000-ddfb-11eb-876b-e339878bf4b5.png">

So every time I want to rewrite my code I have to use my trackpad

**Comment by bummoblizard** [comment]
Hello, thanks for opening the issue. I can't seem to reproduce the issue though. Would you be able to provide more information to let me reproduce this?

For example, which input method and keyboard model are you using?

**Comment by avltree9798** [comment]
> Hello, thanks for opening the issue. I can't seem to reproduce the issue though. Would you be able to provide more information to let me reproduce this?
> 
> For example, which input method and keyboard model are you using? Which iPadOS version are you on?

iPadOS 15 latest beta, I use Apple Magic Keyboard for iPad, the input method is English (UK)

**Comment by bummoblizard** [comment]
I can confirm this is a problem specific to iPadOS 15. Thanks for the report!

**Comment by bummoblizard** [comment]
I have released the fix on App Store. It should be available to download very soon.
