### ISSUE TITLE
Trouble in txt file reading

### ISSUE THREAD

**Issue by zzl-learner** [thebaselab/codeapp#184]
When I use C/C++ compiler, I just can't read the txt file(Both C and C++ method are tried). When reading, the app would crash.

**Comment by bummoblizard** [comment]
I can confirm this, thank you for your report.

**Comment by bummoblizard** [comment]
I have identified the issue and a fix will be released soon.

**Comment by zzl-learner** [comment]
Thank you so much.

**Comment by bummoblizard** [comment]
I've released the fix on App Store.
