### ISSUE TITLE
Directory tree unresponsive after awaking from app suspension

### ISSUE THREAD

**Issue by DaneHoffman** [thebaselab/codeapp#185]
When opening the app from the multitasking menu after it has entered suspension, clicking directories in the directory tree does not expand them for about 10 seconds.

**Comment by bummoblizard** [comment]
Thanks for opening the issue. Is the directory local or on a SMB server?

**Comment by DaneHoffman** [comment]
The directory is local, it's stored in the code app directory on the iPad.

**Comment by bummoblizard** [comment]
That's rather unusual, I can't seem to reproduce it. Does it occur all the time or on certain directories only? Which iOS version are you on?

**Comment by DaneHoffman** [comment]
I should probably have mentioned that I'm on the iPadOS 15 beta. I've encountered it about 3 or 4 times in total over the past two weeks, I'll see if I can link a screen recording of the issue.

**Comment by bummoblizard** [comment]
Got it. Thanks for additional information! The problem could originate from iPadOS 15. I'll keep an eye on this issue.

**Comment by DaneHoffman** [comment]
Screen recording of the issue: https://youtu.be/r3Fycp7mVIU

**Comment by bummoblizard** [comment]
Thanks for the video! Here's something you can try: right click on any file and it should become responsive again.

If the above method works, this issue is a known issue related to a bug from Apple.

**Comment by DaneHoffman** [comment]
Yes, right-clicking does make the directory tree responsive again.
