### ISSUE TITLE
Issues with cloning large repo

### ISSUE THREAD

**Issue by GlazedPineapple** [thebaselab/codeapp#192]
I am trying to clone a large repo(5.7gigs) and when I use the git cli it just freezes. Even when I use the -v command, it doesn’t print anything out besides a warning (see screenshot).
![4946F178-2BDD-40C7-8A47-64A325F4957B](https://user-images.githubusercontent.com/40650629/125703445-7e885a40-6619-4383-8cb5-4d81ee426586.jpeg)

**Comment by bummoblizard** [comment]
Git cli is currently an experimental port, so many features including clone and push are not available. For these operations, please use the GUI instead.

**Comment by GlazedPineapple** [comment]
Okay sounds good. Just wondering, if I use the source control to clone a repo, will it keep going if I switch to a different app? Thanks

**Comment by bummoblizard** [comment]
> Okay sounds good. Just wondering, if I use the source control to clone a repo, will it keep going if I switch to a different app? Thanks

No. You'll need to keep it in the foreground.

**Comment by jwood803** [comment]
I'm also cloning a decent size repo (1.5 gig) and using the UI. It seems to just freeze at zero percent.

Are there logs or anything to see if an error occurred?

**Comment by bummoblizard** [comment]
> I'm also cloning a decent size repo (1.5 gig) and using the UI. It seems to just freeze at zero percent.
> 
> Are there logs or anything to see if an error occurred?

This issue is tracked in https://github.com/thebaselab/codeapp/issues/124. I am trying to improve this. Currently, you'll need to patiently wait for it to complete.

**Comment by bummoblizard** [comment]
> > I'm also cloning a decent size repo (1.5 gig) and using the UI. It seems to just freeze at zero percent.
> > Are there logs or anything to see if an error occurred?
> 
> This issue is tracked in #124. I am trying to improve this. Currently, you'll need to patiently wait for it to complete.

The cloning progress is now displayed properly. I'll let you know once it's available on TestFlight.

**Comment by GlazedPineapple** [comment]
> > > I'm also cloning a decent size repo (1.5 gig) and using the UI. It seems to just freeze at zero percent.
> 
> > > Are there logs or anything to see if an error occurred?
> 
> > 
> 
> > This issue is tracked in #124. I am trying to improve this. Currently, you'll need to patiently wait for it to complete.
> 
> 
> 
> The cloning progress is now displayed properly. I'll let you know once it's available on TestFlight.

How can I sign up for TestFlight?

**Comment by bummoblizard** [comment]
> > > > I'm also cloning a decent size repo (1.5 gig) and using the UI. It seems to just freeze at zero percent.
> > 
> > 
> > > > Are there logs or anything to see if an error occurred?
> > 
> > 
> > > 
> > 
> > 
> > > This issue is tracked in #124. I am trying to improve this. Currently, you'll need to patiently wait for it to complete.
> > 
> > 
> > The cloning progress is now displayed properly. I'll let you know once it's available on TestFlight.
> 
> How can I sign up for TestFlight?
> Also thanks for fixing the issue!! :)

https://testflight.apple.com/join/EgZ8sE2P
