### ISSUE TITLE
can’t git pull or push, ping always timeout

### ISSUE THREAD

**Issue by windingwind** [thebaselab/codeapp#197]
Here’s what I did: 
git clone a private repo(source control) -> edit some files -> git commit(source control) -> git fetch(source control)

then I tried to use git pull & git push in command line, but it didn’t work, with blank output.

Also, ping doesn’t work either.
![8F472D99-C338-44FE-9D59-5DDBF4C3DD5A](https://user-images.githubusercontent.com/33902321/125884677-89c16bb2-3838-4f3c-b8e4-963ff927654e.png)

Allowing users to edit /etc/hosts may help with this problem

**Comment by bummoblizard** [comment]
Thank you for opening an issue. Git cli is currently an experimental port, many features like clone, push and pull don't work yet. Please use the GUI instead.

For the ping issue, I'm not sure what's happening. But the connection should be fine since you are able to clone the repository from GitHub.

**Comment by windingwind** [comment]
> Thank you for opening an issue. Git cli is currently an experimental port, many features like clone, push and pull don't work yet. Please use the GUI instead.
> 
> For the ping issue, I'm not sure what's happening. But the connection should be fine since you are able to clone the repository from GitHub. I believe editing etc/hosts would not be possible since it's unavailable on iOS.

Thanks! Right now I can only use git fetch, commit, clone with GUI. Expecting to use git clone & push soon! 

As for the ping issue, not so important though. Problems with shell in ios is unavoidable I guess. I’ll try to test ping command under different internet environments.

Thank you and everyone contributing to this project. It makes coding and bug fixing much more easier.
