### ISSUE TITLE
Is there way to use GCC or Clang compiler directly from terminal?

### ISSUE THREAD

**Issue by ohsunggyeol** [thebaselab/codeapp#199]
I want to know if there's a way to use GCC compiler directly from terminal. 
ex)`gcc mainc. -o main`
`./main 10 20 30`

I need them to use command line arguments.

**Comment by bummoblizard** [comment]
You can use clang or clang++ in the terminal as you do on a desktop.

**Comment by ohsunggyeol** [comment]
> You can use clang or clang++ in the terminal as you do on a desktop.

Thank you !!! It works
