### ISSUE TITLE
Text highlighting with touchscreen 

### ISSUE THREAD

**Issue by Shanteshmani** [thebaselab/codeapp#20]
Text/code not highlighting correctly or no control options. When double tap, seems to highlight entire line but won’t copy anything.

**Comment by bummoblizard** [comment]
This is a known limitation of Monaco Editor. I'm looking for workarounds.

Currently, you'll need to use a physical keyboard, mouse or trackpad for that interaction.

**Comment by Shanteshmani** [comment]
Ok great, thanks for letting me know.
