### ISSUE TITLE
请求添加诸如scanf()函数的输入框功能

### ISSUE THREAD

**Issue by M1ragets** [thebaselab/codeapp#201]
您好，我想对于初学者来说 c语言中的scanf()函数是时常会用到的。
可能由于我的操作不当，使用该函数后，在终端中不报错，但同时也不会有输入框提示，直接结束程序。
希望未来版本添加，感谢🙏

**Comment by M1ragets** [comment]
我找到了输入框的位置 再次感谢

**Comment by FailDragon-Plus** [comment]
请问你是在哪找到的，我好像不行
![Uploading 9E56A6F8-0EE7-4A05-BC6B-BD4F46F36A6A.jpeg…]()

**Comment by FailDragon-Plus** [comment]
请问你是在哪里找到的，我好像不行
![94F46EC9-8085-4C90-8D43-DB247444845B](https://user-images.githubusercontent.com/63289359/134453863-6fc43250-8afc-4872-85b0-6619a1bc8614.jpeg)
