### ISSUE TITLE
terminal is missing characters

### ISSUE THREAD

**Issue by nohr** [thebaselab/codeapp#202]
for some reason i can only enter keys that are found in my folder name in the terminal. the same goes for what the terminal says back.

**Comment by bummoblizard** [comment]
That's really weird. Which iPadOS version are you on?

**Comment by nohr** [comment]
ipados 15 latest beta

**Comment by nohr** [comment]
![9DCDD968-9476-4E24-BB5C-0AEDD489368A](https://user-images.githubusercontent.com/10060073/126093084-569af127-366f-406e-910f-fc81227969b7.jpeg)

**Comment by bummoblizard** [comment]
Thanks for the additional information. I can confirm that it presents on iPadOS 15 beta 3.

**Comment by bummoblizard** [comment]
Looks like [xterm.js](https://xtermjs.org) is broken on beta 3's WKWebView.

**Comment by ryangurn** [comment]
this issue is occurring for me, when will the next update to the app store app be? I was also wondering if this application has a testflight so that I can submit bug reports for a “beta” version of the app?

**Comment by bummoblizard** [comment]
> this issue is occurring for me, when will the next update to the app store app be? I was also wondering if this application has a testflight so that I can submit bug reports for a “beta” version of the app?
> 
> 
> 
> I love the premise of this app and have waited a long time for something like this to show up on the iPad. 

I've added the link in README.md. The fix is still waiting for approval and not yet available though.

**Comment by Lukas-Batema** [comment]
I noticed that it has only been spaces (at least for me), after stopping the PHP server with the stop button on the terminal, with a side effect of when trying to press space, it slides up the text so it makes it not-visible, then to see it, you have to scroll it back down, but it never inputted the character.
