### ISSUE TITLE
SQLite Remote Support (July 2021)

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#203]
Since we now have PHP remote support, I only think it would be right and worthwhile, if we also add SQLite remote support as well, so it can be used in conjunction with each other :)

**Comment by bummoblizard** [comment]
Afaik SQLite is not built for remote access and it's a built-in feature inside the current php build already.

I'm also not sure what you mean by remote php. To clarify, php runs locally on the app now.

**Comment by Lukas-Batema** [comment]
> Afaik SQLite is not built for remote access and it's a built-in feature inside the current php build already.
> 
> I'm also not sure what you mean by remote php. To clarify, php runs locally on the app now.

I meant local, my bad :)

**Comment by bummoblizard** [comment]
Ah I see. It's supported as a compiled module already. You can verify this by running `php -m`.

**Comment by Lukas-Batema** [comment]
> Ah I see. It's supported as a compiled module already. You can verify this by running `php -m`.

ohhhhhhhh ok, thanks!

**Comment by Lukas-Batema** [comment]
Is there a possibility to use PostgresSQL with `php -m`?
