### ISSUE TITLE
Sidebar UI Error

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#208]
This occurs on iOS 15 Public Beta 1, on this apps version 1.2.5, while having either the Welcome page or only a single file open on the iPhone sidebar UI.![image](https://user-images.githubusercontent.com/55695493/126899444-2f302071-8531-4d36-8da5-2b2f8440e270.png)

**Comment by bummoblizard** [comment]
Fixed in the latest build. Waiting for Apple's approval.
