### ISSUE TITLE
Python - pip install unrecognised 

### ISSUE THREAD

**Issue by Shanteshmani** [thebaselab/codeapp#21]
Can we install packages? 

![D98614A8-2EE4-49F9-B37D-E27917EA7CA7](https://user-images.githubusercontent.com/37173648/105517539-e9570e80-5d22-11eb-82eb-14bf30435dee.jpeg)

![B46672E6-EF91-4A77-8C9B-D4C06CFAF830](https://user-images.githubusercontent.com/37173648/105517554-ed832c00-5d22-11eb-8051-37c6c13f8f01.jpeg)

**Comment by Shanteshmani** [comment]
Is there a special package handler for this?

**Comment by bummoblizard** [comment]
Hello. I am looking to add local Python interpreter support in the coming version with pip support.

**Comment by Shanteshmani** [comment]
Ok great, that’s awesome! 
that will make the app/ide quite powerful
Not sure about iOS and it’s ability to handle it though.

**Comment by Lukas-Batema** [comment]
I would also recommend adding other installing commands for languages that support it as well.

**Comment by Rishi5813** [comment]
There is a Work around for that too, you can import os and then install packages from the same server on which you are running the code.

import os 

os.system(“pip3 install pyttsx3”)

**Comment by bummoblizard** [comment]
Thanks for sharing this!

> There is a Work around for that too, you can import os and then install packages from the same server on which you are running the code.
> 
> import os
> 
> os.system(“pip3 install pyttsx3”)

**Comment by Rishi5813** [comment]
Your Welcome

**Comment by Rishi5813** [comment]
This Small Code Cn fulfill all the Terminal needs:-

import os 
while True:
    command = input("Your Terminal ~$ ")
    os.system(command)

**Comment by Rishi5813** [comment]
This is a python code so you can save this as Terminal.py and execute when needed.

**Comment by Shanteshmani** [comment]
> There is a Work around for that too, you can import os and then install packages from the same server on which you are running the code.
> 
> import os
> 
> os.system(“pip3 install pyttsx3”)

I like the creative thinking! Thanks mate!
