### ISSUE TITLE
App Crash Instantly (1.2.6 TestFlight)

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#214]
I can not even open the app with the most recent build on TestFlight installed on iOS15 Public Beta Build 4. If I do somehow get into the app, when I tap the directory that I want (or any of them), it crashes then after that. 
___
**EDIT:** *After it crashes and the crash notification comes up, I click Share, and it just closes the prompt, then proceeds to do nothing (a.k.a. open the crash sharing screen).*

**Comment by bummoblizard** [comment]
It sounds an TestFlight specific problem. Try to reinstall the app and reboot the device.

**Comment by Lukas-Batema** [comment]
It seems to have stopped crashing. I will try re-installing though, really quick.
