### ISSUE TITLE
When the ‘run’ in python is clicked, it only returns ‘python’

### ISSUE THREAD

**Issue by mahynotch** [thebaselab/codeapp#217]
I’m now using ipad pro 2021 with ios 14.7.1. Before I added a ‘while’ in one of my codes, it worked just fine. However , now regardless of the content of my code, it only returns a ‘python’ in terminal. I’ve clear the settings for several times, but nothing changes. Even the standard print(‘Hallo World’) goes wrong. I wonder why.
![C42C753B-2252-4884-993D-50A77ADC2ECA](https://user-images.githubusercontent.com/27921780/128587625-597f426a-00e3-4d34-9236-c937481c2235.png)

**Comment by bummoblizard** [comment]
Can you try to run the script manually by typing `python default(2).py` in the terminal?

**Comment by bummoblizard** [comment]
Also try the TestFlight version: https://testflight.apple.com/join/EgZ8sE2P
