### ISSUE TITLE
External libraries (Maven) in Java

### ISSUE THREAD

**Issue by dan1109** [thebaselab/codeapp#219]
how do you add a maven library in a java project?  For example org.telegram.telegrambots.
I have already the pom.xml

**Comment by bummoblizard** [comment]
Local OpenJDK needs to be implemented first. #101

Meanwhile, you can code telegram bots using Python or Node.js.

**Comment by bummoblizard** [comment]
Local OpenJDK added in https://github.com/thebaselab/codeapp/commit/39155744844ad472f0b79c714230a8691a7832bb.

**Comment by jri** [comment]
How can I actually run Maven in Code App?
Maven is pure Java, so it should run. But it is launched by `mvn` shell script (beginning with`#!/bin/sh`).
Can I run shell scripts in Code App?
`echo $SHELL` shows `/bin/sh` so it seems a bourne shell is running in the Terminal.
