### ISSUE TITLE
终端字符显示不出

### ISSUE THREAD

**Issue by DoingDog** [thebaselab/codeapp#220]
![EF36DD2B-CBD7-485D-BF84-7D974FD6716B](https://user-images.githubusercontent.com/72430078/129209044-80e4b748-191e-474e-89a1-29397dbb5837.png)
ipadpro2021，终端缺字
图中为输入“git push”后的显示

**Comment by bummoblizard** [comment]
Fixed in the TestFlight version: https://testflight.apple.com/join/EgZ8sE2P
Duplicate (#202)
