### ISSUE TITLE
终端窗口出现字符不可见

### ISSUE THREAD

**Issue by gongcf** [thebaselab/codeapp#223]
终端里只能显示部分字符
![73F84C91-89CF-4C18-9E06-455A16448F6D](https://user-images.githubusercontent.com/10266465/129559802-3a0465be-33c7-43b5-a920-3a8064a6063d.jpeg)

**Comment by Carmelo-02** [comment]
Same issue. I have installed the iOS 15 beta, I don't know if it depends on this.

**Comment by bummoblizard** [comment]
https://testflight.apple.com/join/EgZ8sE2P
