### ISSUE TITLE
Terminal showing cluttered characters

### ISSUE THREAD

**Issue by SevenAndrew** [thebaselab/codeapp#225]
![image](https://user-images.githubusercontent.com/82178604/130333899-0c68377d-4690-4ead-91b3-9c16f3e52171.png)

Testing around with VS Code, very often terminal/output looks like this...

**Comment by t4r7k** [comment]
Yes, unfortunately I have the same issue. I just bought the app and I really loved it but I hope they fix this problem.

**Comment by bummoblizard** [comment]
Please download the beta version: https://testflight.apple.com/join/EgZ8sE2P

It's a iOS 15 specific issue.

**Comment by SevenAndrew** [comment]
> Please download the beta version: https://testflight.apple.com/join/EgZ8sE2P
> 
> It's an iOS 15 specific issue.

Thank you very much! Didn't know! Problem solved!

**Comment by bummoblizard** [comment]
Update released on the App Store.
