### ISSUE TITLE
Import module not working

### ISSUE THREAD

**Issue by JacquieK1k** [thebaselab/codeapp#232]
![image](https://user-images.githubusercontent.com/63683194/131177744-997c018f-1a16-4341-93dc-c0bfe0e4a366.jpeg)

Hi! I am a coding student learning python and I can't seem to import random or any other modules/libraries into the app even though it seems possible according to the other posts. 

I don't know what I am doing wrong and would appreciate if someone can tell me how to import random correctly into this app. I have included a screenshot of what currently happens every time I try importing the random module.

**Comment by bummoblizard** [comment]
There's mistake on your import statements. It should be `import random` only.

![image](https://user-images.githubusercontent.com/38398443/131760940-782719f5-6354-4381-a908-1f2841966952.png)
