### ISSUE TITLE
iPad Magic Keyboard shortcut

### ISSUE THREAD

**Issue by QuantumABI** [thebaselab/codeapp#237]
OS: iPadOS 14.7.1
Keyboard: Apple Magic Keyboard for iPad Pro
Code app version: v1.2.5 Build 30

I can't seem to make the [ ] brackets using the shortcut "Option + 8"  and "Option + 9". I have the language set to "Norwegian", it works outside the app otherwise. Changing the language did not seem fix it for me.

Also dragging and dropping files into another folder in the app itself doesn't seem to work?

Kind regards.

**Comment by sylvoie** [comment]
Hello,

OS: iPadOS 15.2.1
Keyboard: Apple Magic Keyboard for iPad Pro
Code app version: v1.2.7 Build 39
Keyboard layout : French Canadien

I have the same problem, I can’t seem to make those characters :
{ key option+7
} key option+8
[ key option+9
] key option+0

There is the layout of my keyboard
![image](https://user-images.githubusercontent.com/3700343/149867509-6af0dfda-81d6-4e02-83ae-ddbdff0de3a5.png)


Thank’s

**Comment by bummoblizard** [comment]
Thank you for your report. This is related to https://github.com/microsoft/monaco-editor/issues/1233 and I should be able to come up with a native fix.

**Comment by sylvoie** [comment]
Hello,

I confirm that my keyboard works fine on Monaco-Editor. I’m not able to reproduce the problem on that site.

Thank you very much for this wonderful application.  It's my favorite development app. Do you plan to support Python-Django?.

Thank’s

**Comment by bummoblizard** [comment]
> 

Django should be supported and can be run by `python manage.py runserver --noreload`.

**Comment by sylvoie** [comment]
Thank you,

With the option —noreload, that’s mean, if you change your code, you need to manually restart the server.

**Comment by bummoblizard** [comment]
Hi all. I've just released an update (1.2.9). Please see if the updated version solve this problem.

Thanks,
Ken

**Comment by sylvoie** [comment]
Hello,

Thank you, I confirm that your fix correct the problem from my side. That character {}[] can be done by my Apple Magic Keyboard. Very good support.

You correct the problem for North America (Canada-Québec) not just for European.

Can you correct the issue #334? It’s really annoying when editing code.

Thank’s again and food work!

**Comment by bummoblizard** [comment]
> Hello,
> 
> 
> 
> Thank you, I confirm that your fix correct the problem from my side. That character {}[] can be done by my Apple Magic Keyboard. Very good support.
> 
> 
> 
> You correct the problem for North America (Canada-Québec) not just for European.
> 
> 
> 
> Can you correct the issue #334? It’s really annoying when editing code.
> 
> 
> 
> Thank’s again and food work!
> 
> 

I am working on it.
