### ISSUE TITLE
Second print broken on Ipad Pro

### ISSUE THREAD

**Issue by lucas-emartinez** [thebaselab/codeapp#239]

**Comment by lucas-emartinez** [comment]
![3D0619A8-F330-4F4E-8CA8-FD63AAAD2845](https://user-images.githubusercontent.com/88638100/132743296-7040fc4a-a316-4304-9750-0a907df4e2a6.png)
>

**Comment by bummoblizard** [comment]
Hey. This is fixed in the latest App Store release. Please update the app.

**Comment by lucas-emartinez** [comment]
Thank you very much!El 26 sep. 2021 13:40, Ken Chung ***@***.***> escribió:
Hey. This is fixed in the latest App Store release. Please update the app.
