### ISSUE TITLE
Can’t detect modified files

### ISSUE THREAD

**Issue by MalachiteN** [thebaselab/codeapp#24]
I modified a file in my local repo, but *Code* can’t detect it, and refused to commit.

The modified file is a GitHub Actions file, which is located in a hidden folder \/.github\/workflows\/CI.yml.

**Comment by MalachiteN** [comment]
Restarting _Code_ is useful. It detected the files after restarting. However, I think it is a bug, because it can’t act immediately.

**Comment by bummoblizard** [comment]
Hello. In that case, you can also tap the refresh button at the bottom of explorer. It will reload the directory as well as the Git status.

Nevertheless, Git support should be drastically improved in the coming update including faster cloning, branching and detached head mode.
