### ISSUE TITLE
Private Repos on Github

### ISSUE THREAD

**Issue by MaxDusdal** [thebaselab/codeapp#241]
When trying to import a private Repo from GitHub it throws the error: „Clone error: remote credential provider returned an invalid cred type“.

**Comment by bummoblizard** [comment]
You'll need to enter your GitHub credentials in the settings menu. Note that you'll need to use a personal access token instead of the regular password. See https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by Jakubpoland** [comment]
I've set it up like in that link but there is stull isue with cloning

**Comment by bummoblizard** [comment]
What error are you seeing? Make sure you have given the access token the sufficient permission. (Repo access)
