### ISSUE TITLE
真的一言难尽

### ISSUE THREAD

**Issue by corgile** [thebaselab/codeapp#242]
![7EF0F55E-8A95-4909-8D94-19E8DFA42885](https://user-images.githubusercontent.com/48396880/133895505-cc2089d6-3a6f-4fca-9b08-bca84b898a56.png)

![C1C42595-C8DB-4E5C-B13F-679E48387769](https://user-images.githubusercontent.com/48396880/133895511-49db05a1-0dda-43fb-bdd2-d12422144682.png)

**Comment by corgile** [comment]
@bummoblizard

**Comment by bummoblizard** [comment]
这里有两个问题，第一：粘贴时的缩进问题￼￼
这个确实存在￼，这个星期内会推出更新￼￼解决

第二个是￼clang的编译问题：受￼iOS所限，clang￼ target是web assembly，￼暂时wasm并不支持exceptions（https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md)，因此有try-catch, throw等的代码无法连行。

**Comment by corgile** [comment]
> 因此有try-catch, throw等的代码无法连行，这个只能够等LLVM推出更新￼￼解决。￼

代码没有try catch ， throw
