### ISSUE TITLE
Custom class name for Java compiler

### ISSUE THREAD

**Issue by carrotPeanutButter** [thebaselab/codeapp#243]
No matter what name i used. It will always say the file name is not the same as the public class name. Hope to be fixed soon.  
>_<

**Comment by carrotPeanutButter** [comment]
![ED14E119-BF57-4321-83D2-24ACAE285207](https://user-images.githubusercontent.com/90177205/133964526-45abb949-c92e-494c-bd39-9cf80f7c354d.jpeg)

**Comment by bummoblizard** [comment]
For now, the main class name has to be Main. I'm working on a solution.

**Comment by carrotPeanutButter** [comment]
copy that

**Comment by carrotPeanutButter** [comment]
copy that maybe u can add some tips to explain this problem when user is trying to compile a java source file👐

**Comment by 2049027389** [comment]
我也一样，怎么还不解决在如此长的时间内
