### ISSUE TITLE
Features  & bugs

### ISSUE THREAD

**Issue by DaiYuAng** [thebaselab/codeapp#244]
1. I want to run git pull from my private git server  but i can't .Even i configure my private git server auth
2. Please add remote workspace (vs code remote)
3. codeapp crashed when i using git or terminal
4. There is nothing in terminal when i open terminal(I can see a few character in termianl)

**Comment by bummoblizard** [comment]
1: Git in cli is an experimental port, many features don't work. You'll need to use the GUI to run git pull.
2: FTP / SSH access is something I'm working on
3. Resolved in the latest release, please update from the App Store
4. See (3)

**Comment by DaiYuAng** [comment]
Alright thanks for your answer
One more thing , why don't make a Linux virtual container in code app , just like Alpine in ish.

**Comment by bummoblizard** [comment]
That's a great suggestion! The main concern is performance. For example, a hello world Python script might take a few seconds to run in iSH. I will definitely be experimenting with integrating iSH in the future.

**Comment by DaiYuAng** [comment]
Thanks for your answer
codeapp will be a great code editor on ipad
I wating for that day
