### ISSUE TITLE
无法编译运行C语言scanf函数

### ISSUE THREAD

**Issue by FailDragon-Plus** [thebaselab/codeapp#246]
请教一下，Code App要怎么样才能运行scanf函数。
在Code App中，使用本地编译器C(Clang 13.0.0)，编译scanf会卡住没反应，在终端输入什么内容回车都不会有反应。

![C062A9E9-DD92-4943-A548-2A5FDE3AB6DF](https://user-images.githubusercontent.com/63289359/134385139-a7698db8-8205-4f59-a44e-e399f7ab9e77.jpeg)

在VS Code上也会出现类似情况，但可以通过修改扩展的 Code-runner:Run In Termial 设置来解决。

![0C273045-31FD-41EA-9351-AA9FC2E635CD](https://user-images.githubusercontent.com/63289359/134385998-4bc86608-a7ef-4126-857b-ab6424cc411e.png)

但是在Code App里好像没有看到相关的指令和设置

**Comment by bummoblizard** [comment]
scanf應該能夠使用的￼，試在printf後加入￼fflush(stdout)![image](https://user-images.githubusercontent.com/38398443/134455333-733e7290-8fde-4da9-be3b-5ebe3643e383.png)

**Comment by FailDragon-Plus** [comment]
感谢，添加 `fflush(stdout);` 以后就可以了，另外有篇文章说的添加 `setvbuf(stdout, NULL, _IONBF, 0);` 也可以：https://blog.csdn.net/AnimateX/article/details/82955294

**Comment by tangbaker** [comment]
#请问一下，我添加了fflush(stdout)，为什么还是不可以使用scanf

**Comment by FailDragon-Plus** [comment]
试试添加 `setvbuf(stdout, NULL, _IONBF, 0);`
