### ISSUE TITLE
希望支持C++多文件编译

### ISSUE THREAD

**Issue by lifeWithBug** [thebaselab/codeapp#248]
例如我在GradeBook.h中声明了GradeBook类的成员函数，在GradeBook.cpp中定义了Book类的成员函数，在main.cpp中（含main函数）运行时发生报错：
/usr/bin/ld: /tmp/CCRGiKu0.0: in function 'main':
main.cpp: (.text+0x413): undefined reference to
'GradeBook::GradeBook(std::
_cxx11: :basic_string<char, std:: char_traits<char>,
std: : allocator<char> > const&, std: :array<int, 10ul> const&)
collect2: error: ld returned 1 exit status

希望得到解决😁

**Comment by bummoblizard** [comment]
这个情况你可以使用内置的clang命令，具体如下：
clang++ GradeBook.cpp
clang++ main.cpp
clang++ GradeBook.o main.o
./a.out

**Comment by lifeWithBug** [comment]
命令应该没问题，但是其实终端还有部分字符不会显示的bug。😂

发自我的iPad

> 在 2021年9月23日，下午2:11，Ken Chung ***@***.***> 写道：
> 
> ﻿
> 这个情况你可以使用内置的clang命令，具体如下： 
> clang++ GradeBook.cpp 
> clang++ main.cpp 
> clang++ GradeBook.o main.o 
> ./a.out 
>

**Comment by bummoblizard** [comment]
这个要到App Store更新 :)

**Comment by lifeWithBug** [comment]
好像还是不行。。。


发自我的iPad

> 在 2021年9月23日，下午2:23，Ken Chung ***@***.***> 写道：
> 
> ﻿
> 这个要到App Store更新 :)
>

**Comment by bummoblizard** [comment]
可以留下截图￼吗？

**Comment by lifeWithBug** [comment]
很多命令行我都试过了


发自我的iPad

**Comment by lifeWithBug** [comment]
﻿
很多命令行我都试过了


发自我的iPad

**Comment by lifeWithBug** [comment]
![EF02778A-23F7-4E8A-AEDF-C44140BF9784](https://user-images.githubusercontent.com/51158970/134541744-fdbd9189-c595-4e61-9b35-2c22c2a2f9fc.jpeg)
之前我是用邮箱发的，不知道为什么没有图片显示。。。

**Comment by bummoblizard** [comment]
Code App 的 C++ 暂不支持exception，请移除try、catch、throw等关键字。

**Comment by bummoblizard** [comment]
使用“clang++ main.cpp -fno-exceptions”编译代码。然后，您可以使用“./a.out”运行程序。
