### ISSUE TITLE
希望命令行中增加clear指令

### ISSUE THREAD

**Issue by Veloma-Timer** [thebaselab/codeapp#250]
![image](https://user-images.githubusercontent.com/49268882/134808514-b8ec33e5-4b0f-4965-8c66-6101a5f77f79.png)

**Comment by bummoblizard** [comment]
好的， 目前你可以使用 Cmd-K 或按垃圾桶按钮。

**Comment by Veloma-Timer** [comment]
好的，谢谢，希望软件越来越好。
