### ISSUE TITLE
Terminal got stucked after running ssh-keygen

### ISSUE THREAD

**Issue by yeongrokgim** [thebaselab/codeapp#257]
Hi,

I just started to use Code App on iPad Pro 11 (2nd gen), iPad OS 15 Beta (19A346)

As I always do, I want to use per-device ssh key to connect remote server, thus I run `ssh-keygen`.
But after this command, I cannot type anything on terminal.

I also tried to debug this: running `ssh-keygen -t ed25519 -f id_ed25519`, then app asked me passphrase.
Maybe the bug is happen because without specifying target output file, the app wrongly handle terminal input, I suspect.

**Comment by m8458246** [comment]
> Thanks for reporting the bug. I'll look into this. It probably has something to do with interactive inputs.

I wait long time for it. Nothing happened. It's stuck.

**Comment by bummoblizard** [comment]
This is fixed some time ago.
