### ISSUE TITLE
Hope C++ can support #include <bits/stdc++.h>

### ISSUE THREAD

**Issue by andyli0123** [thebaselab/codeapp#261]
Hope C++ can support #include <bits/stdc++.h>

**Comment by lampardnk** [comment]
Agree, this is an extremely useful and common libraries for competitive coders

**Comment by bummoblizard** [comment]
bits/stdc++.h is a non-standard header file and therefore not included in the clang compiler. You should include individual headers manually.
```
Unfortunately, this is a lazy hack, naming a GCC internal header directly instead of individual standard headers like <string>, <iostream> and <vector>. It ruins portability and fosters terrible habits.
```
From https://stackoverflow.com/questions/31816095/why-should-i-not-include-bits-stdc-h

If you really need this header, you can follow guide here (https://stackoverflow.com/questions/28994148/how-can-i-include-bits-stdc-in-xcode) to create your own header file.

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/commit/b56a76ec58bd9688227676b17fdbb89550723648
