### ISSUE TITLE
Repos generated in 1.1.7 sometimes are not compatible with 1.1.8

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#27]
It will not let me push my commits from local remote to my public GitHub repo. It says there are uncommitted changes, which I can see, but all it is, is a blank info symbol without text or a title, which when clicked on says something about the OID missing.

**Comment by bummoblizard** [comment]
Hi. I'm sorry for the problem you are having.

What changes have you made to the repo? Is there any reproducible steps that I can follow?

**Comment by Lukas-Batema** [comment]
> Hi. I'm sorry for the problem you are having.
> 
> What changes have you made to the repo? Is there any reproducible steps that I can follow?

I have made changes to update my help function in my python program, but I had changes before the update happened, so that may be the issue, because it still shows a 1 by the sidebar in the remote section, but it shows the info symbol only. I really didn’t do anything but do a minor edit and push changes, but it won’t let me fully commit them. Thanks!

**Comment by bummoblizard** [comment]
Yes. Screenshots would be appreciated! What do you mean by you had changes before? Were they staged? 

While we're figuring this out, I suggest having the edited file saved somewhere and clone the repo again. Again, sorry for the problem caused :(

**Comment by Lukas-Batema** [comment]
> Yes. Screenshots would be appreciated! What do you mean by you had changes before? Were they staged?
> 
> While we're figuring this out, I suggest having the edited file saved somewhere and clone the repo again.

Yes, they were staged, but became unstated when the most recent update came out. I had been editing the file before the update happened. Here are some images.

![A91D95C5-AA95-42F4-B4F7-8DA200FA4EC7](https://user-images.githubusercontent.com/55695493/107521755-ef514a00-6b80-11eb-80b7-ebdb1d18df8e.png)
![AFE83C0F-B8EF-4DD4-9B57-AB65FC445E1A](https://user-images.githubusercontent.com/55695493/107521760-f11b0d80-6b80-11eb-869f-92ada62c8035.png)
![C32977F2-7CAF-4FBC-829E-42C8451C0AB4](https://user-images.githubusercontent.com/55695493/107521762-f11b0d80-6b80-11eb-92bf-4877b5006a1d.png)

**Comment by Lukas-Batema** [comment]
Also, sometimes the errors and related are halfway off the screen on iOS (iPhones). I am not sure about iPadOS, (iPads).

**Comment by Lukas-Batema** [comment]
After recloning the repo, it did go through,  it there is still a bug with people who had changes active between updates, so I would recommend keeping this issue open until this is fixed. Thanks for the help ;)

**Comment by bummoblizard** [comment]
Got it. Keeping this open. I suspect there could be some incompatibles with Git between the old and the new version.

Regarding the sizing problem, I can confirm they only appear on iPhones. Frankly, the app interface isn't really optimised for iPhone right now. I agree this should be fixed. Also see #6

**Comment by Lukas-Batema** [comment]
> Got it. Keeping this open. I suspect there could be some incompatibles with Git between the old and the new version.
> 
> Regarding the sizing problem, I can confirm they only appear on iPhones. Frankly, the app interface isn't really optimised for iPhone right now. I agree this should be fixed. Also see #6

Okay, thanks. I didn’t see that issue, my bad. I thought that would be good to mention here, as it shows up somewhat in the images I just sent. Thanks again!

**Comment by bummoblizard** [comment]
Resolved in 1.2.1

**Comment by Lukas-Batema** [comment]
Thank you!
