### ISSUE TITLE
远程运行导包问题 (Porting Go to iOS)

### ISSUE THREAD

**Issue by m8458246** [thebaselab/codeapp#277]
我学习的是Golang，只能远程运行代码，单个文件运行时没有问题，但是我想要导入本地包时，无论使用什么样的方法都没法成功，这个有办法解决吗？还有python的Django问题，无法使用python manage.py runserver运行，提示权限问题。
我的版本：App Store最新版
我的设备：iPad pro2021 12.9寸

**Comment by bummoblizard** [comment]
显然，Django在运行开发服务器时会启动子进程。iOS 不支持此功能。
`Python manage.py --no-reload`可以。

对于远程执行，由于远程执行的性质，它不会导入本地包。不过，将Go编译器移植到iOS并非不可能。
