### ISSUE TITLE
ssh remote

### ISSUE THREAD

**Issue by lwqisme** [thebaselab/codeapp#278]
什么时候能实现类似vscode的ssh打开远程文件夹功能呢？今天买了app，发现用密钥连接远程服务器都很困难。

**Comment by socialmedialabs** [comment]
How do you even open a file from SSH? I can connect to the server via SSH but my id_rsa key which I stored in the local Code App directory seems to be ignored. Setting a password for connection via SSH did sometimes work and sometimes simply wouldn't.

And even if I'm connected via SSH, how do I open a file for editing?
`code example.php`
That doesn't work. I have the feeling that Code App has huge functionality but the largest part is hidden or undocumented. It would be really nice to have the possibility to add even folders via SSH as a project.

**Comment by bummoblizard** [comment]
Hi. You cannot open a file via SSH at the moment. `ssh` is only a cli-only command bundled in the terminal.

**Comment by socialmedialabs** [comment]
> Hi. You cannot open a file via SSH at the moment. `ssh` is only a cli-only command bundled in the terminal.

Thank you for your answer. Will this be available somewhere in the future?

**Apart of all of this I want to tell you that I really love Code App. I'ts something I really wished for iPad. Thank you, bro.**

**Comment by bummoblizard** [comment]
This feature is now implemented.
