### ISSUE TITLE
本地编译时，如果使用C++中的STL容器并且对其进行操作，则代码无法正常运行

### ISSUE THREAD

**Issue by snewptl** [thebaselab/codeapp#279]
当添加`#include<vector>`，并且定义一个容器`vector<int>vec`后，这时候运行代码是不会报错的。
但是如果对这个容器进行`vec.push_back(x)`操作时，会产生以下错误：
wasm-ld:  undefined symbol:  __cxa_allocate_exception
wasm-ld:  undefined symbol: __cxa_throw

![41876462-71DF-4A13-92D0-8E5892B5E2C4](https://user-images.githubusercontent.com/52316601/139393325-3afa141c-9800-49c7-bad9-ecaea032ad6e.jpeg)

**Comment by bummoblizard** [comment]
Duplicate (#268)
