### ISSUE TITLE
Text Navigation

### ISSUE THREAD

**Issue by vlad-cool** [thebaselab/codeapp#280]
Navigation with two fingers on keyboard doesn’t work

**Comment by bummoblizard** [comment]
Unless we make a transition to using native editor, or something like CodeMirror 6, this won't happen. But it's definitely not non-trivial therefore I will keep this issue open.

**Comment by bummoblizard** [comment]
Native text selection is now supported through Runestone editor. See https://github.com/thebaselab/codeapp/issues/169#issuecomment-2162955555.
