### ISSUE TITLE
ipad mini 6 无法打开文件夹

### ISSUE THREAD

**Issue by Ven3** [thebaselab/codeapp#284]
切换文件夹app会卡死，重启后又回到之前的位置了，另外，在隐私设置里，文件与文件夹这个选项里面没有CodeApp的授权选项

**Comment by bummoblizard** [comment]
你能试着重新启动设备吗？

**Comment by Ven3** [comment]
> 你能试着重新启动设备吗？

重启设备问题解决了，多谢了，不过之前我也重启过，能切换文件夹，后来不知道怎么回事，又不能切换了。

**Comment by bummoblizard** [comment]
这个应该是iPadOS的bug，如果更新iPadOS后仍有问题请重新开启这个问题。
