### ISSUE TITLE
Git pull command does not work

### ISSUE THREAD

**Issue by RichardBrowning** [thebaselab/codeapp#294]
I tried running _**git pull**_ in Command Line yet it does not work, by stuck when I hit enter, without any output. The only way to break out of it is by Ctrl+C.

Am I running a invalid command or is there another proved way to pull from the repo? I just cannot get my repo updated.

In the attachment is my git config
> [core]
>	bare = false
>	repositoryformatversion = 0
>	filemode = true
>	precomposeunicode = true
>	logallrefupdates = true
>[remote "origin"]
>	url = https://hub.fastgit.org/RichardBrowning/N341-Client-Side-Web-Programming.git
>	fetch = +refs/heads/*:refs/remotes/origin/*
>[branch "main"]
>	remote = origin
>	merge = refs/heads/main

求帮助🙏 三克油 very much

**Comment by bummoblizard** [comment]
Network requests with git cli isn't supported yet. You'll need to use the GUI for it. In the source control tab, press the menu button and select git fetch. Then check out to the latest commit by holding and selecting the 'main'  icon  located in the left lower corner.

**Comment by RichardBrowning** [comment]
Thank you for the reply. It works brilliantly.
![IMG_0014](https://user-images.githubusercontent.com/46521212/143664670-c161341b-9aa7-441e-b8aa-4f8be677803d.jpeg)
?
![A3D72CC8-7545-4A50-98CC-6A0D80578FE8](https://user-images.githubusercontent.com/46521212/143664805-5a912c5f-00c6-416c-9292-4a97ee6eed60.jpeg)
