### ISSUE TITLE
Java Scanner Issue

### ISSUE THREAD

**Issue by walshg3** [thebaselab/codeapp#297]
Recently found this project and I like the work being done a lot. I tried looking to see if others have had this issue but no luck. I have a program that uses Java’s Scanner class to collect user input when I run the program on the remote server i get this error 

![CEF88B23-AA53-454C-8C94-419B592393AF](https://user-images.githubusercontent.com/26581084/143494471-7895544f-9277-42df-8156-20e320416f09.jpeg)

It seems the remote server can not collect user input unless I’m mistaken? I understand Java is being worked on to run locally and this issue is not that big of a deal I am just curious if others have found a way around the problem. 

Thanks

**Comment by bummoblizard** [comment]
The remote execution feature doesn't support interactive user input. Any use input should be typed in the INPUT tab before submitted for execution.
