### ISSUE TITLE
Cannot use spacebar on Magic keyboard while in terminal

### ISSUE THREAD

**Issue by benoluwa** [thebaselab/codeapp#299]
When trying to run commands in the terminal or even just write scripts while using a Bluetooth keyboard, the Spacebar tabs over instead of spacing.

**Comment by bummoblizard** [comment]
Thanks for reaching out. I can't seem to reproduce the problem though. It would be helpful if you can provide more specific information of your setup. For example:
- What's your iPadOS version?
- Which input method are you using
- Which keyboard layout does your keyboard have

**Comment by benoluwa** [comment]
I've actually got it figured out. 
Had to turn off Full Keyboard Access in accessibility. It was creating extra functions for things like the spacebar and other keys.

Thanks

BenOluwa

**Comment by Lukas-Batema** [comment]
> I've actually got it figured out. 
> Had to turn off Full Keyboard Access in accessibility. It was creating extra functions for things like the spacebar and other keys.
> 
> Thanks
> 
> BenOluwa

It does this with a wired keyboard too, not necessarily an Apple keyboard.
