### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#30]
The most recent Python compiler is at version 3.7.7, while the most recent public version available for download online is Python 3.9.0

**Comment by bummoblizard** [comment]
It will be updated in the next release, alongside a local 3.9.0 interpreter.

**Comment by Lukas-Batema** [comment]
> It will be updated in the next release, alongside a local 3.9.0 interpreter.

Ah, okay, I understand, may I close the issue then?

**Comment by bummoblizard** [comment]
I’ll keep it open to remind myself 😃

**Comment by Lukas-Batema** [comment]
Okay, thanks :)

**Comment by bummoblizard** [comment]
Resolved in 1.2.1

**Comment by Lukas-Batema** [comment]
Thank you!
