### ISSUE TITLE
Git issue templates not found

### ISSUE THREAD

**Issue by Mister-Hope** [thebaselab/codeapp#304]
已经尝试重新安装过 Code App，已尝试重置设置

![image](https://user-images.githubusercontent.com/33315834/144532499-746a86dc-9638-4779-aebf-e519c4e562c9.png)

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/discussions/286#discussioncomment-1745021

**Comment by Mister-Hope** [comment]
你有看过图么，我已经在设置中设置了凭证并点击了完成，之后我再次提交仍然是凭证缺失的样子。。。。

**Comment by Mister-Hope** [comment]
补充：我提这个issue的时候我也是已经设置好了凭据。

我确定我输入了正确的GitHub账户名和密码，但我确实没有输入pat。我本身GitHub账户是有2fa的，因为文档的缺失这里我现在也并不确定我是否可以直接提供密码？还是说我只能设置一个pat？

**Comment by bummoblizard** [comment]
如果你用左手边的gui 进行clone可以吗。

**Comment by Mister-Hope** [comment]
天亮了试试，今天太晚了😂

**Comment by Mister-Hope** [comment]
小仓库侥幸成功了几个，Github上稍微大一点的仓库尝试了很多次都是不成功的样子....
