### ISSUE TITLE
身份信息配置无效

### ISSUE THREAD

**Issue by Mister-Hope** [thebaselab/codeapp#305]
![image](https://user-images.githubusercontent.com/33315834/144534430-45dceb15-e75c-471d-883d-7d6adf091dc7.png)![image](https://user-images.githubusercontent.com/33315834/144534445-72614fd9-d2d0-43b3-ba21-4c9aa3c0a9d4.png)

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/discussions/286

**Comment by Mister-Hope** [comment]
Emm，你还是并没有解释我问题，我如图所示我已经通过gui设置了名称和邮箱，那原则上我本地创建仓库并进行commit应该不会弹出相关错误才对。

**Comment by bummoblizard** [comment]
Gui 和 cli 的git是互不关连的，请使用gui进行commit, clone 等。

**Comment by Mister-Hope** [comment]
啊你这么说我就懂了。。。。
