### ISSUE TITLE
Cannot use file <bits/stdc++.h>

### ISSUE THREAD

**Issue by ko04** [thebaselab/codeapp#307]
#261 I have face the same question that this issue have already propose, hope c++ can support <bits/stock++.h>

**Comment by bummoblizard** [comment]
bits/stdc++.h is a non-standard header file and therefore not included in the clang compiler. You should include individual headers manually.
```
Unfortunately, this is a lazy hack, naming a GCC internal header directly instead of individual standard headers like <string>, <iostream> and <vector>. It ruins portability and fosters terrible habits.
```
From https://stackoverflow.com/questions/31816095/why-should-i-not-include-bits-stdc-h
