### ISSUE TITLE
PHP not executing when using "preview in browser".

### ISSUE THREAD

**Issue by Gandalf1783** [thebaselab/codeapp#309]
A simple php script that does echo "Hello"; will not execute when trying to display it in via the Preview in Browser method.

Also, if i just click the run button, it only executes it in the terminal, rather than opening the web browser.

Is this intended, or is this a bug?
I cannot tell, since the README.md says: "Local web development environment (Node + PHP) ✅", therefore I guess there has to be some way?

Thanks!

**Comment by Lukas-Batema** [comment]
You have to start a local server using the terminal. I do not remember how to do this though.

**Comment by bummoblizard** [comment]
@Lukas-Batema is right. See https://www.php.net/manual/en/features.commandline.webserver.php
Typing `php -S localhost:8000` in the terminal will start a development server on port 8000. You can then access the webpage on `localhost:8000` with safari.

**Comment by C4ntor** [comment]
Currently the command `php -S localhost:8000` is not working on Code app version v1.4.3 (at least in my case, when I run the command from the terminal, it goes in a loop and it shows nothing... and consequentially the server on localhost does not start).  Also How I enable the Preview in Browser feature?
