### ISSUE TITLE
Django can’t run server

### ISSUE THREAD

**Issue by shawnljohnson1980** [thebaselab/codeapp#311]
Every time I try to run the manage.py command to run server using Django,  I get a permission error.

**Comment by bummoblizard** [comment]
Can you show me the full error message?

**Comment by shawnljohnson1980** [comment]
Sent from Yahoo Mail for iPad


On Thursday, December 9, 2021, 12:18 PM, Ken Chung ***@***.***> wrote:




Can you show me the full error message?

**Comment by bummoblizard** [comment]
> Sent from Yahoo Mail for iPad On Thursday, December 9, 2021, 12:18 PM, Ken Chung ***@***.***> wrote: Can you show me the full error message? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I can't see the message. A screenshot would be great.

**Comment by shawnljohnson1980** [comment]
Sent from Yahoo Mail for iPad


On Friday, December 10, 2021, 1:13 PM, Ken Chung ***@***.***> wrote:





Sent from Yahoo Mail for iPad On Thursday, December 9, 2021, 12:18 PM, Ken Chung @.***> wrote: Can you show me the full error message? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


I can't see the message. A screenshot would be great.

**Comment by bummoblizard** [comment]
Unfortunately I still can't see the message. Perhaps you want to post it directly on GitHub instating of replying to the email.

**Comment by shawnljohnson1980** [comment]
Yes, I'll try that. I sent a screen shot. I guess our systems don't get along. 

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 14, 2021 at 12:20 PM, Ken ***@***.***> wrote:   


Unfortunately I still can't see the message. Perhaps you want to post it directly on GitHub instating of replying to the email.
