### ISSUE TITLE
Browse first mode

### ISSUE THREAD

**Issue by idvorkin** [thebaselab/codeapp#312]
Wow great app. Amazing really!! 

often on my iPad I just want to browse the code without editing. Would it be possible to have such a thing where the on screen keyboard never comes up but go to references works and  scrolling works

**Comment by bummoblizard** [comment]
I’m glad you enjoyed it! :)

Actually there is already a read-only mode. You can enable it it the
setting menu under editor tab. Although on-screen keyboard might still show
up, the editor will not perform any edit.
