### ISSUE TITLE
Output panel font is very hard to see

### ISSUE THREAD

**Issue by lampardnk** [thebaselab/codeapp#315]
![55E566CB-0B82-4A94-8505-9E206D1C8D67](https://user-images.githubusercontent.com/28803484/146635571-47b3387f-9d71-4d4f-85ff-60c5f3aa7e9b.png)

Hi, this might be very minor issue that isn’t worth posting on github but personally I think it’s really annoying: The dark theme makes the output panel unreadable. The light theme’s output panel is very clear but it’s too bright and I prefer dark theme.

**Comment by bummoblizard** [comment]
Thanks for reaching out. This is not supposed to happen and should be a bug. Can you try to turn dark theme off and on in the app's setting menu?

**Comment by lampardnk** [comment]
I tried turning on/off the dark setting, to automatic and light and different themes and even exit the app and open again in new projects and files but still the same, if its dark mode then whichever themes will make output panel and only output panel invisible/ very hard to read font

**Comment by bummoblizard** [comment]
Got it. As I cannot reproduce this issue on my device, the last thing you could try is to reboot your device. Please provide the app version (scroll to the bottom of the settings page), iPadOS version and device model so that I can try to reproduce this issue.

**Comment by lampardnk** [comment]
Rebooting didnt help.
App ver 1.2.7 Build 39
IpadOS 14.7.1
Ipad 8th gen 10.2 inch model A2270

**Comment by bummoblizard** [comment]
Thank you! I will further investigate into this issue.

**Comment by lampardnk** [comment]
I really love the app, clean and truly vscode-like ui, thank you!

**Comment by lampardnk** [comment]
![2B27A751-4FBC-47F6-A077-514F6107F2D3](https://user-images.githubusercontent.com/28803484/146652306-0d219708-e902-426b-aae3-8198d2b3b4bb.png)

just updated to the latest ipadOS 15.2, panel looks nice now
