### ISSUE TITLE
Button mapping options

### ISSUE THREAD

**Issue by lampardnk** [thebaselab/codeapp#316]
So I’m using a windows layout BT keyboard to code and I’m not really comfortable with how most of the common ctrl commands (eg. Ctrl-C to copy) is replaced with Windows logo (so to copy I need to Windows logo C). So I would like to suggest that the app allows for custom button mappings or support for other keyboard layouts, not just Mac.

Additionally, is it just me or the app feels unresponsive sometimes? I try to left click on a file in the explorer to open it but even when my cursor is in between the file name (supposedly the center of the button), it takes several seconds of spamming left click to open the file.

Thank you, it’s a great app but it can be better

**Comment by bummoblizard** [comment]
Hey. The second issue is a bug from iPadOS that can be fixed by updating to iPadOS 15. 

Regarding the first issue, it's an iOS thing, as ctrl and command keys are different on macOS and iOS. I'll need to investigate if I can do anything about it from the app side.

**Comment by lampardnk** [comment]
Ok, I will update to see if the error goes away, thanks

**Comment by bummoblizard** [comment]
You can change the mapping behavior by the following method:
https://www.macrumors.com/how-to/remap-modifier-keys-ipad-keyboard/

**Comment by lampardnk** [comment]
Thank you so much!
