### ISSUE TITLE
Can not commit / push file changes to github upstream

### ISSUE THREAD

**Issue by lampardnk** [thebaselab/codeapp#317]
![C0DC5066-6B4F-4734-B434-3F3C433E363F](https://user-images.githubusercontent.com/28803484/146666627-551706a6-4e36-478f-93c0-65037f6b87d5.png)

I cloned my github repo so i can edit my files on the code app and then push those files back to github after saving my changes.

I configured my author identity and authentication correctly, and my account does not have 2FA, but it keeps showing this error as i try to push (the push option is in the 3 dots next to the yellow .cpp file in version control)

**Comment by lampardnk** [comment]
nevermind, instead of using your password for authentication use personal token

**Comment by bummoblizard** [comment]
That's correct. For GitHub, only personal access token will work regardless if 2FA is enabled.
