### ISSUE TITLE
SSH-keygen causes the terminal to stall

### ISSUE THREAD

**Issue by zoro273** [thebaselab/codeapp#318]
Running ssh-keygen from the terminal causes it to hand and the application needs to be killed.

**Comment by zoro273** [comment]
V1.2.7 December 2021

**Comment by zoro273** [comment]
As a comparison, ssh-keygen works perfectly fine when executed from a-shell app directly, and since a-shell also uses the same holzschu/a-shell engine, then probably the library included with codeapp needs to be updated.

**Comment by bummoblizard** [comment]
I can confirm. Thanks for reporting.
