### ISSUE TITLE
UI glitch on iPhone and git fetch issue

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#32]
Although it does say the fetch did succeed, it actually doesn’t, because the changes that were made on GitHub, are not visible, as well as the number next to the down arrow didn’t change, as well as the locals/remote repo isn’t changed at all, it stays the same as it was before the “fetch”. I would recommend adding back the merge feature as well. It also prevents me from pushing changes. Notice the highlighted part on the bottom bar on the first image, it still shows 6 GitHub commits, even though it says it successfully fetched them.
![EAB3CA50-D9CB-48BB-AF72-BDCE5B6DBEA3](https://user-images.githubusercontent.com/55695493/107638123-29802180-6c3d-11eb-99c1-08b122da3594.jpeg)
![9108E7E7-F3D4-45C4-9B00-BD5AFA39E5CB](https://user-images.githubusercontent.com/55695493/107638135-2b49e500-6c3d-11eb-84d3-f009896c2ba7.png)

Also, on the very top left corner, there is a little black rectangle, on the gray bar. I don’t know if it is the style I use, but it shouldn’t be happening. 

One more thing, I noticed there are a lot of bugs in a short amount of time since the most recent update. I would suggest using Apple' bug testing program, which I don’t remember the app name, if iirc it is Test _(something)_. Then I would send out testing invitations to certain people who you know would use it and give constructive feedback. If you need someone to help start bug testing/beta testing, just let me know. Try to get almost every bug squashed (more than this most recent update), and then release the update, even if it goes against your timeframe. Just some feedback on how the app versions work and happen, and how to prevent this many bugs. No offense meant, as well. Thanks for understanding!

**Comment by bummoblizard** [comment]
Merging is something I'm working on. Currently, you'll need to checkout to the latest commit manually.

Regarding the fetch issue, 6 represents the number of commits you are behind the remote and 1 represents the number of commits you are ahead of the remote. Although the files are not changed in the working directory, the git objects are fetched. You can checkout to the remote branch to see the changes.

**Comment by Lukas-Batema** [comment]
Okay, thanks!

**Comment by Lukas-Batema** [comment]
I still have some issues while using this app on iPhone, in landscape mode, @bummoblizard.
