### ISSUE TITLE
No pull function?

### ISSUE THREAD

**Issue by lampardnk** [thebaselab/codeapp#321]
My workflow goes: Code on pc vscode, commit and push, go on laptop, pull and work. 
Cant do the same for codeapp and can only clone which takes longer and asks you to go back to the parent folder and data consuming also.  Tried git pull origin master on terminal but stuck and the process does not finish execution

**Comment by bummoblizard** [comment]
Hi. The pull function is located in the source control section under the
three-dot menu. After pulling, you’ll need to manually checkout to the
latest commit by pressing and holding the left bottom corner showing main
or master.

**Comment by lampardnk** [comment]
![6896735D-003A-4E77-875C-B15F0FE74E1F](https://user-images.githubusercontent.com/28803484/147551475-6d4a1f13-3430-4e20-8121-e42f7c3dac10.png)
Thank you, here’s for anyone who needs it
