### ISSUE TITLE
Refreshing Local Repo

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#33]
When I refresh to show updated/created files in the unstashed changes section in Source Control, it sometimes will only do it once, maybe not even work at all, then when I swipe out the app after finishing 50+ file changes in many different files, it “discards” them, or should I say, “never saves” them. I think this is an issue with the git remote software in the app. Thanks for the help!

**Comment by bummoblizard** [comment]
Hello,

I see two problems you are describing here. 

Do you mean that changed / created files are sometimes not shown in the changes section?

And staged files are not actually staged?

**Comment by Lukas-Batema** [comment]
> Do you mean that changed / created files are sometimes not shown in the changes section?

I mean, when you use the refresh button, in the “Open Editors” section it sometimes won’t even recognize the changes made, in the “Source Control” section, which is because the app never thought it was actually changed in the first place, hence when reloading the app by swiping it from springboard, it reverts the changes WITHOUT user permission.

> And staged files are not actually staged?

That was just a way of trying to originally explains the issue, but it seems it caused some confusion. There is a staged section, which you have to now stage the changes before you can push/commit them in the local repo, which you probably already know. I don’t think this is an error, or that this is part of the issue. Thanks!

**Comment by bummoblizard** [comment]
Oh now I get it. That is probably because the file is never saved in the first place. You save a file by either dismissing the keyboard, running your code or pressing command-s.

Closing it for now. Feel free to reopen if the issue persists.

**Comment by Lukas-Batema** [comment]
> Oh now I get it. That is probably because the file is never saved in the first place. You save a file by either dismissing the keyboard, running your code or pressing command-s.

On mobile (iOS) it doesn’t let me dismiss the keyboard, I have to do it by clicking on the terminal (</>) symbol on side bar, click the tab called terminal, click to “type” and then it brings the keyboard down and up, then back down quickly.

**Comment by bummoblizard** [comment]
You can dismiss the keyboard by tapping the empty area under the terminal tab. Again, I’m aware that the UI on iPhone should be more optimized.
