### ISSUE TITLE
How to change keyboard shortcuts with my Apple Magic Keyboard

### ISSUE THREAD

**Issue by sylvoie** [thebaselab/codeapp#334]
Hello,

Like I explained in issue #237 with my Apple Magic Keyboard French Canadien, some shortcuts are not working. I’m looking to configure some keyboard shortcuts to be more efficient. I know that I can use command panel with cmd+shift+P, but I prefer keyboard shortcuts.

Is-it possible to change keyboard shortcuts configuration for indent line, oudent line and go to bracket?

I tried on my MacBook Pro with VSC and those native shortcuts control-option-cmd-9 (outdent), control-option-cmd-0 (Indent) and control+option+cmd+- (go to bracket) work fine.

I wish to use the same shortcuts on my iPad and my MacBook Pro! It’s easier to memorize.

Need your help?

Thank’s

**Comment by bummoblizard** [comment]
Thank you for reaching out. This is not yet possible and I'll see how I can implement this.

**Comment by sylvoie** [comment]
Thank you!
