### ISSUE TITLE
git push 失败

### ISSUE THREAD

**Issue by linxs953** [thebaselab/codeapp#337]
ipad上git push，提示too many redirects or authentication replays，凭据设置的github的帐号密码确认是没问题的

![8824A154-FC0B-4B20-88AA-C236695648A9](https://user-images.githubusercontent.com/20058709/150660053-1c5c7db5-81da-406e-914f-6007ed41aed6.jpeg)

**Comment by bummoblizard** [comment]
请用个人访问令牌，而不是密码。请参阅https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by linxs953** [comment]
ok，可以了
