### ISSUE TITLE
solve the “__int64” error

### ISSUE THREAD

**Issue by UniverseJoe** [thebaselab/codeapp#345]
the C++ clang can’t verify the “__int64”
![9F0338B8-08C5-446A-BB98-568F9A0A988E](https://user-images.githubusercontent.com/98860592/152081517-ec419a06-2e60-4e92-89b6-0ca444f6371a.png)

**Comment by bummoblizard** [comment]
Use `#define __int64 long long`.
__int64 is not available in clang.

**Comment by UniverseJoe** [comment]
> 

how could I use __int64 in code app?
