### ISSUE TITLE
Trouble running php server

### ISSUE THREAD

**Issue by BlueBird931** [thebaselab/codeapp#346]
I’ve been trying to run a php development server from my iPad but even after reading countless times the wiki I can’t get it to work properly.

What happends is that after I run the command `php -S localhost:8000` And open the website from `localhost:8000` it only seems to process the first page, and if from there I try to go to any other page it just doesn’t load, or loads after a few minutes but without loading the CSS.

A thing I noticed is that after running the `php -S localhost:8000` command the terminal doesn’t print anything, but it does print the full log when i stop the server by pressing ctrl+c on the terminal.

Hardware info:
iPad air (3rd generation) running 14.8.1 (18H107)

**Comment by bummoblizard** [comment]
Hi. As iOS apps don't run in the background, you'll need to have both Safari and Code App opened for the server to work.

As for the log message, it's probably a bug. I'll see what I can do about it.

**Comment by BlueBird931** [comment]
I’ve tried running it with split screen as you suggested, but now it loads the pages without running php and only shows a page with all the unexecuted code.

**Comment by bummoblizard** [comment]
Are you sure that you are visiting the right address? You might also try to
change the port of the php server.

**Comment by BlueBird931** [comment]
I’ve changed the port from 8000 to 80 and now it works.
But I still have a problem: all the realtive paths seem to be broken.
For example, if from the page located in the main directory i go to another page in a subfolder the css links with relative paths stop working.

**Comment by bummoblizard** [comment]
I am not able to reproduce to problem. Can you show me the code to reproduce the problem? And make sure you are running the php server from the right directory.

**Comment by BlueBird931** [comment]
Here’s the entire folder with all the files:

[Esercizi-Web-Scuola.zip](https://github.com/thebaselab/codeapp/files/7985127/Esercizi-Web-Scuola.zip)

The main folder “Esercizi-Web-Scuola” contains links to 2 pages in 2 subfolders: “informatica” and “tpsit”.
Each subpage has a link to it’s respective css file and another to the main css file in the main folder.

The subfolders contain subfolders of their own with more pages but they’re not important.

When starting the server I’ve made sure to run the command from the main folder.

**Comment by bummoblizard** [comment]
I think this is the expected behaviour as I tried to run it on my desktop. Try to use an absolute path instead. 

For example, line 7 in informatica/index.php would be
```html
<link rel="stylesheet" href="/informatica/styleInfo.css">
```

**Comment by bummoblizard** [comment]
Update: I'm not too familiar with php, but visiting `http://localhost:80/informatica/index.php` works for me.

**Comment by BlueBird931** [comment]
Got it, specifying the file directly fixes the problem.
I tried visiting `http://localhost/informatica/index.php` And other pages and everything works as intended.
I’ll just have to adjust some links that were pointing only to the directory and not directly to the file.
Thank you for the help!
