### ISSUE TITLE
Terminal and GUI do not push staged changes

### ISSUE THREAD

**Issue by ElbyBruceCPF** [thebaselab/codeapp#347]
Hello,

I have connected to a private GitHub repo and successfully synced the files to my iPad. I am not able to push the changes, however. I have tried:

Terminal
- git add .
- git commit -m "Message"
- git push

GUI
- Stage all changes
- Add message
- Checkmark
- This resulted in a success message, however, the commit is not visible in GitHub

Thank you,
Elby

**Comment by Lukas-Batema** [comment]
Now you can use the GUI of git push, since it successfully committed it.

**Comment by ElbyBruceCPF** [comment]
I tried it again and the GUI works but the terminal does not -- I need to be able to push to the server as well with:

git push [server] [branch]

Is that supported?

**Comment by Lukas-Batema** [comment]
> I tried it again and the GUI works but the terminal does not -- I need to be able to push to the server as well with:
> 
> git push [server] [branch]
> 
> Is that supported?

I am not sure. I don't think any git commands work correctly in the terminal, but it'd be better to wait for someone else to reply on this.

**Comment by bummoblizard** [comment]
Git command is now removed from the latest version. GUI is now the only way to do git operations.
