### ISSUE TITLE
Force remote execution?

### ISSUE THREAD

**Issue by suchipi** [thebaselab/codeapp#348]
I’m trying to run `npm install` for a project I cloned from github, but it runs out of memory.

Is it possible to “force” remote execution for node, instead of using the local execution? Or, can I SSH into my own server and do everything there?

**Comment by bummoblizard** [comment]
SSH support is being working on.

**Comment by suchipi** [comment]
Which issue tracks SSH support, so I can subscribe to it?

**Comment by suchipi** [comment]
Though, this issue wasn't specifically about SSH; it was about using the "remote execution" judge0 stuff.

**Comment by bummoblizard** [comment]
The issue tracking it: https://github.com/thebaselab/codeapp/issues/76

Judge0 wouldn't be useful here because it's designed to run simple scripts and would not install rpm modules.  It should also be mentioned that node is updated to 16.13.2 in the latest commit. It might help the with problem you mentioned above.

**Comment by suchipi** [comment]
Gotcha. Thanks! I'll give it a shot.

**Comment by bummoblizard** [comment]
> Also, your app rocks! I love that the vscode-like sidebar is implemented using native views. Thank you for making it!

Glad you liked it! The update mentioned above should be available on TestFlight this week.

**Comment by wattsie** [comment]
> > Also, your app rocks! I love that the vscode-like sidebar is implemented using native views. Thank you for making it!
> 
> Glad you liked it! The update mentioned above should be available on TestFlight this week.

Any update on TestFlight version?
