### ISSUE TITLE
Advice and Question

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#35]
Dear @bummoblizard,
What language do you use to program this application? If it is Swift, I can help, as well as transferring the app to Android, with Java. Just let me know if you need/want any extra help from me. Also, I noticed there are a lot of bugs in a short amount of time since the most recent update. I would suggest using Apple' bug testing program, which I don’t remember the app name, if iirc it is Test (something). Then I would send out testing invitations to certain people who you know would use it and give constructive feedback. If you need someone to help start bug testing/beta testing, just let me know. Try to get almost every bug squashed (more than this most recent update), and then release the update, even if it goes against your timeframe. Just some feedback on how the app versions work and happen, and how to prevent this many bugs. No offense meant, as well. Thanks for understanding!

_Disclaimer: This was put here as a separate issue, just in case you didn’t see it in #32._

Best Wishes,
Lukas Batema

**Comment by bummoblizard** [comment]
Hello Lukas,

The app is written in Swift and TypeScript. However, I don’t have a plan to open source this project or port it to Android as it’s still in its early stage. Thanks for the offer though!

Regarding the bugs, I have submitted an update to the App Store. It should be released in a day or two. TestFlight is also a great idea. I will post a link to it in the future.

Ken

**Comment by bummoblizard** [comment]
Closing this for now.
