### ISSUE TITLE
Markdown 中文标点黄色警告建议去处，影响编写体验

### ISSUE THREAD

**Issue by lijiakof** [thebaselab/codeapp#350]
我是一个vs code 下重度使用markdown+git写作的程序员，最近开始用iPad进行办公，发现CodeApp的确是一个不错的应用，在使用过程中发现Markdown 中文标点黄色警告建议去处，影响编写体验。如下图：
![818647C8-35A2-428A-B776-CD189BD8D628](https://user-images.githubusercontent.com/2752008/152829312-2ef9b4ea-80dd-4944-8fbd-493c75f7067e.jpeg)

**Comment by lijiakof** [comment]
我检查了，不是搜索造成的。另外这不同的标点符号，只要是中文标点就这样。

**Comment by bummoblizard** [comment]
Let's track it here: https://github.com/microsoft/monaco-editor/issues/2955
