### ISSUE TITLE
使用git 无法clone项目，请求帮助谢谢！

### ISSUE THREAD

**Issue by xcl331** [thebaselab/codeapp#356]
git clone一个public项目是没有问题的。但clone一个private项目，
提示：templates not fund in /user/local/share/git-core/templates
我录入全局的登录信息git config —global user.name ”” 
提示error: could not lock config file /private/var/mobile/Containers/Data/Application/37D10A8B-EDD3-4CA1-8DBE-29259304B8C7/.gitconfig: Operation not permitted
我应该如何设置？？

谢谢🙏

**Comment by bummoblizard** [comment]
Git命令在最新版本中已经删除。 请按GUI来代替。
