### ISSUE TITLE
app不能同步代码，在终端输入代码也不好用。最终导致终端死掉

### ISSUE THREAD

**Issue by xcl331** [thebaselab/codeapp#357]
![99c570275378a4c2c0e6f19bbd768be](https://user-images.githubusercontent.com/7325526/154405141-da4207a3-c15a-4bd4-aa69-b0c016ef24b9.jpg)

左下角显示有2个同步，点击不好用。再终端输入git pull等了好久也没有反应，停了命令后，再输入任何命令终端都不好用了。必须重启app才可以。

**Comment by bummoblizard** [comment]
Git命令在最新版本中已经删除。 请按住左下角来代替GUI。

**Comment by xcl331** [comment]
我这里，按住左下角的分支可以弹出选择，但按住左下脚的pull和push没有任何反应，不会带出任何操作。不知道是什么原因？
