### ISSUE TITLE
Unable to move/change text selection

### ISSUE THREAD

**Issue by KamilTheDev** [thebaselab/codeapp#359]
**Device:** iPad Pro (11-inch), iOS 15.3.1

I'm unable to select text properly. I double tap to select an initial word, but then I cannot move/change the text selection at all.

Here's a screen recording. I double tap "Hello", and try move the text selection to "Hello, World". 

https://user-images.githubusercontent.com/98935285/154841718-6fa402f7-a430-43e5-bac3-bdc2dbed0b26.MOV

I just got codeapp today. Previously I used Spck Editor, but it stopped getting updates on iOS, so now it's fairly outdated.

Spck Editor's text selection works great. They have big buttons for moving text selection, and a quick-menu popup. Here's a screenshot:
![CECDB74A-9420-4772-AF0F-E7F74A09A86D](https://user-images.githubusercontent.com/98935285/154842461-6b12c1c1-368f-4fbd-9fb9-bfabc4cffb27.jpeg)

---

Please fix this, I can't really use codeapp until properly selecting text is possible. I also hope you can add a quick-menu popup for Cut/Copy/Paste/Select All, as shown in the Spck Editor screenshot.

**Comment by bummoblizard** [comment]
Thank you for reaching out. I know it's important and  I will try to replicate this feature.
