### ISSUE TITLE
Error message warning templates not found in /usr/local/share/git-core/templates

### ISSUE THREAD

**Issue by socialmedialabs** [thebaselab/codeapp#363]
When trying to clone a repository from GitHub.com via SSH I get the following message:

**warning templates not found in /usr/local/share/git-core/templates**

The terminal then dies and in most cases codeapp itself crashes as well.

A user on StackOverflow suggests to create that folder manually but the shell denies with „cd: /usr: permission denied“

**Comment by bummoblizard** [comment]
Hi. I assume you are using the TestFlight version. Git command is experimental and does not work properly. It's not included in the App Store version.

**Comment by socialmedialabs** [comment]
This happens with the latest version v1.2.9 build 42. I went ahead and reinstalled codeapp but it‘s still the same.

This issue is reproducible.

**Comment by bummoblizard** [comment]
Thanks for the information. In that case, I might have mistakenly included git in the build. 

It's an experimental port and should not be expected to work properly. Sorry for the confusion.
