### ISSUE TITLE
[Git] Cannot pull the changes from remote Github repository. 

### ISSUE THREAD

**Issue by dashplaygrounds** [thebaselab/codeapp#364]
There is only "fetch" function but no "pull" function. The command "git pull" doesn't work. 
In order to get the latest changes in the file, I deleted the local repository and cloned it again.

The experience will be better if this is fixed. Thanks!

**Comment by dpadmin629** [comment]
I did the workaround and it worked. But for those like me who are comfortable using the git commands on the terminal, the experience on the app will be better if this a part of the enhancement. Thanks!

**Comment by bummoblizard** [comment]
I understand and it's being working on.

**Comment by bummoblizard** [comment]
Pull is now available.
