### ISSUE TITLE
clang does not load on iPadOS 15.4

### ISSUE THREAD

**Issue by Lin-Fusion** [thebaselab/codeapp#365]
错误提示：clang : command not found
![IMG_0393](https://user-images.githubusercontent.com/96066367/155951444-80affb93-1a5b-4372-b7f7-a4582cda88b4.PNG)

**Comment by Lin-Fusion** [comment]
The same problem with C++, iPadOS version 15.4

**Comment by bummoblizard** [comment]
请尝试重新启动iPad。

**Comment by Lin-Fusion** [comment]
> 请尝试重新启动iPad。

It reports the same after reboot ipad or restart the app.

**Comment by bummoblizard** [comment]
In that case, I would suggest reinstalling the app. 

If it still doesn't work, please let me know your iPad model.

**Comment by Lin-Fusion** [comment]
> 



> In that case, I would suggest reinstalling the app.
> 
> If it still doesn't work, please let me know your iPad model.

Reinstalling doesn't work, the ipad model is ipad pro 2021(A2377)

**Comment by bummoblizard** [comment]
Thank you for letting me know. I will try to reproduce this issue.

**Comment by bummoblizard** [comment]
By the way, which version of Code App are you on? You can check by scrolling to the bottom of the settings menu.

**Comment by Lin-Fusion** [comment]
> By the way, which version of Code App are you on? You can check by scrolling to the bottom of the settings menu.

Version 1.2.9 Build42. I intalled it on another ipad and it works.

**Comment by Lin-Fusion** [comment]
I have flashed my ipad to iPad os 15.3 and it works perfectly, but due to some data I have to go back to iPad  os 15.4. It can be the bug of new iPad os.

**Comment by wjh7000** [comment]
![image](https://user-images.githubusercontent.com/51263521/158508603-665165f5-838a-42f6-aac2-38f9e9840de7.png)
![image](https://user-images.githubusercontent.com/51263521/158508627-aa4ba280-f355-4be4-80c5-47292ac3cfee.png)

编译C和C++都会出现这个问题
iPadOS 15.4正式版，iPad Pro 2020 11寸

**Comment by cfvescovo** [comment]
Same problem here using iPadOS 15.4 on my iPad Pro 11 2020

**Comment by Happinesspill** [comment]
Same problem when compiling C or C++
iPadOS 15.4 official released version，iPad Pro 2020 11 inch
App version: 1.2.12 build 45

> ![image](https://user-images.githubusercontent.com/51263521/158508603-665165f5-838a-42f6-aac2-38f9e9840de7.png) ![image](https://user-images.githubusercontent.com/51263521/158508627-aa4ba280-f355-4be4-80c5-47292ac3cfee.png)
> 
> 编译C和C++都会出现这个问题 iPadOS 15.4正式版，iPad Pro 2020 11寸
> 
> Same problem when compiling C or C++ iPadOS 15.4 official released version，iPad Pro 2020 11 inch

**Comment by bummoblizard** [comment]
This is fixed in the latest release. It will be available on the App Store in a day or two.
