### ISSUE TITLE
iPad上如何连接GitHub的代码仓？凭据怎么配置？

### ISSUE THREAD

**Issue by Armison** [thebaselab/codeapp#366]

**Comment by bummoblizard** [comment]
问：我无法克隆私有存储库或将更改推送到我的存储库

答：您需要在“设置”>版本控制>身份验证”中设置凭据。在许多情况下，

您需要使用个人访问令牌，而不是常规密码。有关GitHub，请参阅https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
