### ISSUE TITLE
Can some of the languages be locally compiled or interpreted ?

### ISSUE THREAD

**Issue by Rishi5813** [thebaselab/codeapp#37]
It would be great if some of the languages run locally like Python and C. It would too be faster than the sever compilation and would make this app as good as a IDE on our desktops.

Thank You

**Comment by bummoblizard** [comment]
Yes. It will be possible to run Python or C code locally. I plan to include this feature in March's update.

**Comment by Rishi5813** [comment]
It wolud be too lengthy to write whole environment and runtime for Languages, you can take help of some Opensource github ios apps such as ish or a-shell and make some changes to the ui of their app and then add it to the Terminal window, is it Possible ?

**Comment by bummoblizard** [comment]
Hi @Rishi5813. It’s totally possible and local development is a core goal of this project. 

Code App’s terminal is based on an open source project called `ios_system` by a-shell’s author. After some modification and extension, Python and NodeJS runtime are indeed working in the development build, they also come with pip and npm support. 

You can expect the update to be available in early March :)

**Comment by Rishi5813** [comment]
Okay Thanks !

**Comment by bummoblizard** [comment]
Many languages can now be locally compiled or interpreted, including C, C++, Python, PHP, Node.js

**Comment by hg0428** [comment]
I would love to see an expansion of the locally available languages. I know how difficult this is, but its a great idea.

**Comment by bummoblizard** [comment]
> I would love to see an expansion of the locally available languages. I know how difficult this is, but its a great idea.

What languages do you wish the app to support?

**Comment by hg0428** [comment]
> > I would love to see an expansion of the locally available languages. I know how difficult this is, but its a great idea.
> 
> What languages do you wish the app to support?

I would love to see support for Java.
I would also like support for Gwion, but thats mainly because I am friends with its creator.

**Comment by rcarmo** [comment]
Golang would be nice (although quite challenging).
