### ISSUE TITLE
一些更新建议（有些功能没试过，如果没有希望采纳）

### ISSUE THREAD

**Issue by InkBlackScorpion** [thebaselab/codeapp#381]
1.为当前版本与后续减少内存提高下载速度和减少存储空间占用，更新**_离线编译包app内选择下载_**功能
2.**支持更多离线编译功能（c#希望可以优先）**
3.更新**运行过程中输入或按键操作**
4.**本机IO操作与访问其他文件内的类与函数**
5.**完善基本文本编辑功能**，如长按空格、全选的功能
6.**完善输入提示与实时报错**

**Comment by linotrylie** [comment]
预祝这个项目越来越好

**Comment by bummoblizard** [comment]
谢谢你的建议。

在iPad上开发C#代码的用例是什么？ASP.NET？Windows应用程序？我对C#不太熟悉，但我想它与Windows平台有很多依赖性。

“mcs”在Linux上运行。（https://github.com/mono/mono）这似乎是一个很好的起点。
