### ISSUE TITLE
Git command cannot be used on the console in iPad Pro 

### ISSUE THREAD

**Issue by ginshin** [thebaselab/codeapp#387]
在 ipadpro 中突然无法在控制台中使用 git 命令，之前是可以的，那就无法对远程 git 仓库进行合并， Fetch 下来的文件也就无法 merge，麻烦看一下

If the git command cannot be used on the console in iPad Pro suddenly,  It was possible before. the remote git warehouse cannot be merged, and the files from fetch cannot be merged. Please have a look

**Comment by bummoblizard** [comment]
Git was removed due to its incompatible license and some technical difficulties. Please checkout to origin/master by holding the left bottom corner.

**Comment by ginshin** [comment]
Thanks
