### ISSUE TITLE
五条主要优化建议（帮助最大的是前两条）

### ISSUE THREAD

**Issue by InkBlackScorpion** [thebaselab/codeapp#390]
我可能发过一组建议，不过整体太过杂乱，这篇文章里直接整理出五条建议
首先评价一下这款软件两个主要功能
文本编辑：在中国市场名为“ES文件浏览器”的免费软件中自带的编辑器似乎不逊色于这款app（在一些方面甚至更方便）
编译与运行：中国市场名为“编程狮”的免费app中的工具箱内置了功能与这款app完全一样的线上编译工具，也就是说，可以从“ES文件浏览器”中编辑文本，测试时粘贴在“编程狮”的编译工具中，似乎能够取代这款app
建议：
如果能够实现以下五条中的任何一条，就能领先于ES与编程狮（即30RMB花得更值）
1.实时代码补全
2.实时错误检查
3.多文件编译（调用其他文件的class等）
4.本地或服务器托管IO操作
5.时间操作（即读取服务器或本机当前 时、分、秒）

**Comment by OP-ACE** [comment]
能否把 阅读模式 或 叫只读模式 放在主界面上，毕竟在ios上更多时候是看代码，偶尔运行代码。
谢谢~

**Comment by bummoblizard** [comment]
1.实时代码补全
- JavaScript, TypeScript, HTML, CSS 均有
2.实时错误检查
- 同上
3.多文件编译（调用其他文件的class等）
- 本地编译的语言均有支持
4.本地或服务器托管IO操作
- 同上
5.时间操作（即读取服务器或本机当前 时、分、秒
- 同上

似乎將JDK直接移植到iOS是最好的解決方法: https://github.com/thebaselab/codeapp/issues/101
