### ISSUE TITLE
Pushing commit to git takes really long

### ISSUE THREAD

**Issue by Default-01** [thebaselab/codeapp#392]
When im pushing a commit with git it takes a long time before i can see the commit in my GitHub repository. Why is this taking so long to appear?

**Comment by bummoblizard** [comment]
Is this a problem specific to Code App? It would be great if you can check if it works as expected on a desktop.

**Comment by Default-01** [comment]
Git works as intended on PC

**Comment by bummoblizard** [comment]
> Git works as intended on PC

I see. Is it a large repo? If it's, can you reproduce this issue on a small repo?

**Comment by Default-01** [comment]
It should not take a couple of hours, and sometimes it does not work at all.

**Comment by bummoblizard** [comment]
There were problems with GitHub's server recently. Can you check if it works as intended now?

**Comment by Default-01** [comment]
It still does not show up in github as commit
