### ISSUE TITLE
Question re: Git and CLI

### ISSUE THREAD

**Issue by socialmedialabs** [thebaselab/codeapp#396]
Why is it not possible to use Git via CLI?

When attempting to use `git clone` or any other git command I get the error `command not found`.

So while Git is available via UI it isn't via CLI and I'd like to understand why that is.

**Comment by bummoblizard** [comment]
Because I haven't been able to port git cli to iOS. The UI uses libgit2 instead of the cli tool.

**Comment by socialmedialabs** [comment]
Thank you for clarification.
