### ISSUE TITLE
在html里写中文，运行到浏览器显示乱码

### ISSUE THREAD

**Issue by elfinc** [thebaselab/codeapp#398]

**Comment by bummoblizard** [comment]
```html
<head>
  <meta charset="utf-8">
  ...
</head>
```

**Comment by elfinc** [comment]
![BF657434-C817-449C-A8F8-1C75A5DBD565](https://user-images.githubusercontent.com/24192826/160443111-cec5f847-4f75-482d-bc05-7f7d50c80142.jpeg)
![86134742-2DBF-439F-AC25-E50ED0AF38E6](https://user-images.githubusercontent.com/24192826/160443119-6209d459-92da-465c-b6c6-6c9e5a2d2424.jpeg)

**Comment by elfinc** [comment]
> 

啊，感谢。。
