### ISSUE TITLE
Sidebar buttons sometimes not responding to pointer clicks

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#4]
When using a mouse or a trackpad, buttons in the sidebar sometimes don't respond to clicks.

Current workaround: Right click / long press the buttons to bring up context menu and the button becomes responsive.

**Comment by Twelvesuns** [comment]
file:///private/var/mobile/Library/Mobile%20Documents/X6B29J8D22~com~savysoda~documents/Documents/Printer%20info.rtf.original

**Comment by bummoblizard** [comment]
Seems to be fixed in iPadOS 14.5.
