### ISSUE TITLE
March's Update (Node.js + Python) now available on App Store

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#40]
Hello! 1.2.0 update is now available for testing on App Store! You can now run Python or Javascript script locally with package managers support. Here's what changed.

A guide on using Node.js:
https://github.com/thebaselab/codeapp/blob/main/documentation/working-with-nodejs.md

You could also submit issues on GitHub or TestFlight. 

### v1.2.0 (March 2021)
- Node.js runtime
  - Run Javascript offline
  - Install npm modules
  - Install Javascript commands globally (tsc, prettier etc.)
  - New terminal commands: npm, npx, node
- Python 3.9.2 runtime
  - Run Python offline
  - Install modules with pip
  - Install Python commands globally
  - New terminal commands: pip, python, python3
- Editor
  - `Problems` tab
  - New Markdown style
  - Syntax highlighting for Vue
  - Smooth Scrolling option for devices with high refresh rate
- Terminal
  - Now supports light colour scheme
- File exploerer
  - Reduced row height
- Bug fixes

**Comment by Rishi5813** [comment]
I am sorry that posted that issue on that page, i thought it was a common problem of nodejs which was being discussed on the issue.

**Comment by Frodo20** [comment]
Python's matplotlib still couldn't be installed.

**Comment by bummoblizard** [comment]
> Python's matplotlib still couldn't be installed.

Will try to include it in the next update.

**Comment by Lukas-Batema** [comment]
Will April’s and future monthly updates be on TestFlight? I really enjoyed the new feature beta testing! Also, Didn’t March’s release come out already, so shouldn’t April's Update be pinned, and not this one? Thanks!

**Comment by bummoblizard** [comment]
Hi Lukas. There has been some delay in the development due to my schedule and the amount of issues I need to fix. I will upload the build to TestFlight once it's ready.

**Comment by Lukas-Batema** [comment]
Ah, ok. Sorry about that :), take as much time as you need!
