### ISSUE TITLE
Not Being able to compile Java projects without Main class.

### ISSUE THREAD

**Issue by CodeStrate** [thebaselab/codeapp#403]
I have a file, suppose PriorityQueueDemo, with one class of the same name, I can't run it since it says no main class found.

Please fix it

**Comment by caffed** [comment]
The `main` entry point is required by the JVM https://docs.oracle.com/javase/specs/jls/se11/html/jls-12.html#jls-12.1.

Also stating "Please fix it" without any suggestions is rude and will not help your cause.

**Comment by CodeStrate** [comment]
> The `main` entry point is required by the JVM https://docs.oracle.com/javase/specs/jls/se11/html/jls-12.html#jls-12.1.
> 
> 
> 
> Also stating "Please fix it" without any suggestions is rude and will not help your cause.

> There is a `main` entry point and my program mostly only runs when I rename my class to Main and file to Main.java .
> I mostly face issues with Java codes in the App.
