### ISSUE TITLE
TestFlight Beta - Crashing

### ISSUE THREAD

**Issue by Rishi5813** [thebaselab/codeapp#41]
I just installed The TestFlight update on my iPad, it crashed as soon as I opened it. I thought I should inform you about this.

**Comment by bummoblizard** [comment]
Hello. Please try updating to build 8 and see if the problem persists.

**Comment by Rishi5813** [comment]
Okay

**Comment by Rishi5813** [comment]
It is Resolved, it was my Testflight Problem, I reinstalled it. It Worked By That

**Comment by Lukas-Batema** [comment]
I had to do the same. On iPhone 6s, 14.x

**Comment by bummoblizard** [comment]
Reopening as I see other reports on this. I can't seem to reproduce it though. It would be appreciated if any reproducible steps can be provided. Could be an iOS version issue.

**Comment by bummoblizard** [comment]
I might have identified the issue. Build 10 should fix this.

**Comment by Lukas-Batema** [comment]
> Reopening as I see other reports on this. I can't seem to reproduce it though. It would be appreciated if any reproducible steps can be provided. Could be an iOS version issue.
> 
> I tested it on iPad 8th generation and iPhone 8, both are on 14.4.

My iPhone 6s is at 14.4 as well, as I checked in further investigation into my general -> about (in settings)
