### ISSUE TITLE
SFTP connect

### ISSUE THREAD

**Issue by orgserj** [thebaselab/codeapp#419]
HOw add server for sftp connect?

**Comment by bummoblizard** [comment]
Thank you for reaching out! I assume you are using the TestFlight version. SFTP is just a ssh connection. You'll need to enabled ssh access in your computer.

For Mac: https://support.apple.com/en-gb/guide/mac-help/mchlp1066/mac

**Comment by orgserj** [comment]
> Thank you for reaching out! I assume you are using the TestFlight version. SFTP is just a ssh connection. You'll need to enable ssh access in your computer.

Yes, testflight. I can't find the item in the application interface how to add my server

**Comment by bummoblizard** [comment]
Are you using an iPhone? The feature is not yet available for iPhone.

**Comment by orgserj** [comment]
> Are you using an iPhone? The feature is not yet available for iPhone.

Yes, your application is very convenient as it is similar to vscode, add sftp support on iphone please (download upload edit files). It is because of this function that I am ready to buy in the apple store! It would be ideal to add pylance)  thank

**Comment by bummoblizard** [comment]
@orgserj It's now available in the latest TestFlight build.
