### ISSUE TITLE
Terminal does not work

### ISSUE THREAD

**Issue by k-corby** [thebaselab/codeapp#42]
Hi, just letting you know since the latest update I am not able to use terminal to install npm or python extensions. The terminal is just a grey area with not ability to click and type etc. Also local python script do not compile. External python script 2.7 work fine through your server.

**Comment by bummoblizard** [comment]
Thanks for letting me know. I have submitted a fix and it should be fixed in a day or two.

**Comment by bummoblizard** [comment]
For those who are experiencing this problem, you might download the TestFlight version from https://testflight.apple.com/join/EgZ8sE2P.

Sorry for the trouble caused. It's a configuration error I made when releasing the latest version.

**Comment by bummoblizard** [comment]
1.2.1 released.
