### ISSUE TITLE
Fetch showing "too many redirects or authentication replays"

### ISSUE THREAD

**Issue by TheEnlightened1** [thebaselab/codeapp#428]
Hi folks

App has been working amazing for me,github integrating well, until today. When I go to fetch my recent commits I get 

![image](https://user-images.githubusercontent.com/93515955/165508163-ae24f69e-fcab-4c95-8fdf-fef7da707ae0.png)

It takes quite a while for this message to pop up. 

I've been pushing and fetching from this repo fine, but the recent commit (done on my desktop in another IDE) that it is trying to pull is quite a lot of CSV files. Maybe it's struggling with the size? 

Any help appreciated

**Comment by bummoblizard** [comment]
Thank you for reaching out! The access token is probably expired. You’ll
need to generate another one in GitHub.

**Comment by TheEnlightened1** [comment]
Arrgh! Totally didn't realise my token expired yesterday 🙄

New token and now working again. 

Thankyou! Can now close this.
