### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#434]
I noticed that there is no Discord Server for this project. I think it would be very beneficial because it could be used for support and stuff, to keep the issues and stuff decluttered from repeated questions. If there is one already, please link me to it. Thanks!

**Comment by CoolOllie2** [comment]
I agree, if you need help to create and manage one. I can run it for you and give you administrator.

**Comment by bummoblizard** [comment]
I don't think I have the time to manage a discord server. Discussions tab in GitHub should do the work.

**Comment by Lukas-Batema** [comment]
Sadge, okay. It could reach more users, marketing-wise tbh.
