### ISSUE TITLE
`mkdir -p ~/Library/usr/share/man/man1` Not permitted

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#435]
When running the command in the title, it says, `Operation not Permitted`, even though I can run, `mkdir -p ~/Library/usr/bin` then run, `mkdir -p ~/Library/usr/bin/neofetch` (in my case to manually run the steps in a Makefile, since there is no `make` command, which is referenced in my previous issue), without error. From previous attempts, running, `mkdir -p ~/Library/usr/bin/neofetch` right off the bat, produces, `Operation not Permitted`, which is why I did that in two separate steps, after, `ls ~/Library/usr`, which showed there was no, `~/Library/usr/bin` directory, which shows that this is because there is not a directory, and I have to make one. This is the same issue here, but I cannot do, `mkdir -p ~/Library/usr/share/man`, then `mkdir -p ~/Library/usr/share/man/man1`, as I did with my original come-across with this issue. Making the, `~/Library/usr/share/man` directory gave the, `Operation not Permitted` error as well, so I then, `ls ~/Library/usr` (again), which showed that there was in fact a, `~/Library/usr/share` directory. Then I did, `ls ~/Library/usr/share`, which showed there was no, `~/Library/usr/share/man` directory, which is a similar outcome (just different directories) as in my first issue, but the same fix, did not work as expected. Any thoughts? Is this due to permissions? I don't think it is a permission issue, since it let me make the, `~/Library/usr/bin` and `~/Library/usr/bin/neofetch` directories in this way. Thanks!

**Comment by bummoblizard** [comment]
It is actually a permission error. iOS apps live inside their own sandboxes and the only accessible directories are Documents, Library and tmp under `/var/mobile/Containers/Data/Application/2F8A1C1E-1969-47EA-BC8F-542414DA4A15/{folder}`.

Anything outside the uuid will not be accessible. You can read more about his in https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html.

To work around this, we configured bin folder as Documents/bin and Library/bin. You can get the full list by running echo $PATH in the terminal.

**Comment by Lukas-Batema** [comment]
Got it, is this a way I can work around it too?

**Comment by bummoblizard** [comment]
> Got it, is this a way I can work around it too?

Sorry I didn't see your comment thoroughly. The ~/Library directory is actually accessible but usr/share is a symlink to the app resources created by the app. It is therefore not editable.

To work around this, put the files in another directory if possible.

**Comment by Lukas-Batema** [comment]
Yeah, that didn't work. Will try something different later.
