### ISSUE TITLE
More fonts

### ISSUE THREAD

**Issue by louka-dubois** [thebaselab/codeapp#439]
Possibility to change the font could be very nice, like for the font Fira Code 👀

**Comment by bummoblizard** [comment]
![Simulator Screen Shot - iPad (9th generation) - 2022-05-29 at 16 22 33](https://user-images.githubusercontent.com/38398443/170859048-481388a9-a90c-4c27-8c44-9b00c0f81b73.png)

**Comment by Lukas-Batema** [comment]
This looks nice! Thanks!

**Comment by louka-dubois** [comment]
Omg that is amazing! Thank you!

**Comment by bummoblizard** [comment]
It's available on TestFlight :)
