### ISSUE TITLE
cannot run java

### ISSUE THREAD

**Issue by xyxyx718** [thebaselab/codeapp#440]
![FBB4236C-3E34-4293-8D8F-B6A1E10C1CCD](https://user-images.githubusercontent.com/59339633/166858107-e9bca11a-2187-4044-8f0c-79638860c35b.png)

**Comment by carrotPeanutButter** [comment]
I opened the same issue before. The response from owner is the current version can only run java file named Main.java(something like that). A different class name or file name may cause issue like this.

**Comment by Oruelas07** [comment]
I'm having this issue hopefully they can fix it
