### ISSUE TITLE
git 无法 push

### ISSUE THREAD

**Issue by SP-FA** [thebaselab/codeapp#446]
从自己的 git 上clone了代码，写完之后push显示 Credentials are not configured，同时我发现也无法进行 fetch，请问如何解决。
设备：ipad pro 2021
系统：ios 15.4.1

![3DF4BC07-F07F-4054-BB1C-933E49162FF4](https://user-images.githubusercontent.com/59771007/168463247-32e8f656-75e8-4f56-84e2-3a86f057a614.jpeg)

**Comment by bummoblizard** [comment]
Settings > Source Control > Credentials > Enter your personal access token
https://docs.github.com/cn/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
