### ISSUE TITLE
Support for cloning into and pushing to github branches

### ISSUE THREAD

**Issue by hg0428** [thebaselab/codeapp#450]
This is crucial for any developer that has any large projects. I have a repo where I often push to a developer branch, so I need this feature.

**Comment by bummoblizard** [comment]
You can switch branches by holding the branch name in the left bottom corner.

**Comment by hg0428** [comment]
> You can switch branches by holding the branch name in the left bottom corner.

Wow, that button is super tiny. I can't seem to press it though, and nothing happens when I do.

**Comment by hg0428** [comment]
I would be happy to close this once I figure out how to press that button

**Comment by hg0428** [comment]
Oh, wait, you have to hold it.
Why are there more options than branches I have?
I have 2 branches: main, and Developer, it shows:

- [ ] Orgin/main

- [ ] Orgin/Developer

- [ ] Orgin/HEAD

- [ ] main

I feel like thats a bug.
Also, what is the `at xxxxxxxx`?

**Comment by bummoblizard** [comment]
> Oh, wait, you have to hold it.
> 
> Why are there more options than branches I have?
> 
> I have 2 branches: main, and Developer, it shows:
> 
> 
> 
> - Orgin/main
> 
> 
> 
> - Orgin/Developer
> 
> 
> 
> - Orgin/HEAD
> 
> 
> 
> - main
> 
> 
> 
> I feel like thats a bug.
> 
> Also, what is the `at xxxxxxxx`?
> 
> 
> 
> 

It's not. Origin means the remote branch, when you check out to a remote branch, git creates a local copy of that branch hence the one without origin. Xxxxxxx is the hash of the commit, it is used to uniquely identify a commit.

Regarding the UI size, there's definitely room for improvement. Thank you for your feedback.
