### ISSUE TITLE
Regression: Existing users cannot access Themes / 订阅问题

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#453]
Code App switched to freemium in the latest release. Existing users should continue to have access to all features including Themes but it is not currently the case. I already uploaded the fixed build to App Store and hopefully they can approve it within today.

Sorry for the frustration caused.

在最新版本中，Code应用程序切换到免费。现有用户可以继续存取包括主题在内所有功能，但目前情况并非如此，在一两天内我会推出更新修复这个问题。我已经将版本上传到App Store，希望他们能在今天内批准。

抱歉为你带来不便。

**Comment by Lukas-Batema** [comment]
This may be related, the App Store says the in app purchase is null: ![image](https://user-images.githubusercontent.com/55695493/169072781-f87e2abf-6a89-4a80-bd49-2e39d7e9da8c.jpeg)

Q: will this fix moving from TestFlight back to the stable version, if a user has downloaded it previously (before freemium)? (In my case, before it cost money at all).

**Comment by bummoblizard** [comment]
> Please compensate the old users!

Hey. Existing users continue to have full access to all of the features forever. I'm sorry if you are frustrated by the pricing changes. It is a way to bring Code App free for more people.

**Comment by bummoblizard** [comment]
> This may be related, the App Store says the in app purchase is null: ![image](https://user-images.githubusercontent.com/55695493/169072781-f87e2abf-6a89-4a80-bd49-2e39d7e9da8c.jpeg)
> 
> Q: Will this fix moving from TestFlight back to the stable version, if a user has downloaded it previously (before freemium, which in n my case, it was before it cost money at all)?

The null value is unrelated I believe. The actual issue was related to validating purchase receipt. 

For your question, every user who downloaded the app before freemium, regardless free or not, can access all of the features without subscription.

**Comment by luanhaixin** [comment]
However, there is a charge for the theme function after my update! 100 yuan per year…

**Comment by bummoblizard** [comment]
> However, there is a charge for the theme function after my update! 100 yuan per year…

It's a bug that I will fix in an update today or tomorrow. You don't have to subscribe again.

**Comment by luanhaixin** [comment]
😂Then I can do it again! Code app is the best!

**Comment by Lukas-Batema** [comment]
> > This may be related, the App Store says the in app purchase is null: ![image](https://user-images.githubusercontent.com/55695493/169072781-f87e2abf-6a89-4a80-bd49-2e39d7e9da8c.jpeg)
> 
> > 
> 
> > Q: Will this fix moving from TestFlight back to the stable version, if a user has downloaded it previously (before freemium, which in n my case, it was before it cost money at all)?
> 
> 
> 
> The null value is unrelated I believe. The actual issue was related to validating purchase receipt. 
> 
> 
> 
> For your question, every user who downloaded the app before freemium, regardless free or not, can access all of the features without subscription.

Ah, ok. Thanks for the answer! I have been pleased with the app since I downloaded it on September 28, 2020. Thanks for the continued development!

**Comment by bummoblizard** [comment]
Fixed in the latest update.
