### ISSUE TITLE
CRITICAL BUG: Run button not working for node.js

### ISSUE THREAD

**Issue by hg0428** [thebaselab/codeapp#454]
Pressing the run causes an error.
Typing the command itself works, but only sometimes, as seen below.
https://user-images.githubusercontent.com/45984899/169101939-76c9f118-1808-4fb0-ad01-64981961c906.MOV

But, in other cases, with projects that have much more than a simple hello world, it doesn't work with the run or typing the command itself.

**Comment by hg0428** [comment]
![Uploading 6DC4C0D9-5B25-4319-83F7-B980B54245EF.png…]()

**Comment by hg0428** [comment]
![9D8D8B51-3056-4849-857B-1F1070C0A2F5](https://user-images.githubusercontent.com/45984899/169103885-8f361a93-7b88-4acf-8a18-3feb48ab0bc1.png)

**Comment by hg0428** [comment]
> Hi. These are 2 different issues. For the second one, can you provide the error message for me to take a look at?

How is it 2 different issues?
Its node.js not working, thats 1 issue.
BTW, its the same error message in every case.

**Comment by bummoblizard** [comment]
Can you show me the error message 'with projects that have much more than a simple hello world'? The error messages might look similar but might provide me with more information to look into.

**Comment by hg0428** [comment]
> Can you show me the error message 'with projects that have much more than a simple hello world'? The error messages might look similar but might provide me with more information to look into.
Here:
![image](https://user-images.githubusercontent.com/45984899/169165553-9fc588c0-b019-4ff6-b513-c7d3b3348b97.jpeg)

**Comment by hg0428** [comment]
> > Can you show me the error message 'with projects that have much more than a simple hello world'? The error messages might look similar but might provide me with more information to look into.
> 
> Here:
> ![image](https://user-images.githubusercontent.com/45984899/169165553-9fc588c0-b019-4ff6-b513-c7d3b3348b97.jpeg)

That's for when I try to use express.js.
