### ISSUE TITLE
左下角的版本控制分支和右下角的编码格式错位

### ISSUE THREAD

**Issue by SPTAU** [thebaselab/codeapp#46]
即左下角的master和右下角的utf-8高出底边栏一截
iPad2020 Pro 11英寸
版本1.2.0build11
iPadOS 14.1

**Comment by bummoblizard** [comment]
你好，请问可以提供截图吗

**Comment by SPTAU** [comment]
![Uploading D37915D9-AABE-41CE-AC88-9AA48A917BBE.png…]()

**Comment by SPTAU** [comment]
![558C2BFD-C82B-4DC2-AA6F-6A3ACB44FFFB](https://user-images.githubusercontent.com/46211051/111118328-991e5f00-85a3-11eb-96f2-765b419e4247.png)

**Comment by bummoblizard** [comment]
关于这个应该是iOS的问题，更新到iPadOS 14.4即可解决。

**Comment by SPTAU** [comment]
啊，版本说错了，是14.4.1

**Comment by SPTAU** [comment]
![995ABE78-3893-46D7-B95F-960F118F86C3](https://user-images.githubusercontent.com/46211051/111119254-ddf6c580-85a4-11eb-913a-142329c20ec8.png)

**Comment by bummoblizard** [comment]
好的我会研究一下，因为调试在iPad 8上没有这个问题

感谢你的回报。

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp-source/commit/21ad359595d19b490a72654c8560091f5feb8650
