### ISSUE TITLE
Shrinked working area with external keyboard connected

### ISSUE THREAD

**Issue by tkantor81** [thebaselab/codeapp#469]
Hello, I have connected the external keyboard. When I am typing, the screen is not the full screen. The bottom language bar shrinks the working area.
I have the iPad with the latest iPadOS.

![IMG_0333](https://user-images.githubusercontent.com/6500956/170819358-9e3a7ea4-d8c3-4d87-815c-a48d8b1748df.jpeg)

**Comment by bummoblizard** [comment]
Hi. You can disable this in iOS settings > general > keyboard > shortcuts.

**Comment by tkantor81** [comment]
Thank you for your tip, anyway Textastic works fine with it enabled :) I am writing code multi language so I would like to have it enabled.

Odesláno z iPadu

> 28. 5. 2022 v 12:08, Ken Chung ***@***.***>:
> 
> ﻿
> Hi. You can disable this in iOS settings > general > keyboard > shortcuts.
>

**Comment by tkantor81** [comment]
Hello, thank you for information, anyway Textastic works fine with it enabled :) I am writing code multi language so I would like to have it enabled.

Odesláno z iPadu

> 28. 5. 2022 v 12:08, Ken Chung ***@***.***>:
> 
> ﻿
> Hi. You can disable this in iOS settings > general > keyboard > shortcuts.
>

**Comment by bummoblizard** [comment]
I see! I’ll see how I can disable it from the app.
