### ISSUE TITLE
按回车键无法自动缩进 (Python)

### ISSUE THREAD

**Issue by segeral** [thebaselab/codeapp#47]
在py文件中，输入for循环后按回车键没有缩进

**Comment by segeral** [comment]
![image](https://user-images.githubusercontent.com/54263609/111164186-c9ccbb80-85d8-11eb-9eb6-5f196a9442b1.jpeg)

**Comment by bummoblizard** [comment]
I can confirm this. It will be fixed in the next release.

**Comment by segeral** [comment]
> I can confirm this. It will be fixed in the next release.

这个不止for循环，还有其他的命令也会出现这种情况，希望能在下一个版本尽快修复

**Comment by bummoblizard** [comment]
Fixed in TestFlight build.
