### ISSUE TITLE
Minor issue with theme dialog formatting

### ISSUE THREAD

**Issue by tkantor81** [thebaselab/codeapp#470]
![IMG_0334](https://user-images.githubusercontent.com/6500956/170839107-0264b664-3342-4089-a164-6b6ffcf6b705.jpeg)

**Comment by bummoblizard** [comment]
Thank you for reporting this. Which iOS version are you on? This might be caused by iOS updates.

**Comment by tkantor81** [comment]
15.5

**Comment by bummoblizard** [comment]
> 15.5

I can confirm this.

**Comment by tkantor81** [comment]
Latest iPadOS version 15.5 on iPad Air 2022 11”.

Odesláno z iPadu
