### ISSUE TITLE
Drag and drop files & Multiple windows of Code App

### ISSUE THREAD

**Issue by hg0428** [thebaselab/codeapp#473]
I would love to be able to drag and drop files into folders, and  stuff like that.

I would also love if I could open multiple windows of Code App like you can with Safari. I have come across multiple times where I attempted to do it and it doesn't work, this would be a great feature to have.

**Comment by hg0428** [comment]
By the way, I think you may need a team to work on this many bug fixes and enhancements

**Comment by bummoblizard** [comment]
> By the way, I think you may need a team to work on this many bug fixes and enhancements, instead of just you.
> This app is incredible though.

Thank you! I'm currently on my Summer break so I will be able to dedicate more time on this.

**Comment by hg0428** [comment]
> Thank you! I'm currently on my Summer break so I will be able to dedicate more time on this.

Thats great to hear.

When I found this ide, I could finally stop developing my ide.
You have done a great job on this. 

Thanks for making this so that we didn't have to.

**Comment by hg0428** [comment]
> > By the way, I think you may need a team to work on this many bug fixes and enhancements, instead of just you.
> > This app is incredible though.
> 
> Thank you! I'm currently on my Summer break so I will be able to dedicate more time on this.

I was making an ide before I found Code App.
Your's is way better though.

Mine couldn't run code, and it crashed when you attempted to drag and drop folders, but files could be dragged.

It had custom themes and editor preferences.
It had custom font weight, custom letter spacing, and other settings, like minimap, font ligatures, and line numbers.
You could not only code your own themes but it also had a theme builder.
It had a console, but the console didn't do much and you couldn't type commands into it, I was planning to add basic commands though.
I was in the middle of making plugins when I stopped development.


So, mine had some cool features, but it also couldn't run code or anything.

**Comment by bummoblizard** [comment]
These features are all now supported.
