### ISSUE TITLE
Coding on ipad with keyboard. Cannot copy&paste

### ISSUE THREAD

**Issue by Peiwvy** [thebaselab/codeapp#475]

**Comment by Peiwvy** [comment]
Under version 1.3.3 Build87, with iPad version 15.5.
I cannot use cmd+c to copy words and cmd+v to paste words, but it works well on other APP . it seems some conflicts on it.
PS: I use the default keyboard shortcuts.

**Comment by hg0428** [comment]
I have this problem all the time, just restart the app. When you restart it, it will crash, then just restart it again and it will work that time.

**Comment by Peiwvy** [comment]
I’m sorry that i don’t find where to restart the app. I noticed that there have a button called “Reset all settings (清除所有设置)” , and touched it to rest all settings, but which makes no inflvence to my problem.

**Comment by CoolOllie2** [comment]
Close the app and swipe it out in the apple app switcher, and reopen it.

**Comment by hg0428** [comment]
> I’m sorry that i don’t find where to restart the app. I noticed that there have a button called “Reset all settings (清除所有设置)” , and touched it to rest all settings, but which makes no inflvence to my problem. 

Yes, just close the app and swipe out as stated in the above comment
