### ISSUE TITLE
Git Clone Error

### ISSUE THREAD

**Issue by 2902208038** [thebaselab/codeapp#487]
I'm trying to clone my project from github to CodeApp, I notice that CodeApp could clone project by URL just like VSCode, but it report an error 
```
could not find appropriate mechanism for credentials
```
 when I cloning, so I wonder how can I successfully clone my project to CodeApp?

**Comment by bummoblizard** [comment]
Did you set the correct credentials in the settings page? You'll need to create a personal access token in GitHub.

**Comment by 2902208038** [comment]
> 是否在设置页面中设置了正确的凭据？需要在 GitHub 中创建个人访问令牌。

Thanks a lot, I create a personal access token and set it to CodeApp, it works well now.
