### ISSUE TITLE
SFTP Issue

### ISSUE THREAD

**Issue by UntrustedTech** [thebaselab/codeapp#491]
I Keep trying to connect to my SFTP Server and edit som files, but it wont connect, i keep getting a message stating "ERROR", but when i connect to my FTP server it works fine, not sure whats going on.

**Comment by bummoblizard** [comment]
Hi. Can you try it with the TestFlight version and see if it’s fixed? The
link is in readme.md.

**Comment by UntrustedTech** [comment]
Hey, just close this issue, i figured out the Issue, it wasn't the application that was the issue, as i tried using multiple public SFTP servers to connect to and all worked. It was the host of the network that i was trying to connect to. Ill still download the TestFlight version since i really enjoy using this Code editor compared to other ones out there have have less features than this one.
