### ISSUE TITLE
Cannot perform text selection with touch

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#5]
Currently, Monaco Editor, thus Code App does not support touch interaction for text selection. It's a bummer for users who wants to copy text without a physical mouse or keyboard.

**Possible solution:** Mimic native text selection by conforming the editor view to `UITextInput` protocol.

**Current workaround:** Select text by sliding your finger across the line numbers gutter area, then use the buttons on the keyboard toolbars to copy and paste text.

**Comment by Lukas-Batema** [comment]
> ...**Current workaround:** Select text by sliding your finger across the line numbers gutter area, then use the buttons on the keyboard toolbars to copy and paste text.

Could you give me some more detailed info on how to do this, I am having a troubling time doing so. Thanks!

**Comment by bummoblizard** [comment]
This does not work anymore as in the new version of Monaco Editor. I understand it could be really troubling for touch screen users, especially iPhones users.

**Comment by Lukas-Batema** [comment]
> This does not work anymore as in the new version of Monaco Editor. I understand it could be really troubling for touch screen users, especially iPhones users.

I thankfully have many keyboards and mice, but I usually prefer to programme on the go, as I ride the bus to school, as I am still in High School. So that means I use my iPhone/iPad to programme OFFLINE.

**Comment by bummoblizard** [comment]
Duplicate #20
