### ISSUE TITLE
Terminal issue on iPhone

### ISSUE THREAD

**Issue by gavinggordon** [thebaselab/codeapp#50]
Terminal doesn't seem to be working on my iPhone 11 Pro Max. When I tap on the tab, labelled Terminal, then tap again in the content area therein, in order to invoke the keyboard used to type commands into terminal, nothing happens. The keyboard is not invoked, and thus nothing can be typed into the terminal.

**Comment by gavinggordon** [comment]
> Terminal doesn't seem to be working on my iPhone 11 Pro Max. When I tap on the tab, labelled Terminal, then tap again in the content area therein, in order to invoke the keyboard used to type commands into terminal, nothing happens. The keyboard is not invoked, and thus nothing can be typed into the terminal.

Nevermind. I updatee the app, and now the issue appears to have been resolved.

**Comment by bummoblizard** [comment]
It was a bug in version 1.2.0 and it's now resolved.
