### ISSUE TITLE
Overflow in the terminal

### ISSUE THREAD

**Issue by JoeRourke123** [thebaselab/codeapp#51]
When the terminal is open there is no way (or it appears that way to me) to scroll down to bottom of the content if it goes off the screen. Either scrollbars or a "clear" command on the terminal would be greatly appreciated!

**Comment by JoeRourke123** [comment]
Nevermind, after clicking again on the terminal window and pressing enter I was scrolled to the bottom. However, a clear command would still be very helpful!

**Comment by bummoblizard** [comment]
Hello. You can use Command+K to clear the terminal if you’re using a physical keyboard. If not, you can press the trash can button.

**Comment by JoeRourke123** [comment]
Ah yes that works - thank you very much.
