### ISSUE TITLE
[SOLVED] Commit problem

### ISSUE THREAD

**Issue by ArturSultanov** [thebaselab/codeapp#514]
Hello,

I cloned GitHub rep using HTTPS. Than I went to folder and created a new file (almost empty). I chose this new file at the “staged changes”, wrote a message and push a commit button. I’ve checked my GitHub rep and there is no new file I pushed though “Code App”. As Authentication (in the app setting) I use the same user name and password as for GitHub account.

https://user-images.githubusercontent.com/95172163/177386619-7ac7a87f-bc68-4743-a1c0-d2944b39f14f.mp4

**Comment by bummoblizard** [comment]
Hi. After committing, you'll need to press the push button.

![image](https://user-images.githubusercontent.com/38398443/177389203-462f3eb2-c490-447e-bae8-a335c8fbb5b7.png)

**Comment by ArturSultanov** [comment]
> Hi. After committing, you'll need to press the push button.
> 
> ![image](https://user-images.githubusercontent.com/38398443/177389203-462f3eb2-c490-447e-bae8-a335c8fbb5b7.pn
![IMG_0191](https://user-images.githubusercontent.com/95172163/177391776-a24d3c18-5fa1-41bc-82bf-7f9af0bf3b9e.jpeg)
g)

Thank you, it helped. Sorry, I am a beginner with a git. But actually I have a new problem :)
App writes “too many redirects or authentication replays”.

**Comment by ArturSultanov** [comment]
> > Hi. After committing, you'll need to press the push button.
> > ![image](https://user-images.githubusercontent.com/38398443/177389203-462f3eb2-c490-447e-bae8-a335c8fbb5b7.pn
> > ![IMG_0191](https://user-images.githubusercontent.com/95172163/177391776-a24d3c18-5fa1-41bc-82bf-7f9af0bf3b9e.jpeg)
> > g)
> 
> Thank you, it helped. Sorry, I am a beginner with a git. But actually I have a new problem :) App writes “too many redirects or authentication replays”.

UPD: I regenerated token and it works fine. Thank you so much!

**Comment by bummoblizard** [comment]
You need to use a personal access token instead of the password. See
https://code.thebaselab.com/extras/frequently-asked-questions

**Comment by ArturSultanov** [comment]
> You need to use a personal access token instead of the password. See https://code.thebaselab.com/extras/frequently-asked-questions
> […](#)

I generated token and it works perfectly. Thank you so much for you help!
