### ISSUE TITLE
Remote connection server function

### ISSUE THREAD

**Issue by Xiong-JiaHao** [thebaselab/codeapp#521]
Sometimes the app will flash back when connecting to the server remotely. 
And I hope to add a note display of the server. Thank you.

I wish you every success in your work.

**Comment by bummoblizard** [comment]
Can you let me know your server's setup? (OS / SSH software and version)

**Comment by ginshin** [comment]
Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1011-oracle aarch64)

**Comment by bummoblizard** [comment]
This is fixed in the latest release.
