### ISSUE TITLE
Unable to load custom loaded font

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#527]
The built in font picker can't show user defined fonts.

**Comment by tomasyang2020** [comment]
If the Fira Code font is installed via the Apple Configuration Profile, it will not be possible to select this font via the font picker in the app. This is also the case if you install the Apple Configuration Profile after selecting the font, in which case the selected Fira Code font will render normally.(App Store Version 1.3.4 Build 94,iOS 15.6)

**Comment by bummoblizard** [comment]
> If the Fira Code font is installed via the Apple Configuration Profile, it will not be possible to select this font via the font picker in the app. This is also the case if you install the Apple Configuration Profile after selecting the font, in which case the selected Fira Code font will render normally.(App Store Version 1.3.4 Build 94,iOS 15.6)

Fira Code is embedded in the app. It should show up whether you installed it or not.

**Comment by excitedplus1s** [comment]
> 
I can repro 
Before I install the Fira font
![8194867D-B5AE-4A32-B2DC-E4DE5F43EDF5](https://user-images.githubusercontent.com/81917660/184099418-88181a0e-ff8a-4396-b5a5-4812218e3c5c.png)

After I install the Fira font
![DDC14535-2FB9-425E-855A-F91ED76BC896](https://user-images.githubusercontent.com/81917660/184099608-1a863db2-c75b-4209-b581-7911469c8370.png)

**Comment by excitedplus1s** [comment]
> I can repro Before I install the Fira font ![8194867D-B5AE-4A32-B2DC-E4DE5F43EDF5](https://user-images.githubusercontent.com/81917660/184099418-88181a0e-ff8a-4396-b5a5-4812218e3c5c.png)
> 
> After I install the Fira font ![DDC14535-2FB9-425E-855A-F91ED76BC896](https://user-images.githubusercontent.com/81917660/184099608-1a863db2-c75b-4209-b581-7911469c8370.png)



> I can repro Before I install the Fira font ![8194867D-B5AE-4A32-B2DC-E4DE5F43EDF5](https://user-images.githubusercontent.com/81917660/184099418-88181a0e-ff8a-4396-b5a5-4812218e3c5c.png)
> 
> After I install the Fira font ![DDC14535-2FB9-425E-855A-F91ED76BC896](https://user-images.githubusercontent.com/81917660/184099608-1a863db2-c75b-4209-b581-7911469c8370.png)

Apple Configuration Profile 
https://gist.github.com/excitedplus1s/25fe51c7060ce81a5bf0f866afa97a9b

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp/issues/1004.
