### ISSUE TITLE
Symbolic links in sftp are not loading

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#533]

**Comment by Sergong** [comment]
I can confirm that this is the case on iPadOS 16 as well…

**Comment by wyllgao** [comment]
Hi,

For projects in which data and code are stored in different paths, it is a critical foundational feature, and we hope the bug can be fixed soon.

**Comment by bummoblizard** [comment]
> Hi,
> 
> 
> 
> For projects in which data and code are stored in different paths, it is a critical foundational feature, and we hope the bug can be fixed soon.

Thanks for the heads up. I will work on this next week.

**Comment by bummoblizard** [comment]
This should be fixed in the latest TestFlight build. See https://github.com/thebaselab/NMSSH/commit/68d4728ba2e284c587fa62bbfb349b5d43a05109.

**Comment by bummoblizard** [comment]
TODO: Also resolve symlink directories

**Comment by bummoblizard** [comment]
> TODO: Also resolve symlink directories

Fixed in https://github.com/thebaselab/codeapp/commit/c527110d515c30df44d582b28ea405eb119e1a7d. This feature will be released on App Store shortly in 1.5.2.
