### ISSUE TITLE
git support when working with remote repository

### ISSUE THREAD

**Issue by bastian1209** [thebaselab/codeapp#544]
Git control (source control) only supports for local repositories in Ipad now.
I usually work with remote repository using ssh connection, but it is not available to watch version changes.
Supporting git for remote repository would be very nice feature for this app.
Thank you!

**Comment by bummoblizard** [comment]
That's a great idea and I might be able to implement it. For now, you can use the command line git.

**Comment by bummoblizard** [comment]
Closing in favour of https://github.com/thebaselab/codeapp/issues/886
