### ISSUE TITLE
Build error this undefined symbol...

### ISSUE THREAD

**Issue by mkinitcpio** [thebaselab/codeapp#549]
Hello!
I have an issue with compile to simulator from main branch: 

<img width="523" alt="Screen Shot 2022-08-21 at 8 32 40 PM" src="https://user-images.githubusercontent.com/12542028/185803653-34f064d9-a380-406f-92f7-7d0ebe6b0736.png">
<img width="1115" alt="Screen Shot 2022-08-21 at 8 32 45 PM" src="https://user-images.githubusercontent.com/12542028/185803662-0b04d45f-8af0-4fa6-93b2-0d6cc7fd2af0.png">

**Comment by bummoblizard** [comment]
In SwiftGit/Package.swift, replace the package url of clibgit2 to https://github.com/light-tech/Clibgit2. Our fork uses a arm64 architecture for M1 machines.

**Comment by mkinitcpio** [comment]
Ah many thanks!

**Comment by bummoblizard** [comment]
Updated Clibgit2 to a universal binary. Building for x86-64 simulator should work now.
