### ISSUE TITLE
文件新建/重命名bug

### ISSUE THREAD

**Issue by Heming-Zhong** [thebaselab/codeapp#55]
在新建文件时文件名包含中文会导致得到的文件名异常。

另外，在给文件重命名时，如果使用简体中文输入法，在输入一次中文后便无法继续输入，而且完成重命名时程序有可能会出现闪退。

复现：
1. 在新建文件时用简体中文输入法输入任意中文；
2. 文件重命名，在重命名输入框中输入任意中文，并且中间至少间隔一次；

**Comment by bummoblizard** [comment]
你好，我能够确认这个问题￼￼。

在更新退出前，￼你可以使用终端命令￼`rm 旧档名 新档名￼￼`以更改名字￼。

**Comment by bummoblizard** [comment]
Fixed in TestFlight build.
