### ISSUE TITLE
[Unconfirm Bug] asyncpg can't install

### ISSUE THREAD

**Issue by staciax** [thebaselab/codeapp#563]
pip install asyncpg

![image](https://user-images.githubusercontent.com/69411527/188533841-120bfbc1-4997-41e2-9060-d11f548f6e49.png)

**Comment by bummoblizard** [comment]
Hi. The error message suggests this package contains native components that cannot be compiled or installed on an iOS device. (It's trying to call clang) Consider alternative packages.

**Comment by staciax** [comment]
Asyncpg not support linux/aarch64
