### ISSUE TITLE
Add Vim editor

### ISSUE THREAD

**Issue by symjie520** [thebaselab/codeapp#565]
Hope to add Vim Editor support!  Thanks !

**Comment by weykon** [comment]
YES !!!
Omitted touchpad and efficient coding with Vim are the ultimate in convenient mobile coding.

**Comment by bummoblizard** [comment]
@weykon I will work on it this today.

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/commit/60eb17d1a17421fa865f8e90b7083da83e3acc8f adds support for vim mode without ex commands and search. I will continue to work on it to support these features.
