### ISSUE TITLE
App Crashes On ios16

### ISSUE THREAD

**Issue by xsantosx420** [thebaselab/codeapp#572]
ipad pro 10.5 (2017)
ios 16.1

**Comment by bummoblizard** [comment]
Does it crash immediately upon opening? Can you try rebooting the device?

**Comment by xsantosx420** [comment]
Yes, it does crash immediately upon opening. Yes,I've tried reboot and reinstall this app several times but it still doesn't work.

**Comment by xsantosx420** [comment]
> Does it crash immediately upon opening? You might also try to reboot the device or reinstall the app.
> 

Yes, it does crash immediately upon opening. Yes,I've tried reboot and reinstall this app several times but it still doesn't work.

**Comment by mrkhachaturov** [comment]
ipad os 16  app crashes while trying to connect by sftp

**Comment by mrkhachaturov** [comment]
![image](https://user-images.githubusercontent.com/105451445/190031690-f9a7b904-8c1b-4a66-8eca-10712457a9f2.jpeg)
Now it stops crashing, but still can't connect by sftp - unknown error

**Comment by Yansongsongsong** [comment]
same here.

iPad model: iPad pro 11-inch 3rd generation
iPadOS version: 16.1(20B82)

how to reproduce:
1. download the ipa file https://github.com/thebaselab/codeapp/releases/tag/1.3.6 , and self signed it again with personal account.
2. install it on device
3. open it and it will crash directly when open it

**Comment by bummoblizard** [comment]
> same here.
> 
> 
> 
> iPad model: iPad pro 11-inch 3rd generation
> 
> iPadOS version: 16.1(20B82)
> 
> 
> 
> how to reproduce:
> 
> 1. download the ipa file https://github.com/thebaselab/codeapp/releases/tag/1.3.6 , and self signed it again with personal account.
> 
> 2. install it on device
> 
> 3. open it and it will crash directly when open it

Does the TestFlight version work? https://testflight.apple.com/join/EgZ8sE2P

**Comment by Yansongsongsong** [comment]
> 

`the beta is full`. i am afraid i can not download the testflight version

**Comment by Yansongsongsong** [comment]
> > same here.
> > iPad model: iPad pro 11-inch 3rd generation
> > iPadOS version: 16.1(20B82)
> > how to reproduce:
> > 
> > 1. download the ipa file https://github.com/thebaselab/codeapp/releases/tag/1.3.6 , and self signed it again with personal account.
> > 2. install it on device
> > 3. open it and it will crash directly when open it
> 
> Does the TestFlight version work? https://testflight.apple.com/join/EgZ8sE2P

the beta is full. i am afraid i can not download the testflight version. @bummoblizard

**Comment by bummoblizard** [comment]
@Yansongsongsong I opened up more slots.
