### ISSUE TITLE
Svelte Syntax Highlighting

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#573]
Currently, `*.svelte` files do not have syntax highlighting. I think (and many others that I have talked to and know) that Svelte and SvelteKit are a new-ish out and coming HTML and JS framework. It (for the most part) is HTML and JS syntax, so it shouldn't be too hard to implement. Thanks!

**Comment by bummoblizard** [comment]
Reference: https://github.com/sveltejs/language-tools

**Comment by Lukas-Batema** [comment]
So, it's more than just modifying expiating configurations, I see. Is there still any way to get this to work?

**Comment by bummoblizard** [comment]
> So, it's more than just modifying existing configurations, I see. Is there still any way to get this to work?

The usual way to get it work is extracting relevant files from existing vscode extension. For example, these files contains the syntax definition: https://github.com/thebaselab/codeapp/tree/main/CodeApp/monaco-textmate.bundle/grammars

**Comment by Lukas-Batema** [comment]
Ah, okay.

**Comment by bummoblizard** [comment]
![Simulator Screen Shot - iPad Air (5th generation) - 2022-09-19 at 20 46 54](https://user-images.githubusercontent.com/38398443/191020556-91ac0ee8-c3b0-4b38-a101-55feddd997fc.png)
