### ISSUE TITLE
Add option to specify remote path while connection start

### ISSUE THREAD

**Issue by kiochan** [thebaselab/codeapp#583]
Hello,

It will be better when add a option to set path of remote workspace.

Every time when I connect the remote server, it always route into root directory, that make it hard to find the right repository and work with it.
This also makes the repository better version managed.

**Comment by PengJuntong** [comment]
totally agree with kiochan
willing to see that new feature

**Comment by bummoblizard** [comment]
That's a great idea. I will try to implement this in the coming release.

**Comment by scripzero** [comment]
yeahh i want that tool
