### ISSUE TITLE
text selection

### ISSUE THREAD

**Issue by JuntongPeng** [thebaselab/codeapp#584]
still find it hard to use the cursor to select specific text, only can select a single word by a double click.

maybe a bug on ipadOS16?

**Comment by C4ntor** [comment]
As you can see from the first screen record (in attachments) when coding in the editor you cannot select (or deselect) single pieces of code/text/ or single characters, as you would do in any IDE (or even in a simple text editor like Apple Note) and this is just frustrating! Currently you can only select (with a double tap/click on it) a single keyword of the language. I let you another screen record in the attachments to better understand what I’m saying. Please fix this ASAP

Uploading 197222623-c77d0940-1aa7-4

https://user-images.githubusercontent.com/116038756/197331521-df92cdb7-2afc-495d-a73f-1313b025cf4f.mp4

150-b820-8fde870fc94c.mp4…
