### ISSUE TITLE
目录层级多的时候，目录显示不全

### ISSUE THREAD

**Issue by Gavin-J** [thebaselab/codeapp#585]
目录层级多的时候，目录树窗口不能左右滚动，深层级的目录无法显示

![4EEBEDE5-A895-436F-A1EE-29BB0FB47203](https://user-images.githubusercontent.com/12963221/192321285-d947c64b-b6d3-4f7a-939d-f3ab46db673e.jpeg)

**Comment by bummoblizard** [comment]
It is now possible to expand the sidebar by dragging it.
