### ISSUE TITLE
Can't find files inside my repository

### ISSUE THREAD

**Issue by ghost** [thebaselab/codeapp#587]
I followed all the steps of the code app documentation to clone a repository form github. When I do it though I can't see any of the files in my repository, if I create a new file "the source control" on the side bar refreshes and now I can see only the files created on my Ipad.
I can commit only the new/modified files from the ipad and when I try to commit the "push" option isn't available.
I tried restarting my IPAD, after the restart i found a .git file in my project, in my repository I only have a text file though.

**Comment by bummoblizard** [comment]
Switch to the files tab to your files. That’s the first item in the side
bar. If you are using an iPhone, select files from the drop down menu at
the top indicated by three dots.

**Comment by hg0428** [comment]
I can't find files period. I have to close the app and reopen it to see new files.
If I create and save a file, it doesn't show up until I close the app and reopen it

**Comment by bummoblizard** [comment]
> I can't find files period. I have to close the app and reopen it to see new files.
> If I create and save a file, it doesn't show up until I close the app and reopen it

Again, this might be related to compatibility / issues with iPadOS 16.1 betas. I don't see these problems on 16.0.

**Comment by hg0428** [comment]
> > I can't find files period. I have to close the app and reopen it to see new files.
> 
> > If I create and save a file, it doesn't show up until I close the app and reopen it
> 
> 
> 
> Again, this might be related to compatibility / issues with iPadOS 16.1 betas. I don't see these problems on 16.0.

There is no iPadOS 16.0, they are skipping right to 16.1 for release since release was delayed.

**Comment by RLungarella13** [comment]
I unistalled and created a new repository and it worked
