### ISSUE TITLE
Almost constant crashing on iPadOS 16.1 beta

### ISSUE THREAD

**Issue by hg0428** [thebaselab/codeapp#588]
It randomly crashes. I can be editing code or installing a package, it just randomly crashes.

It just randomly crashes and I can't do anything with the app for fear it could crash at any moment and my edits be lost.

And when it crashes, to restores my workspace to how it was a few days ago. Its not saving the workspace.

This needs to be fixed.
I'm on iPadOS 16.1 Beta

**Comment by bummoblizard** [comment]
The beta versions of iPadOS aren't particularly stable and I haven't tested the app on 16.1 yet. Not to mention 16.0 isn't released too.

I recommend switching back to iPadOS 15 if you want a better stability.

**Comment by hg0428** [comment]
> The beta versions of iPadOS aren't particularly stable and I haven't tested the app on 16.1 yet. Not to mention 16.0 isn't released too.
> 
> 
> 
> I recommend switching back to iPadOS 15 if you want a better stability.

Well, iPadOS 16.1 will be released in only a few weeks anyways.

I can use replit while I'm waiting.
