### ISSUE TITLE
Can’t install pandas. Is this expected?

### ISSUE THREAD

**Issue by carlossierra311** [thebaselab/codeapp#59]
I am trying to run a small project that uses pandas, and after hitting run, codeapp diligently tells me that pandas isn't installed. So I then try:
`pip install pandas`

And I get a message suggesting me to update pip's installed version, so I proceed with:
`python -m pip install –upgrade pip `

This works fine, and pip's latest version in installed. I try to install pandas again, and now I get a cascading attempt to do so with older pandas versions, failing each time with the following numpy related message:
![image](https://user-images.githubusercontent.com/23511373/112100733-95767380-8b73-11eb-8855-f459251df553.png)

Can you please provide some guidance on how to proceed?

Thanks

**Comment by bummoblizard** [comment]
Hello. Yes this is expected. Pip install does not support modules with native components due to iOS constraints. 

With that being said, it's possible for me to include pandas as a built in module and I do plan to include it in future updates.

**Comment by carlossierra311** [comment]
Ok. Thank you Ken.

**Comment by bummoblizard** [comment]
Added in the latest build. Will be available on App Store very soon.
