### ISSUE TITLE
Java returns error:cannot find symbol

### ISSUE THREAD

**Issue by RLungarella13** [thebaselab/codeapp#590]
I have two java files in the same folder, one has the main class and the other has a custom class. When I run the java file with the main class it return me "error: cannot find symbol", and it referes to the custom class i jave on the other java file. I tried to compile it with visual studio code and it works fine, but when i try to run it on my IPAD it doesn't work. I tried using "import" but it didn't work.

**Comment by bummoblizard** [comment]
Multi file compiling are not supported through remote execution.

**Comment by C4ntor** [comment]
> Multi file compiling are not supported through remote execution.

Please, if possible try to find soon a workaround to this problem, because for me multi file compiling is essential in Java, and I would really love this feature on the CodeApp.

**Comment by bummoblizard** [comment]
You can now use java and javac to run Java programs locally in the latest build. Multi-file compiling should work as expected in a desktop environment.
