### ISSUE TITLE
(Version:1.3.5 Build 111)Failed loading clang++ from clang.framework

### ISSUE THREAD

**Issue by tarada** [thebaselab/codeapp#592]
The same problem appears again. This is about my local c++. Now I have to use the remote terminal and it's responding for a long time.
![00287132-B4E2-4B3E-978B-6915050B83BD](https://user-images.githubusercontent.com/27858484/193404442-ee412c47-9ff7-44c6-9e54-c5e3fb5021c7.jpeg)

**Comment by bummoblizard** [comment]
Try to reboot your device.

**Comment by tarada** [comment]
solved. Thank u

**Comment by tarada** [comment]
> Try to reboot your device.

Solved. Thank u
