### ISSUE TITLE
comment fermer un repository 

### ISSUE THREAD

**Issue by baudrysouvignet** [thebaselab/codeapp#595]
Bonjour,

J'ai connecté un repository github avec la partie "source control"
Mais je n'arrive pas à en ouvrir un deuxième, ou à fermer le fichier.

Merci de me dire si quelqu'un a une solution.

**Comment by bummoblizard** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/38398443/193457715-39dbeac9-6754-44f9-9ce1-6bbc9f2986ce.png">

Select a new folder by clicking this button. Selecting On My iPad > Code brings you back to the root folder.

**Comment by baudrysouvignet** [comment]
thank's 
I am so stupid
