### ISSUE TITLE
How to use PHP

### ISSUE THREAD

**Issue by baudrysouvignet** [thebaselab/codeapp#596]
Hello, 

I want to run my website in PHP. I don't find how.
Can you help me to run my php program in a web page ?

Thank's
b.S

**Comment by bummoblizard** [comment]
https://code.thebaselab.com/extras/frequently-asked-questions#local-runtime

> My PHP code is not running in the web privew.
> The default web preview only serves static documents and does not run PHP code. To run a local PHP development server, run php -S localhost:8000 in the terminal and visit localhost:8000 in Safari or other browsers.
