### ISSUE TITLE
Pip and extensions

### ISSUE THREAD

**Issue by TheSeeven** [thebaselab/codeapp#599]
While extensions are not really that big of a deal, I would love to be able to install libraries in order to extend my python

**Comment by bummoblizard** [comment]
You can do pip install in the terminal.

**Comment by TheSeeven** [comment]
I receive this when i try:

Perianu Leon
________________________________

**Comment by bummoblizard** [comment]
@TheSeeven I can't see the error.

**Comment by TheSeeven** [comment]
![image](https://user-images.githubusercontent.com/65567387/194303931-04d4d834-ab58-4dcd-92be-8659fcead845.png)

**Comment by bummoblizard** [comment]
What module are you trying to install?

**Comment by TheSeeven** [comment]
scipy

**Comment by TheSeeven** [comment]
Hello,
I am comment back for the installing module part.
I am trying to install sklearn but I get a writing error, so technically I cannot install the desired module for my needs.
