### ISSUE TITLE
Optimise the interface on iPhone

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#6]
Code App uses VS Code as a design template. While the interface is clean and efficient when used on an iPad, it's not really optimised for iPhones where screen space is limited. We could either drop support for iPhones, or come up with optimisations or a whole new interface for smaller screens.

**Comment by Lukas-Batema** [comment]
> Code App uses VS Code as a design template. While the interface is clean and efficient when used on an iPad, it's not really optimised for iPhones where screen space is limited. We could either drop support for iPhones, or come up with optimisations or a whole new interface for smaller screens.

I wouldn’t drop support, because this is the best and basically only app that does everything I actually need, for free. I would obviously suggest to use media cues to fix layout issue.

**Comment by bummoblizard** [comment]
Here's are some screenshots of the improved interface.

![IMG_4F2931FEA542-1](https://user-images.githubusercontent.com/38398443/118389963-1a0add00-b65f-11eb-9564-e3b8386db4d9.jpeg)
![IMG_DBE2B3CDDD4F-1](https://user-images.githubusercontent.com/38398443/118389971-2858f900-b65f-11eb-9c25-a544d0a6fe02.jpeg)

**Comment by Lukas-Batema** [comment]
That looks nice, I love the sidebar that slides to the right. Maybe make it customizable, from the right to left, or left to right.

> Here's are some screenshots of the improved interface.
> 
> ![IMG_4F2931FEA542-1](https://user-images.githubusercontent.com/38398443/118389963-1a0add00-b65f-11eb-9564-e3b8386db4d9.jpeg)
> ![IMG_DBE2B3CDDD4F-1](https://user-images.githubusercontent.com/38398443/118389971-2858f900-b65f-11eb-9c25-a544d0a6fe02.jpeg)
