### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by lennyesquivel** [thebaselab/codeapp#60]
This is an enhancement, it would be great to have Java 8 support with the runtime environment. I love the app so far and this is the only thing stopping me from using my iPad  as my main development machine.

**Comment by bummoblizard** [comment]
Hello. That’s a really great suggestion. It’s indeed possible to cross compile JDK for iOS.

Hopefully I will be able to include it in the near feature.

**Comment by bummoblizard** [comment]
Local Java is now available in the latest TestFlight build. You can use java and javac to run Java programs locally.

**Comment by lennyesquivel** [comment]
Thanks so much, really glad it could be done and that we can now use ipads
for java development, thank you all.
