### ISSUE TITLE
My app is ins German Language and I can’t change to English

### ISSUE THREAD

**Issue by guimaferreira** [thebaselab/codeapp#603]
I just downloaded the app, my iPad Pro default language is Brazilian Portuguese.
The app is in German, and I need to change to English, but I don’t have a clue on how to change, as I don’t understand German.

Is this a bug? Or someone can help me changing the language?

**Comment by bummoblizard** [comment]
I'm not sure how this happened but you can go to Settings App > Code App and select another language.

**Comment by guimaferreira** [comment]
@bummoblizard that worked, thanks!

An hypothesis I had was that as my main language (portuguese) the default language is being applied, and maybe the default is german.

**Comment by guimaferreira** [comment]
@bummoblizard  that worked, thanks!

An hypothesis I had was that as my main language (portuguese) the default language is being applied, and maybe the default is german.

**Comment by bummoblizard** [comment]
I’m not sure how this happened but you can go to Settings App > Code App
and select a new language there.
