### ISSUE TITLE
local Java (openJDK)

### ISSUE THREAD

**Issue by Bschoy** [thebaselab/codeapp#615]
Proposal: 

allow the download and usage of an openJDK version, to enable local Java support.
This is sure to appeal to a wide range of people who dislike being reliant on remote services / do not have access to the internet on the go.

**Comment by PalmaMichele** [comment]
Add support for java standard libraries, like java.util, because currently you cannot use a Scanner class (from the java.util library) for example to ask for an Input, because the Terminal will show you an error: "Exception in thread main java.util.NoSuchElementException  ...... at java.base/java.util.Scanner.nextInt(Scanner.java:2258)"

**Comment by C4ntor** [comment]
It would be great! Maybe even allowing multi file compiling (thanks to local java support)

**Comment by C4ntor** [comment]
> Proposal:
> 
> allow the download and usage of an openJDK version, to enable local Java support. This is sure to appeal to a wide range of people who dislike being reliant on remote services / do not have access to the internet on the go.

@bummoblizard would it be possible?

**Comment by bummoblizard** [comment]
> > Proposal:
> 
> > 
> 
> > allow the download and usage of an openJDK version, to enable local Java support. This is sure to appeal to a wide range of people who dislike being reliant on remote services / do not have access to the internet on the go.
> 
> 
> 
> @bummoblizard would it be possible?

Yes. But I haven't been able to do it.

**Comment by Bschoy** [comment]
Is it planned already or any updates?

**Comment by bummoblizard** [comment]
Added in https://github.com/thebaselab/codeapp/commit/39155744844ad472f0b79c714230a8691a7832bb.
