### ISSUE TITLE
Java: cannot use Scanner (from java.util)

### ISSUE THREAD

**Issue by C4ntor** [thebaselab/codeapp#616]
Currently you cannot use a Scanner class (from the java.util library) for example to ask for an Input (whatever the input type will be: String, int, double....) because the Terminal will show an error: "Exception in thread main java.util.NoSuchElementException ...... at java.base/java.util.Scanner.nextInt(Scanner.java:2258)" (first screenshot). This seems to happen only with the Scanner Class of java.util, because as you can see from the second screenshot, I tested other classes of java.util (Queue, LinkedList) and they work. 
![IMG_0085](https://user-images.githubusercontent.com/116038756/197189986-343dfe6c-c3a9-40fa-ae9c-2373134ae4c1.png)
![IMG_0086](https://user-images.githubusercontent.com/116038756/197190007-3b0c99d6-47e8-4a28-845f-df04307ff24d.jpeg)

**Comment by C4ntor** [comment]
> 

I don't understand how this question (explaining step by step the recursive algorithm to calculate the factorial of a number) could be related to my problem (the topic is that Scanner class doesn't work ). Anyway, here I let you the explanation that you asked for:  
_Keep in mind that the factorial of a number (n!) can be written as n*n-1*n-2.... so on until 1, or it can also be written as n* (n-1)!, also remember that by definition the factorial of 0 is equal to 1 (and the factorial can only be calculated for positive integers and zero) and this is the key concept behind the algorithm that you proposed._ That algorithm is **Recursive**, this means that it calls itself with simpler inputs each time, and returns the result for the current input by carrying out basic operations on the returned value for the smaller input. 
_(Indeed as you can see it calls it self over and over and over again, but on a smaller number each time, until the number on which it is called isn't zero, in that case you are in the Base Case and it "stops" the recursion, because as you know by definition the factorial of zero equals one)_
Imagine this as stairs,  a step is created at each call, and the previous call is "paused" until the next one has a result to return to the previous one.

_In the case of the factorial, the value is calculated as the number on which you want to calculate the factorial multiplied by the recursive call on the (number minus 1), therefore the method pauses and wait for the result of the factorial applied on that (number minus 1). 1) in order to continue, but the same mechanism is applied to the calculation of (number minus 1), so this in turn will be equal to the number that multiplies the factorial calculated on its predecessor (therefore n-1 * factorial of (n-1 -1), and so on .. until you reach the base case (when the number passed is zero) and in this case you will not call a recursive thing but instead you will return 1. Then each result is rolled back to the point that called the recursion ... and the factorial is calculated._

(I have written your code in VScode and also I have recorded a video-note that shows you all the steps, so that it can be more clear, you can see them in attachments). I hope I'm being clear.

https://user-images.githubusercontent.com/116038756/197592482-65faa61e-9b64-4cba-98dc-0b7b324a4ead.mp4

**Comment by C4ntor** [comment]
> Currently you cannot use a Scanner class (from the java.util library) for example to ask for an Input (whatever the input type will be: String, int, double....) because the Terminal will show an error: "Exception in thread main java.util.NoSuchElementException ...... at java.base/java.util.Scanner.nextInt(Scanner.java:2258)" (first screenshot). This seems to happen only with the Scanner Class of java.util, because as you can see from the second screenshot, I tested other classes of java.util (Queue, LinkedList) and they work.
> ![IMG_0085](https://user-images.githubusercontent.com/116038756/197189986-343dfe6c-c3a9-40fa-ae9c-2373134ae4c1.png)
> ![IMG_0086](https://user-images.githubusercontent.com/116038756/197190007-3b0c99d6-47e8-4a28-845f-df04307ff24d.jpeg)
@bummoblizard

**Comment by bummoblizard** [comment]
@C4ntor You need to fill in the inputs in the input tab before executing.

**Comment by C4ntor** [comment]
> @C4ntor You need to fill in the input
![IMG_0196](https://user-images.githubusercontent.com/116038756/205453898-9ee160e3-d0a9-4e0a-b2a8-f742d53b230e.png)
![IMG_0197](https://user-images.githubusercontent.com/116038756/205453907-c0bc9317-86fe-4bcc-aba1-00dc14eb7554.png)
![IMG_0198](https://user-images.githubusercontent.com/116038756/205453908-1f89e770-b23e-4bfc-a486-4476a4f111d4.png)

https://user-images.githubusercontent.com/116038756/205453909-57b90c68-96ce-4224-999f-f3d371bcc9e1.mp4

s in the input tab before executing.

Hello, thanks for your answer. This process of typing your inputs before executing the code is frustrating, and it doesn't seems to happen with other languages like Python (as you can see from video attachments below). Can you improve it also for Java? If the problems is related to the fact that Java runs remotely, please as already said add soon a local version of JDK to use.
