### ISSUE TITLE
xcode build failed

### ISSUE THREAD

**Issue by eli32-vlc** [thebaselab/codeapp#622]

**Comment by eli32-vlc** [comment]
I did install all the framework

![Screen Shot 2022-10-24 at 6 05 07 pm](https://user-images.githubusercontent.com/84105075/197479071-1901a8ee-e556-4320-80d0-cadec47d3751.jpg)


thanks so much for helping

**Comment by bummoblizard** [comment]
Can you show me the build errors?

**Comment by eli32-vlc** [comment]
![Screen Shot 2022-10-25 at 7 54 28 am](https://user-images.githubusercontent.com/84105075/197637284-f44f7273-67ae-4eb8-a4bd-b0076375b43d.jpg)

**Comment by eli32-vlc** [comment]
I did not change anything

**Comment by bummoblizard** [comment]
Try to reset the Swift Package cache. I believe the button is in top menu's File section.
