### ISSUE TITLE
Allow to view PDF files

### ISSUE THREAD

**Issue by konstantinkobs** [thebaselab/codeapp#624]
I want to work on a LaTeX project in the app. For this, opening the resulting PDF in a tab is useful to see if the (external) compilation was successful. Therefore, it would be useful to be able to open PDF files in the app. Currently, this is not possible.

**Comment by bummoblizard** [comment]
Added in https://github.com/thebaselab/codeapp/commit/bb70a7858a180e46264b758be7af44a9199abd93 :)
