### ISSUE TITLE
clone git 提示 clone error could not find appropriate mechanism for credentials

### ISSUE THREAD

**Issue by zoubeihua** [thebaselab/codeapp#651]
clone error could not find appropriate mechanism for credentials 
这个报错怎么解决呢，我用vscode 拉去输入账号密码就可以了，为什么用codeApp 没有输入账号密码的地方，直接报错没有凭证

**Comment by yusancky** [comment]
> 为什么用 Code App 没有输入账号密码的地方

在 Code App 中设置一下 GitHub 凭据，然后就可以使用了。

![](https://user-images.githubusercontent.com/83524927/204132559-70ec4049-9702-40a9-8727-bbcc62447c8a.jpeg)
