### ISSUE TITLE
How to push to remote repository?

### ISSUE THREAD

**Issue by shubham-1827** [thebaselab/codeapp#656]
I am new to this app, and I can’t see the ‘push’ option (only fetch option is there), how can I access my remote repository?

![B370C274-274B-4CDE-B047-0A79E07AB0FA](https://user-images.githubusercontent.com/117329147/202372277-cf1338c6-7d61-400c-8010-75e6bfa0ef49.png)

**Comment by bummoblizard** [comment]
Please refer to this: https://code.thebaselab.com/guides/version-control#pushing-to-remote

You might need to configure your credentials first: https://code.thebaselab.com/guides/version-control#pushing-to-remote

**Comment by shubham-1827** [comment]
Please can you guide me what to do? 
i think I have done everything as per the docs but still the error occurs?
![87406AD1-3889-48C4-B8E0-ACF210FAD3F9](https://user-images.githubusercontent.com/117329147/202430794-49f919cd-49e9-41e8-8228-99334a833fdb.png)
