### ISSUE TITLE
ssh-remote support

### ISSUE THREAD

**Issue by andy-yang-1** [thebaselab/codeapp#659]
Coding with IPad really needs ssh-remote, and we can ssh our remote server just like vscode.

**Comment by bummoblizard** [comment]
It is available. Switch over to the remote session and select SFTP server. Terminal as well as files access are supported.

**Comment by bummoblizard** [comment]
https://code.thebaselab.com/guides/connecting-to-a-remote-server-ssh-ftp

**Comment by andy-yang-1** [comment]
Thx! It really helps!
