### ISSUE TITLE
Unsupported credentials type (SSH authentication in Git)

### ISSUE THREAD

**Issue by lublak** [thebaselab/codeapp#682]
I try to login with GitHub.
I created a new personal token but I get this error message:

![image](https://user-images.githubusercontent.com/44057030/206276296-0c60313d-d4c3-41e0-bd33-a34c1e427db6.jpeg)

**Comment by lublak** [comment]
Also because it doesn't work it keeps in the gui:

![image](https://user-images.githubusercontent.com/44057030/206305419-a132e15d-7e19-4bd0-b4eb-d62394c88897.jpeg)

**Comment by bummoblizard** [comment]
HI. You need to set your personal access token in the settings menu. You can follow this link for reference: https://github.com/thebaselab/codeapp/issues/662

**Comment by lublak** [comment]
@bummoblizard i used my personal access token.

**Comment by lublak** [comment]
@bummoblizard just some issues. It's a classic token with full repo access and begins with ghp_
I tried user name and user email.
I also tried the new one github_pat_.
The issue was that the repo was cloned with ssh before. Tokens only works with https. After i cloned with code app direct it works fine.

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp/commit/524935fb9eea288a59adb7e78d9551b3df7e181d.
