### ISSUE TITLE
How can I use SSH Private Key?

### ISSUE THREAD

**Issue by Lucas-Baek-HYU** [thebaselab/codeapp#688]
I am a developer who is using your app well. I want to access AWS EC2, and the server uses priv key.

After using the key option in app, I thought I could add a key file or import the key, but I couldn't find a way because I was not used to it yet.

Could you guide me how I need to access my server using the key?

**Comment by bummoblizard** [comment]
Hi. To use a private key, store it in Documents/.ssh/id_rsa. You can open this file in Code App and copy the content of the private key over this file. You might need to enable 'show hidden files' in the settings menu to see it.

**Comment by Lucas-Baek-HYU** [comment]
Thank you. As per your guide, I put the pem file which is my private key in the Documents/.ssh/id_rsa directory in the code app :)

I approached it in the following way.
  1) Copy the pem file from the file app to the Documents directory of the Code app
  2) Move using the shell provided by the code app
  3) Verifying the use of remote server → key authentication in the code app

And I did "see public key" but the app didn't respond. What should I type in the SSH secret key?

**Comment by Lucas-Baek-HYU** [comment]
Thank you. As per your guide, I put the pem file which is my private key in the Documents/.ssh/id_rsa directory in the code app :)

I approached it in the following way.

  1. Copy the pem file from the file app to the Documents directory of the Code app
  2. Move using the shell provided by the code app
  3. Verifying the use of remote server → key authentication in the code app

And I did "see public key" but the app didn't respond. What should I type in the SSH secret key?

**Comment by Lucas-Baek-HYU** [comment]
Is there any update?

I saw that similar issues in the process of connecting with Mac OS were reported after my question, but it seems to be different from my situation. (But, it has been a lot of reference)

I wonder if there is a way to access the server using the private key of my AWS EC2 server 😁 

If you need to implement it, can you tell me the progress?

**Comment by Lucas-Baek-HYU** [comment]
Dear @bummoblizard 
I'm sorry, I reopened this issue.
Because I didn't understand the answer well.

I'm not sure where NMSSH is used on the iPad or iPhone (if it was Mac OS, I think it's an SSH-related library), but the problem I was curious about is access to AWS from mobile devices.

Please check if there is an update :)

**Comment by bummoblizard** [comment]
@Lucas-Baek-HYU I will take a look into this again today.

**Comment by Lucas-Baek-HYU** [comment]
@bummoblizard Is there any update?
Let me know if you need anything!

**Comment by Jflick58** [comment]
Jumping in as well - replicating the VS Code remote flow on an iPad was the main reason I bought this app. Private key auth works in other apps like terminus or WebSSH, so really hoping it can get figured out here. Otherwise, love the app!

**Comment by bummoblizard** [comment]
@Lucas-Baek-HYU @Jflick58 I added support for in-memory private key content in the latest TestFlight build (might take a while for the build to show up there). Let me know if it works for you.

TestFlight link: https://testflight.apple.com/join/EgZ8sE2P

**Comment by Lucas-Baek-HYU** [comment]
**Dear @bummoblizard,**
Thank you, today I was able to check the updated one as shown in the picture below from the link you shared 👍 

![codeapp_test](https://user-images.githubusercontent.com/96026789/223163510-ecb8f61e-bbb9-4b78-a7d7-8aad96b77695.jpg)

But I still don't know how to use them :(
I tried to connect to the server by copying the RSA key (START & END part) of the AWS EC2 server I had in "Private Key Contents", but I couldn't connect to the server. (Or I couldn't find using File Manager to load key files such as .pem or .ppk)

Could you tell me what I should do to test it?

**With Best Regard,
Lucas. B.**

**Comment by bummoblizard** [comment]
> **Dear @bummoblizard,**
> 
> Thank you, today I was able to check the updated one as shown in the picture below from the link you shared 👍 
> 
> 
> 
> ![codeapp_test](https://user-images.githubusercontent.com/96026789/223163510-ecb8f61e-bbb9-4b78-a7d7-8aad96b77695.jpg)
> 
> 
> 
> But I still don't know how to use them :(
> 
> I tried to connect to the server by copying the RSA key (START & END part) of the AWS EC2 server I had in "Private Key Contents", but I couldn't connect to the server. (Or I couldn't find using File Manager to load key files such as .pem or .ppk)
> 
> 
> 
> Could you tell me what I should do to test it?
> 
> 
> 
> **With Best Regard,
> 
> Lucas. B.**

I will test it on a AWS instance tomorrow and let you know.

**Comment by bummoblizard** [comment]
@Lucas-Baek-HYU 

I successfully connected to an AWS instance by:
- Set up a Amazon Linux EC2 instance
- Fill its public ip address in Code App
- Fill the user name as `ec2-user` (The default value for this depends on your machine type, refer to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html)
- Copy the content of `xxx.pem` to `private key content`, I used a RSA key, but ed25519 should work fine as well.

You might want to check the configuration of your AWS instance. For example, is a ssh ip whitelist enabled?

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/38398443/223440227-075e708f-efcd-4a6d-afe2-640311d85a5d.png">

**Comment by bummoblizard** [comment]
Reminder for myself: Write a guide on connecting an AWS instance in code.thebaselab.com.

**Comment by Lucas-Baek-HYU** [comment]
**Dear @bummoblizard,**
Wow, Thank you for your quick reply :)
I am very grateful for sharing your test results, and this update will be very helpful to me.

However, I have one question.
I copied my EC2 Private Key contents as your guide and tried to log in with my EC2 username.

But I'm still getting a message that I can't connect.
I tested the contents as below.

- Attempt to access both using Public IP and Domain Name
- Attempt to access an IP that is already inbound within an instance (via a router WiFi connection in my development environment)

Is there anything I misunderstood?
Or, like what you said the other day, should I put the pem cert file in the "Documents/.ssh/id_rsa" path and try it?

**With Best Regard,**
**Lucas. B.**

**Comment by bummoblizard** [comment]
Hi @Lucas-Baek-HYU .

No, you don't need to do that. Just copying the key content should be enough.

You probably did it, but just to confirm, did you successfully connect to the instance using another SSH client? This can confirms you set up the server properly.

**Comment by Lucas-Baek-HYU** [comment]
**Dear @bummoblizard,**
Yes, other SSH clients read the PEM key file directly, but first of all, I checked that the server connection was going well.

**Comment by Lucas-Baek-HYU** [comment]
Dear **@bummoblizard**,
Is there any additional update? I saw a new menu called "Import from File". However, getting the key failed, and still copying the contents of the key and connecting it to AWS also fails.

**Comment by GrangerLue** [comment]
> @Lucas-Baek-HYU @Jflick58 I added support for in-memory private key in the latest TestFlight build. You can now directly copy your private key into Code App. Let me know if it works for you.
> 
> TestFlight link: https://testflight.apple.com/join/EgZ8sE2P. The latest build might take a while to show up.

Jumping in as well - I bought this app while the current version does not have the support for private key, which is the main reason I bought this app. And the testflight link is full. Any ideas?

**Comment by thamer111** [comment]
@bummoblizard, I'm unable to import a private key from the public update in the App Store, which is crucial for my use.
Additionally, it appears that the TestFlight beta version has reached its maximum capacity. 
Thank you for your attention.

**Comment by bummoblizard** [comment]
> 
> 
> @bummoblizard, I'm unable to import a private key from the public update in the App Store, which is crucial for my use.
> 
> Additionally, it appears that the TestFlight beta version has reached its maximum capacity. 
> 
> Thank you for your attention.

The update will be available as soon as it passes the App Store review.

**Comment by bummoblizard** [comment]
> The update will be available as soon as it passes the App Store review.

It is now available on App Store.

**Comment by carstenf** [comment]
I still have the same issues: (using aws ec2, ec2-user)
- Trying to import a pem file failed 
- Coping the content into the private key area and connect as well failed
Some suggestions?

**Comment by bummoblizard** [comment]
@carstenf A potential fix for this is now available on TestFlight. Can you let me know if the issue persist there? Here's the link: https://testflight.apple.com/join/EgZ8sE2P

**Comment by carstenf** [comment]
Works fine, thanks
