### ISSUE TITLE
Auto refresh for PDF and images

### ISSUE THREAD

**Issue by Feliks151450** [thebaselab/codeapp#691]
In vscode, if i change a file like PDF and other images via code like python, it would auto refresh, but in this app i have to open other files and reopen it to see the latest context. It will be great if this app could do so.

**Comment by bummoblizard** [comment]
Great suggestion. I'll take a look into it.

**Comment by yusancky** [comment]
And when editing and previewing Markdown file, I should close the preview page and then reopen to refresh. I think it needs auto refresh too.

**Comment by bummoblizard** [comment]
Will include in the next update.

**Comment by bummoblizard** [comment]
The feature is now available in TestFlight.

**Comment by Feliks151450** [comment]
> 

hello, does the "auto refresh" only works in local mode? It does not work when I ssh to a remote machine.
