### ISSUE TITLE
Working with multiple files (.txt or .py)

### ISSUE THREAD

**Issue by Bschoy** [thebaselab/codeapp#692]
I am using multiple .txt files to read and write to in python. These all are in the same folder as the Script. Testing it using a MAC worked fine but on IPad it says File not found. I tried giving the PATH in Addition to the file name but it still doesn't work. 

from: 
"test.txt"

to: 
"Auf meinem iPad/Code/Newly-Seen-Analyse/final/test.txt"
(My system is in German)

Any workarounds or solutions?

**Comment by Bschoy** [comment]
Using the newest AppStore release right now

**Comment by bummoblizard** [comment]
Can you show me the source code?

**Comment by bummoblizard** [comment]
Try to cd into the folder containing your source code and run Python in the
terminal manually there. The paths are incorrect because they are relative
to the current working directory.

「Bschoy ***@***.***>」在 2022年12月12日 週一，23:12 寫道：

**Comment by Bschoy** [comment]
> 寫道

I tried that but somehow still don't get it, maybe since im new to all of this

![image](https://user-images.githubusercontent.com/96501815/207359885-149ffba7-fd72-4817-a4db-b026fc06ea83.jpeg)

**Comment by bummoblizard** [comment]
```
cd Newly-Seen-Analyse
cd final
Python preparation.py
```

**Comment by Bschoy** [comment]
Using this in the Console works to execute, but somehow not when providing the path of a file to work with within a script

**Comment by bummoblizard** [comment]
It's related to relative paths. Paths inside your Python code are relative to the working directory. When clicking the button to run, the working directory is always the root of your project folder.
