### ISSUE TITLE
Cannot rename new directory

### ISSUE THREAD

**Issue by wmorgue** [thebaselab/codeapp#697]
STR:

1. Create a `New Folder`
2. Try to rename it
3. Get the errror: «New Folder couldn’t be move to … because an item with same name already exists.»

Look at the screen recording:

https://user-images.githubusercontent.com/24982084/207949681-bd7c154e-b648-4da6-853c-d5eb40c14bf8.mov

Environment:
iPad Pro 11” M1
iPadOS 16.2
Magic Keyboard 2 or screen keyboard (it’s doesn’t matter)
Code app. Version 1.4.1 Build 157 from TestFlight

**Comment by bummoblizard** [comment]
Thank you for reporting this. I can confirm this issue.

**Comment by bummoblizard** [comment]
Related commit: https://github.com/thebaselab/codeapp/commit/4b4bfc792c41b9e99b00e0e60dd6a39e07416888

**Comment by bummoblizard** [comment]
MoveItem implementation: https://github.com/thebaselab/codeapp/blob/main/CodeApp/Managers/FileSystem/Local/LocalFileSystemProvider.swift
