### ISSUE TITLE
Folder `Code` disappeared when upgraded

### ISSUE THREAD

**Issue by yusancky** [thebaselab/codeapp#698]
I stored most of the files in the folder `Code` under `My iPad` generated during installation. It worked very well some days ago. 

However, after I upgraded to `1.41` from `1.40`, the folder `Code` disappeared. I couldn't find the folder in The folder where recently deleted files are stored, either. 

In my memory, I upgraded for 2 times so I'm not sure which upgrade caused the problem. Now, the version of my `Code App` is `1.4.1 Build 155`. 

How can I do to find my files?

**Comment by bummoblizard** [comment]
Hi. It's supposed to be an iOS bug. You just need to restart your iPad.

**Comment by yusancky** [comment]
Fixed
