### ISSUE TITLE
Sometimes Keyboard Toolbar is Dark in `Light` Theme

### ISSUE THREAD

**Issue by yusancky** [thebaselab/codeapp#700]
When using theme `Light`, keyboard toolbar may be dark sometimes. 

![](https://user-images.githubusercontent.com/83524927/208374997-4eea70f9-2486-42b4-b862-119a81b5c5fe.jpeg)

**Comment by bummoblizard** [comment]
Hi. Which version are you on? Did it happen after the update?

**Comment by yusancky** [comment]
> Which version are you on? 

1.4.1 (158)

> Did it happen after the update?

I found this issue before I updated. But this has still happened after the update.

**Comment by yusancky** [comment]
I upgraded to the new version of Code App 1.4.3 (168) and the issue still reproduces like this: 
1. Open the Code app and open the keyboard. 
2. Open other apps without collapsing the keyboard. You can do this through the Dock, notifications, or other means. 
3. Simply swipe the app's page. 
4. Go back to the Code App and open the keyboard. 

Here is a video to show the issue. 

https://user-images.githubusercontent.com/83524927/211441223-8d07422a-e183-4446-8be1-b293c4f228b9.MOV

**Comment by bummoblizard** [comment]
Hi. Please see if https://github.com/bummoblizard/codeapp/commit/79529a3493729cc417773f321c949191f692a11d improved this.
