### ISSUE TITLE
SSH connections to macOS Ventura with ssh key

### ISSUE THREAD

**Issue by Jbrev3** [thebaselab/codeapp#715]
I am able to SSH from my iPad to my Mac with a username and password, but I haven't been able to figure out how to SSH using key authentication. 

I successfully generate the keys using ssh-keygen in the terminal in the code app on my iPad, but how to I get to key to the ~/.ssh/authorized_keys file on my Mac? ssh-copy-id does not seem to work. I did copy the .pub key, sign on to my Mac with a password, and then paste the key in the authorized_keys file. However, when I try to sign on, I get "Authorization failed" in the app. This is perhaps similar to issue #688.

Note: I am able to ssh to my Mac using another key on another device, so I think the Mac side is set up correctly. 

I have very little experience with SSH, and this is my first post, so let me know if you need additional information.

**Comment by bummoblizard** [comment]
Hi. I am able to reproduce this problem. Seems like the last update broke ssh using private keys. I will into this and issue a fix.

**Comment by bummoblizard** [comment]
@Jbrev3 Which macOS version are you on?

**Comment by bummoblizard** [comment]
This is actually a compatibility issue with macOS Ventura. The new OS requires a more secure hash algorithm for public keys. I'll need to update `ssh-keygen` for this.

As a workaround:
- add the following entries in `/private/etc/ssh/sshd_config` on your Mac 
```
HostkeyAlgorithms +ssh-rsa
PubkeyAcceptedAlgorithms +ssh-rsa
```
- Run `sudo launchctl stop com.openssh.sshd` (This restarts the ssh service)

**Comment by bummoblizard** [comment]
Unfortunately this requires a reimplementation of ssh connection and will take some time but I will priorities on fixing this.

**Comment by Jbrev3** [comment]
I have Ventura 13.1. And I verified your solution worked. Thank you!

**Comment by bummoblizard** [comment]
Update: It is also possible generate a supported key-pair by running `ssh-keygen -t ed25519` so that macOS will accept the connection. In the latest TestFlight version, you might manually specify a custom private key to take advantage of this.

**Comment by thekeith** [comment]
> Update: It is also possible generate a supported key-pair by running `ssh-keygen -t ed25519` so that macOS will accept the connection. In the latest TestFlight version, you might manually specify a custom private key to take advantage of this.

Can confirm this works.

To others who see this, here are the steps to resolve:

1. Open the terminal in Code
2. Run `ssh-keygen -t ed25519`
3. Open a connection to the remote machine _without_ using SSH (username and password)
4. Edit the ~/.ssh/authorized_keys file and append the contents of id_ed25519.pub to the file, then save. You can do this with a command line editor like nano (ie: `nano ~/.ssh/authorized_keys`)
5. Close the connection and make a new connection in Code using key authentication, and paste the contents of id_ed25519 into the private key field (not id_ed25519.pub)
6. Set save credentials and connect

That should allow you to connect without issue.
