### ISSUE TITLE
Node js Live server module not working

### ISSUE THREAD

**Issue by shubham-1827** [thebaselab/codeapp#724]
I am learning JavaScript now and don’t know much about node.js till now, but I want to use the live server to create a live server.

I use these commands:
`npm install -g live-server`
`live-server`

but I got this error:
![90AF6CD1-22A2-42FA-B273-0509A120E0AA](https://user-images.githubusercontent.com/117329147/211992117-de7e0afd-1c44-4cfb-bdc1-fb4c1624daf6.jpeg)

**Comment by bummoblizard** [comment]
`live-server --no-browser`

**Comment by bummoblizard** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/38398443/212559915-3f3800e2-24e0-45ae-b473-f85108be1acb.png">
