### ISSUE TITLE
中文环境下，右下角的编码字段（图片中是“UTF-8”）显示位置有问题

### ISSUE THREAD

**Issue by iblueer** [thebaselab/codeapp#73]
在键盘收起的情况下，编码字段会漂移一点位置。

键盘弹出后不会有这个情况。
![image](https://user-images.githubusercontent.com/3581944/113462702-ca78a500-9454-11eb-95bf-5638ff4f991d.png)
![image](https://user-images.githubusercontent.com/3581944/113462711-d3697680-9454-11eb-922e-a935b5ba7474.png)

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp-source/commit/21ad359595d19b490a72654c8560091f5feb8650
