### ISSUE TITLE
Multiple SSH servers

### ISSUE THREAD

**Issue by papalozarou** [thebaselab/codeapp#730]
At present there's only one key – so I can only have one SSH connection at a time. Can this be updated to allow multiple connections ala Blink, SecureShellFish, Textastic etc.?

**Comment by bummoblizard** [comment]
Thanks for the suggestion. I'll implement this in the future. But you can currently connect to multiple server by:
- Using password authentication
- Copying the public key to the server

**Comment by bummoblizard** [comment]
Implemented via https://github.com/thebaselab/codeapp/commit/4e54d1e3a3c772644ce9a7dcd2ec58364c27900e.
