### ISSUE TITLE
pip install some packages error

### ISSUE THREAD

**Issue by darkr4y** [thebaselab/codeapp#734]
Origin project: https://gitee.com/liqianglog/django-vue-admin.git

1. freezing at `pip install impacket`
2. install failed:
```

coreschema

mysqlclient

Pillow

ruamel.yaml

```

can you give some help plz?
thank u :)

**Comment by darkr4y** [comment]
now on 1.4.3 Build 186
I can install 
```
Pillow
ruamel.yaml
ruamel.yaml.clib
coreschema
```

**Comment by darkr4y** [comment]
npm install error
```
Reached heap limit Allocation failed 
```
![image](https://user-images.githubusercontent.com/4407382/216825506-7c8ba3f7-250e-4783-9be1-c7d3a832dbfc.png)

**Comment by bummoblizard** [comment]
The Node.JS and Python runtime in Code App both have limits on memory usage, as well as constraints on native binaries. Therefore not all modules are supported. For Node.js in particular, the runtime will fail if it tries to consume too much memory.
