### ISSUE TITLE
When i connect via ssh with a key the app crashes.

### ISSUE THREAD

**Issue by Albeph** [thebaselab/codeapp#735]
When I connect via ssh to my Oracle Cloud VM, the code app crashes.
What tipe of log you need? Because is very annoying.

Have a nice day!

**Comment by bummoblizard** [comment]
Does it crash every time or occasionally? Please send me the crash log by:

Open the Analytics & Improvements section of Settings on the device. See Share analytics, diagnostics, and usage information with Apple.

Tap Analytics Data.

Locate the log for your app. The log name starts with Code_

Select the desired log.

Tap the Share icon, and select Mail to send the crash report as a mail attachment to [sh.chung@thebaselab.com](mailto:sh.chung@thebaselab.com)

**Comment by Albeph** [comment]
I send the email!

**Comment by bummoblizard** [comment]
> I send the email!

Thanks for the log. I noticed that you are using a beta version of iPadOS. I suggest updating it to a stable version first.

**Comment by Albeph** [comment]
No, i use 16.2 stable

In data 18 gennaio 2023 16:07:45 Chung Shing Hin ***@***.***> 
ha scritto:

**Comment by Albeph** [comment]
I use the stable version of ipad os.The first photo is the version installed on my ipad, the second photo is a wikipedia page, that represent the last stable version that can be installed Il giorno 18 gen 2023, alle ore 16:19, Francesco Alberghina ***@***.***> ha scritto:﻿



No, i use 16.2 stable




In data 18 gennaio 2023 16:07:45 Chung Shing Hin ***@***.***> ha scritto:



I send the email!

Thanks for the log. I noticed that you are using a beta version of iPadOS. I suggest updating it to a stable version first.

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/commit/fcd73f2b8b26cf805a62133d657395c94ff09669

**Comment by bummoblizard** [comment]
Reference: https://github.com/NMSSH/NMSSH/blob/94624c90e357eda412e40c1a3d9dec1a1cb7479d/NMSSH/NMSSHSession.h#L37-L44

**Comment by Albeph** [comment]
Is not solved… Also with the last update…

**Comment by bummoblizard** [comment]
> Is not solved… Also with the last update…

Thanks for letting me know. I will keep working on this.

**Comment by Albeph** [comment]
The problem seems to be fixed. Thanks a lot!
