### ISSUE TITLE
Initialize GitHub repository not working

### ISSUE THREAD

**Issue by HaremKing-11** [thebaselab/codeapp#736]
I have a private GitHub repo that I have been using for a few week. But on the 18th, after reinstalling the app, the initialize repository function wasn’t working properly. I put the clone url and then Code App says that the repo has been initialized but I can’t see any files from the repo and the initialize repo button doesn’t disappear. If I try to re-enter the GitHub url, I get a message saying the repo already exists.

I just want to be able to access my repo and edit it when needed, please help

**Comment by HaremKing-11** [comment]
Nvm it started working by itself somehow

**Comment by Lukas-Batema** [comment]
Nice! I'm glad you could figure it out!
