### ISSUE TITLE
xcode build failed due to dependencies

### ISSUE THREAD

**Issue by wbjsamuel** [thebaselab/codeapp#737]
Hi, thanks for the awesome app.
Here, i have a problem while building.
`error: The package product 'ZipArchive' requires minimum platform version 15.5 for the iOS platform, but this target supports 13.0 (in target 'SwiftGit2' from project 'SwiftGit2')`
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/38983954/213630050-5df5af53-6b49-4d58-9f9c-bb554ff8bb26.png">
How can i settle this problem ?

**Comment by bummoblizard** [comment]
Are you running an Intel Mac?

**Comment by wbjsamuel** [comment]
Nope, I am running a M1 Monterey Mac

**Comment by bummoblizard** [comment]
You might have accidentally updated ZipArchive to a newer version. Reset all changes you made to the repo in git and re-download the dependencies. 

You can do this by running `git reset --hard` or simply re-clone the project.

if this doesn't work, go to Xcode file navigator > Packages > SwiftGit2 > Modify `platforms: [.iOS(.v13)],` to `platforms: [.iOS("15.5)],`. Do the same for 'iOS Deployment target` in the Code project.

**Comment by wbjsamuel** [comment]
thanks a lot.
I settle this problem by using `git reset --hard`
