### ISSUE TITLE
Java input

### ISSUE THREAD

**Issue by Bschoy** [thebaselab/codeapp#739]
i just now realized that input needs to be provided before running the program. 
This links to an issue i previously opened concerning a local copy of openJDK to run Java locally, but even if server-side execution is the only way would it not be possible to ask for input in a behavior identical to a desktop environment (meaning not upfront / before running the program)?

**Comment by Bschoy** [comment]
though a local distribution of Java could render this issue meaningless / solved.

**Comment by Bschoy** [comment]
> though a local distribution of Java could render this issue meaningless / solved.

if not something similar to what replit did could be done, they use server-side execution but ask for input in a desktop like manner

**Comment by bummoblizard** [comment]
Thank you for the suggestions. I intend to bring a local runtime of Java to Code App. 

These projects should be good references:
- https://github.com/PojavLauncherTeam/openjdk-multiarch-jdk8u
- https://github.com/PojavLauncherTeam/jdk17u

**Comment by Bschoy** [comment]
> Thank you for the suggestions. I intend to bring a local runtime of Java to Code App. 
> 
> 
> 
> These projects should be good references:
> 
> - https://github.com/PojavLauncherTeam/openjdk-multiarch-jdk8u
> 
> - https://github.com/PojavLauncherTeam/jdk17u

these both look very promising, glad you're looking into it.
Thanks for your hard work and quick responsiveness.

**Comment by Bschoy** [comment]
@bummoblizard would you happen to be able to guess an estimated date after which local Java support should be realized?

**Comment by Bschoy** [comment]
> > @bummoblizard would you happen to be able to guess an estimated date after which local Java support should be realized?
> 
> Hi. I'm focusing on fixing the existing issues. I will work on it after that.

Appreciate it, i found this App that has a local Java 9 runtime that works. (I have tested it without internet) To use it you have to pay around 3€ but it works.

I'm not fond of the User experience and UI at all but it still could end up helping you implement a local Java runtime yourself. 

https://apps.apple.com/app/id992268206

**Comment by bummoblizard** [comment]
Local OpenJDK is added in https://github.com/thebaselab/codeapp/commit/39155744844ad472f0b79c714230a8691a7832bb. However, interactive input is still not supported.

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp/issues/1036
