### ISSUE TITLE
iPad app crashes when reconnecting to sftp server after disconnecting

### ISSUE THREAD

**Issue by M-Alter** [thebaselab/codeapp#742]

**Comment by bummoblizard** [comment]
I've pushed a fix for this in TestFlight. Let me know if it solves the problem: https://testflight.apple.com/join/EgZ8sE2P

**Comment by M-Alter** [comment]
Thanks @bummoblizard  this does actually solve the problem.

**Comment by M-Alter** [comment]
When is it expected to roll out to the App Store?

**Comment by bummoblizard** [comment]
Within this week :)
