### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by redscorpse** [thebaselab/codeapp#755]
Will it be possible to add Vim plugins (or similar) to Code App?
Or at least shortcuts like commenting lines, moving blocks up and down, folding, etc.

**Comment by bummoblizard** [comment]
While there is no vim support, you can refer to https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf for the common editing shortcuts.

**Comment by redscorpse** [comment]
> While there is no vim support, you can refer to https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf for the common editing shortcuts.

Cool, thanks!
