### ISSUE TITLE
Suppress certain font ligatures

### ISSUE THREAD

**Issue by graphemecluster** [thebaselab/codeapp#758]
When using the default font Menlo, font ligatures “fi” and “fl” appear on my iPad Pro 12.9’:
![IMG_0622](https://user-images.githubusercontent.com/53967830/216749741-e92a234a-b2ec-4066-8541-6be46f76199a.jpeg)

**Comment by bummoblizard** [comment]
Fixed via #758. It will be available on TestFlight soon.

**Comment by graphemecluster** [comment]
Thanks for the quick fix. People who are using Fira Code will be surprised though.
