### ISSUE TITLE
Changes lost for unsaved file when switching file in explorer

### ISSUE THREAD

**Issue by graphemecluster** [thebaselab/codeapp#761]
To reproduce, open a file on a tab. Type something and click another file in the explorer.

**Comment by bummoblizard** [comment]
I can't seem to reproduce this. Would be great if you can send me a screen capture demonstrating it. Also let me know the app version.

**Comment by graphemecluster** [comment]
1.4.2 Build 165 (The TestFlight is already full and I’m not able to join)

https://user-images.githubusercontent.com/53967830/216815074-94891183-c5ec-4d88-8b5b-3b151924b7d3.mp4

**Comment by bummoblizard** [comment]
It should be fixed in master. The update should be available soon.

**Comment by bummoblizard** [comment]
This fix is now available in App Store.
