### ISSUE TITLE
Data leak?

### ISSUE THREAD

**Issue by GitSamson** [thebaselab/codeapp#775]
Somehow I can see 3,700 changes in resource control panel, but I didn't create any of these, even I commit but don't know where it committed. 

Please help to check.

**Comment by bummoblizard** [comment]
Please share a screenshot for me to take a better look at it. These files are likely generated by a dependency manager and can be ignored by adding entries to .gitignore.

**Comment by GitSamson** [comment]
> Please share a screenshot for me to take a better look at it. These files are likely generated by a dependency manager and can be ignored by adding entries to .gitignore.


Uploading FullSizeRender.MOV…

**Comment by GitSamson** [comment]
I see the problem is, thanks for reply my silly question. 
The files are from /node_module even I didn’t connect to repo.
