### ISSUE TITLE
Incorrect terminal autocomplete with network folder

### ISSUE THREAD

**Issue by RobertCordingly** [thebaselab/codeapp#78]
This test requires a keyboard to be connected to the iPad.

Steps to reproduce:
1. Open the program for the first time, create a new folder called "test"
2. Connect to a network folder (SMB) and select it as your current directory
3. Open terminal and run 'ls', you should see everything in the network folder.
4. Type 'cd t' and hit tab on a keyboard. It will autocomplete to 'cd test' even though a folder named 'test' does not exist in the network folder. 

Tab autocomplete appears to only take into account the contents of the root folder the app uses, not network folders.

**Comment by bummoblizard** [comment]
Can confirm. Will fix this in the next update.
