### ISSUE TITLE
Will the local compiler for C/C++ be available in the future?

### ISSUE THREAD

**Issue by zzl-learner** [thebaselab/codeapp#79]
I’ve been using this app on my pad for a while, which is really convenient for us student. It’s awesome to see a local Python compiler available. However, some courses of mine require the c/c++ environment. I’m  wondering  if the local C/C++ compiler will be available in the future?

**Comment by bummoblizard** [comment]
Yes. It would be possible and it's something I plan to add in the future.

**Comment by bummoblizard** [comment]
Added in the latest build.
