### ISSUE TITLE
修改C/C++文件的代码后有一定几率触发无法输入的bug

### ISSUE THREAD

**Issue by PeterCKing** [thebaselab/codeapp#797]
在修改完代码执行前，终端显示：
                            
      Document $

单击执行后显示：

     Document $ clang

     Document $
再次执行还是重复上述现象，根本没有输入或者输出

**Comment by PeterCKing** [comment]
![Uploading 61F48584-7E64-4EB4-81DC-253939F30C42.png…]()

**Comment by PeterCKing** [comment]
@bummoblizard

**Comment by LFY-INVERSE** [comment]
一样，我也没有输出。一般重新下载就又好了。

**Comment by bummoblizard** [comment]
Should be fixed by https://github.com/thebaselab/codeapp/issues/612.
