### ISSUE TITLE
有些语句无法正确执行

### ISSUE THREAD

**Issue by segeral** [thebaselab/codeapp#80]
如下图![image](https://user-images.githubusercontent.com/54263609/114273167-b41dab00-9a4b-11eb-85db-90398870a982.png)

INPUT 中已经输入
3 5

但依然报错，而这个语句在vs code上执行就不会出错

**Comment by bummoblizard** [comment]
你好，这个应该是关于`input(”“)`的bug，当提示字元时空白的时候，终端会无法输入字元。

你可以尝试使用`input(“input? “)。
