### ISSUE TITLE
positive look behind regex doesn’t work

### ISSUE THREAD

**Issue by oscampo** [thebaselab/codeapp#802]
Trying to use this simple regex:

```
(?=\$)\d+
```

to extract numeric value of a price from this text:

```
Model : QAZ-243
Price: $50
Color: Blue 32
Size: 17
```

but it doesn’t works

**Comment by bummoblizard** [comment]
Which programming language are you referring to?

**Comment by oscampo** [comment]
It´s only a simple regex search on a txt

**Comment by bummoblizard** [comment]
I see. Lookbehind isn't supported until iOS 16.4. Please consider updating your device.

**Comment by oscampo** [comment]
Perfect!
I just updated my iPad to a beta version of iOS 16.4 and regex search work like a charm.
Thanks!
