### ISSUE TITLE
When new fonts are installed on ipad they aren’t visible on Code

### ISSUE THREAD

**Issue by oscampo** [thebaselab/codeapp#804]
When new fonts are installed as a new profile or in the fonts section of iPad system settings(via a third app), those fonts are not visible in the settings of Code

**Comment by bummoblizard** [comment]
Enable the show all fonts option in the settings menu. By default, the font picked only shows monospace fonts.

**Comment by oscampo** [comment]
Thanks, 
Enable “show all fonts”  was the first option to try to find the newly installed fonts, but it doesn't work 
 Also, I tried with monospaced fonts, but the same: they are not shown in the font picker. 
The specific font I trying to use is anka/coder font: https://code.google.com/archive/p/anka-coder-fonts/downloads

**Comment by bummoblizard** [comment]
Addressed in https://github.com/thebaselab/codeapp/commit/cdec2e606a1742fd8d8755087b9c3e8853024896.
