### ISSUE TITLE
Can’t run C program on my iPad - it‘s running on my Windows machine tho

### ISSUE THREAD

**Issue by Brorob255** [thebaselab/codeapp#807]
Hey you guys - im pretty new to coding in general and am currently learning it a but in university. When i try and run my program on the iPad it gives me an errormessage that sais: *MYNAME*  $ clang /private/var/mobile/Containers/Data/Application/28422960-913F-4C4B-AA87-1194BFC976DA/Documents/pin2_s2023/01_Warmup_C. 
Des that have something to do with me pulling the files from our Unis Server as a Repo? 
Thank you guys so much in advance- looking forward to being able to completely code on my ipad instead of on my at home PC.

![D2E1BE69-6558-4F25-99B3-49CC4A0894BF](https://user-images.githubusercontent.com/129838361/229730718-7dbab0ec-e80d-4ff6-8e8d-2e4b4ff1a814.png)

**Comment by Brorob255** [comment]
I figured out that i had to go into the folder i was trying to run the program in to be able to run the program through the terminal. Sry for bothering :D

**Comment by sixeightw0lf** [comment]
thankyou for the note though! this will help people in the future!
