### ISSUE TITLE
Find in folder recursively

### ISSUE THREAD

**Issue by NyaMisty** [thebaselab/codeapp#81]
When go over big projects, we often use find in files/folders to quickly look at related code.
Currently the Code app can only search in opened files, making the find feature nearly useless :(

**Comment by bummoblizard** [comment]
Hi. I agree this would be a great feature. Let's see how I can implement this efficiently.

**Comment by bummoblizard** [comment]
It might also be worth mentioning that the terminal has support for `grep`.

You can use this command to search for text recursively: `grep -r 'text goes here' path_goes_here`

**Comment by NyaMisty** [comment]
> It might also be worth mentioning that the terminal has support for `grep`.
> 
> You can use this command to search for text recursively: `grep -r 'text goes here' path_goes_here`

I agree. Actually I have three ways to search:
- by using Github's search feature: slow, and does not work for forked repo
- by using grep: always working, but I can't navigate to each file easily :(
- by combining Code App with grep & Github search: use the above methods to locate files, then open them in editor and search. Slow but the navigating experience is far more better.

So personally I really hope that Code app can integrate grep's functionality ;)

**Comment by bummoblizard** [comment]
Added in the latest build :D
![IMG_0392](https://user-images.githubusercontent.com/38398443/114408115-af87fc80-9bdb-11eb-93ad-1f126c42dae4.jpeg)

**Comment by NyaMisty** [comment]
Thanks for the super fast response and implementation!
but it seems that the testflight is obsolete, and appstore still didn't updated :(

**Comment by bummoblizard** [comment]
I've uploaded the build to TestFlight: https://testflight.apple.com/join/EgZ8sE2P
Check it out! :)

> Thanks for the super fast response and implementation!
> but it seems that the testflight is obsolete, and appstore still didn't updated :(
