### ISSUE TITLE
Clone error

### ISSUE THREAD

**Issue by oscampo** [thebaselab/codeapp#820]
With version 1.4.4 (193), it's not possible to clone any repository, always obtains the same error:

`Clone error: failed to resolve address for github.com: nodename nor servname provided, or not known`

**Comment by bummoblizard** [comment]
I couldn't reproduce this issue. It could be a temporary network error. Try to restart your device.

**Comment by oscampo** [comment]
Thanks. Restarting the device fixed this issue.
