### ISSUE TITLE
Pulling from a known Git not syncing

### ISSUE THREAD

**Issue by Zack-Intellica** [thebaselab/codeapp#827]
Pull request states it completed, and it shows how many changes need to come to the iPad, but no files get updated

![image](https://github.com/thebaselab/codeapp/assets/119376124/57ff4029-7cfc-4a7d-8f83-91817ff2eaae)

**Comment by bummoblizard** [comment]
You need to manually check-out to the remote branch for the changes to appear in the file system. Note that conflict resolve is not supported yet, so any conflicting local changes will be discarded.

Specifically, select `origin/HEAD` in this menu: https://code.thebaselab.com/guides/version-control#switching-branches.

**Comment by bummoblizard** [comment]
Git pull is now supported.
