### ISSUE TITLE
iPad can’t scroll horizontally in the Project Viewer

### ISSUE THREAD

**Issue by ais-developer** [thebaselab/codeapp#828]
I can’t seem to see my files because when i open 4 nested folder the file name keeps going to the right and off the end of the end.
You should be able to horizontally scroll or resize the project folder view window

**Comment by ais-developer** [comment]
[](https://ibb.co/3fnZbsc)

**Comment by ais-developer** [comment]
https://ibb.co/3fnZbsc

please see picture, you can see the file names are getting cut off.

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp/commit/a89bc748af633d3c5d6f20a23682866e142e2889. It is now possible to adjust the width of the sidebar.
