### ISSUE TITLE
ssh 命令行光标跑偏

### ISSUE THREAD

**Issue by czln** [thebaselab/codeapp#83]
输入命令以后光标就跑偏了，不过不影响输入。
另外自带的命令行的cwd很奇怪，没法调整，打开新的文件夹以后，工作文件夹也不会变，cd命令也没有权限往上调。
![image](https://user-images.githubusercontent.com/11393043/114341184-bedf5980-9b8b-11eb-8978-0dd526f5182e.png)

**Comment by bummoblizard** [comment]
最新的版本应该有更好的SSH支持，可以试一下哦
