### ISSUE TITLE
One Particular File Will Not Display

### ISSUE THREAD

**Issue by 12buntu** [thebaselab/codeapp#845]
Hey! I’ve been using this app for some web development stuff, and for some reason it refuses to render one text file. All other text files have worked correctly, and I cannot replicate the issue. When I attempt to open the file, a new tab is opened with the correct file name, but no change occurs on the editor screen—whatever file was previously displayed continues to be displayed. In short, I cannot get the editor to focus on this file, although there is no other file that behaves this way. 

Any help fixing this on my end, if it is possible, would be appreciated!

The faulty text file is linked below. It has not had any issues with VS code or any other text editor I have used.
https://github.com/12buntu/Book-N/blob/master/_posts/Aria-Sphere/2023-03-12-Aria's-Sphere.md?plain=1

**Comment by bummoblizard** [comment]
The fix should be available on TestFlight soon.

**Comment by 12buntu** [comment]
Oh thank you so much! I don’t even know how I didn’t notice that before. I just changed the file name and everything is all good now!
