### ISSUE TITLE
非常想知道支持哪些快捷键

### ISSUE THREAD

**Issue by edhnt455** [thebaselab/codeapp#85]
用pad写代码基本都会配个键盘的吧，那快捷键就显得非常重要。试了一下最基本的复制删除保存之类的都没问题，但是像注释，运行之类的常用快捷键也很重要吧。我找了半天没看见有相关说明，是我没找到还是没有做呢，求告知！

**Comment by bummoblizard** [comment]
关于文件编辑器的快捷键大致与￼VS Code￼相同：
￼ https://gist.github.com/wxingheng/e3fc8bb470db102bc12c3cfcaabdcfae

注释和运行的快捷键分别是 `Command + /`和`Command + R`￼￼。

至于其他的快捷键可以长按Command￼查看。￼

**Comment by edhnt455** [comment]
好的👌
