### ISSUE TITLE
Can't see directory and file names several levels deep

### ISSUE THREAD

**Issue by arjenschrijer** [thebaselab/codeapp#859]
I am connected to my remote server but to go to my project folder I have to go quite a lot of levels deep. /home/[user]/sites/[folder]/[folder]/project/...

When I'm that deep into the folder structure I can no longer see the names of the files and folders due to the sidebar being to narrow. An option could be to enable horizontal scroll to the explorer or to allow setting a path for the connection to start on a deeper level than just "/".

![image](https://github.com/thebaselab/codeapp/assets/9567120/aedffeff-7f71-4946-a53c-9383bba1c720)

**Comment by bummoblizard** [comment]
Thank you for the report. While I am working on improving this, you might hold down on a sub-directory and pick `assign as workspace folder` to properly show the files under it.

**Comment by Yolumia** [comment]
I have encountered the same problem.

**Comment by PuttyDeVil** [comment]
It is still not enough even with “assign as workspace folder”. I think there are some people work on ssh who need a convenient “cd” command. Hope you can support a command line interface to open files and change directory.

**Comment by PuttyDeVil** [comment]
It is still not enough even with “assign as workspace folder”. I think there are some people working on ssh who do need a convenient “cd” command. Hope you can support a command line interface to open files and change directory.

**Comment by PuttyDeVil** [comment]
t is still not enough even with “assign as workspace folder”. I think there are some people working on ssh who do need a convenient “cd” command. Hope you can support a command line interface to solve this problem.

**Comment by PuttyDeVil** [comment]
It is still not enough even with “assign as workspace folder”. I think there are some people working on ssh who do need a convenient “cd” command. Hope you can support a command line interface to solve this problem.

**Comment by PuttyDeVil** [comment]
It is still not enough even with “assign as workspace folder”. I think there are some people working on ssh who do need a convenient “cd” command. Hope you can support a command line interface to solve this problem. > Thank you for the report. While I am working on improving this, you might hold down on a sub-directory and pick `assign as workspace folder` to properly show the files under it.

**Comment by bummoblizard** [comment]
Fixed in https://github.com/thebaselab/codeapp/commit/a89bc748af633d3c5d6f20a23682866e142e2889. It is now possible to adjust the width of the sidebar.
