### ISSUE TITLE
Add local git (FR)

### ISSUE THREAD

**Issue by talaviram** [thebaselab/codeapp#865]
While there is some git functionality,
For my usage at least, a binary `git` available on the terminal would be much appreciated.

My rationale(s):
- I barely use git from UI
- In the specific scenario I'm trying, I have a folder on iCloud with a swift playground app that I can try to develop on macOS/Xcode and iPad. (if you put the swiftpm inside a folder you can open the folder and then access the guts of the `.swiftpm` folder from code!)
- My git is local so far (I don't sync it remotely, it's only backed-up/synced)
- This way I could use some basic local version control (git) on my playground while still developing on the iPad.

This would also provide a workaround to others needing some "advanced" git features that aren't that simple from UI.

**Comment by bummoblizard** [comment]
A git like command `lg2` was added in https://github.com/thebaselab/codeapp/commit/e5a503a66fd4a517e6660f0942868a8abf3b6c99. It will be available on TestFlight soon.

**Comment by talaviram** [comment]
Thank you so much! I've just discovered it and it looks awesome.
I've opened another issue related:
https://github.com/thebaselab/codeapp/issues/916

Feel free to close this issue. I guess aliasing `lg2` to `git` would make things (and scripts) easier but would falsely imply this is git rather than a git complaint.

**Comment by bummoblizard** [comment]
Aliasing can cause problems with certain commands. Let's pop a notification suggesting `lg2` when a user tries to run `git` instead.

**Comment by bummoblizard** [comment]
<img width="348" alt="image" src="https://github.com/thebaselab/codeapp/assets/38398443/b6bc9cec-1bb4-4e54-aa8e-15abe7ed3710">
