### ISSUE TITLE
Internet issue

### ISSUE THREAD

**Issue by jonlinquent** [thebaselab/codeapp#866]
So i tried to make a discord bot using python but this one thing always weird. My internet ping is always 22 but when i check the ping on the bot it says 200+ ( testflight code app ) can you fix this?

**Comment by bummoblizard** [comment]
Internet condition can be affected by many factors, especially when the device is connected via WiFi. You might check your internet connection using the 'ping' command in terminal and consider switching to 2.4GHz WiFi for stabler connection.
