### ISSUE TITLE
Permission issues when running npm run dev on ipad

### ISSUE THREAD

**Issue by jahzlariosa** [thebaselab/codeapp#868]
npm ERR! Cannot read properties of undefined (reading 'stdin')
npm ERR! code EPERM
npm ERR! syscall spawn
npm ERR! errno -1
npm ERR! Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (node:internal/child_process:413:11)
npm ERR!     at spawn (node:child_process:713:9)
npm ERR!     at /private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:18:12
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at promiseSpawn (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:17:13)
npm ERR!     at spawnWithShell (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:123:10)
npm ERR!     at promiseSpawn (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm ERR!     at runScriptPkg (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:79:13)
npm ERR!     at runScript (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm ERR!     at RunScript.run (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/lib/commands/run-script.js:121:13)
npm ERR!  Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (node:internal/child_process:413:11)
npm ERR!     at spawn (node:child_process:713:9)
npm ERR!     at /private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:18:12
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at promiseSpawn (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:17:13)
npm ERR!     at spawnWithShell (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:123:10)
npm ERR!     at promiseSpawn (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm ERR!     at runScriptPkg (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:79:13)
npm ERR!     at runScript (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm ERR!     at RunScript.run (/private/var/mobile/Containers/Shared/AppGroup/9479D47E-A07B-4F3F-8209-3A8AF9A6A05D/lib/lib/node_modules/npm/lib/commands/run-script.js:121:13) {
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'spawn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in: /var/mobile/Containers/Data/PluginKitPlugin/FC549B91-270F-4EED-B9EA-A5C8398C01AC/Library/Caches/_logs/2023-07-09T07_07_27_705Z-debug-0.log

**Comment by bummoblizard** [comment]
Can you share us the content of package.json?

**Comment by Taikylah** [comment]
Hi there same issue here on An iPad Air 5.
Here is the package.json
![IMG_0106](https://github.com/thebaselab/codeapp/assets/25254922/da746373-14c2-4d7a-93e1-6f3bf32042a0)

**Comment by Weemizo** [comment]
Same happens to me, any solution to this issue?

**Comment by Weemizo** [comment]
> Hi there same issue here on An iPad Air 5. Here is the package.json ![IMG_0106](https://user-images.githubusercontent.com/25254922/254068391-da746373-14c2-4d7a-93e1-6f3bf32042a0.jpeg)

Any solution found? I also got an iPad Air 5
![IMG_0044](https://github.com/thebaselab/codeapp/assets/60063669/07aa2090-c363-4cd2-8568-d55c1c48b4da)

**Comment by bummoblizard** [comment]
Hello @Weemizo. The error message shows Node tried to spawn a sub-process. This is prohibited on iOS and therefore unsupported in Code App. Please see https://github.com/thebaselab/react-starter for a React sample project that we created.

**Comment by Lukas-Batema** [comment]
@bummoblizard, you may want to add this to the following section on what I assume is the wiki at https://code.thebaselab.com/extras/frequently-asked-questions#my-favourite-npm-python-module-doesnt-work/, or perhaps under it as a subsection for a list of templates made for codeapp that help with otherwise unsupported packages?

**Comment by Taikylah** [comment]
Hi, @bummoblizard I tried your template but there is still the same error

**Comment by lk0606** [comment]
@jahzlariosa  same to me, how to fix this
