### ISSUE TITLE
Cannot select compiler

### ISSUE THREAD

**Issue by QWQcoding** [thebaselab/codeapp#874]
I want to use the server-side compiler "gcc" , but when I run the code , I can only use the compiler "clang". I can't select which compiler to use.

**Comment by bummoblizard** [comment]
![Simulator Screenshot - iPad (10th generation) - 2023-07-28 at 14 39 36](https://github.com/thebaselab/codeapp/assets/38398443/3fb4c08a-ea5c-40e6-8f3b-1f8ed990ac3b)
