### ISSUE TITLE
FileProvider dependency is gone from GitHub

### ISSUE THREAD

**Issue by aehlke** [thebaselab/codeapp#878]
https://github.com/amosavian/FileProvider

```
This repository has been disabled
Access to this repository has been disabled by GitHub Staff due to a violation of [GitHub's Terms of Service](https://docs.github.com/site-policy/github-terms/github-terms-of-service). If you are the owner of the repository, you may reach out to GitHub Support for more information.
```

Sounds like some nonsense. I have a local copy if needed.

**Comment by bummoblizard** [comment]
While I can simply switch to my own fork, I am concerned with any potential breach of ToS regarding the repository. I have contacted the author for more information.

**Comment by aehlke** [comment]
hi again - did you learn anything from the author?

**Comment by bummoblizard** [comment]
He did not reply. I decided to use the fork for now. The change is pushed to the main branch.
