### ISSUE TITLE
Files Browser in CodeApp cannot scroll horizontally. Filenames cut off.

### ISSUE THREAD

**Issue by ais-developer** [thebaselab/codeapp#885]
When i open my folder, files are nested inside eventually the file names are cut off the further in folder hierarchy you go.

**Comment by ais-developer** [comment]
Please raise the severity of this if possible. Most mobile and Web projects have multiple folders and package names nesting, therefore not being able to scroll horizontally means most of the files are not click able since a large number of file text is cut off. Making the app very hard to functional.

Thank you.

**Comment by bummoblizard** [comment]
It is now possible to adjust the sidebar width.

<img width="1080" alt="image" src="https://github.com/thebaselab/codeapp/assets/38398443/2e24e4dd-f4f4-40a4-9e43-c2bfd6e323d5">
