### ISSUE TITLE
Can not open PEM files anymore

### ISSUE THREAD

**Issue by carstenf** [thebaselab/codeapp#892]
Looks like with the new version, the opening of PEM files cause the following error: Failed to import key.
Some time ago it was still possible.

**Comment by carstenf** [comment]
It’s iPadOS 16.6

**Comment by solwon** [comment]
I'm using iPadOS 16.1 and the app can't import pem key on my Files app.
I managed to connect to my server by copy-pasting private key from my password manager, but yeah, it is not recommendable action.

**Comment by carstenf** [comment]
Yes, agree.
Some weeks ago, I could import it.

just some question, can I run the code on a remote server?
I don’t know how to connect to a machine with running VSCode.
I would somewhere specify the port forwarding linke 8080.
I some applications one could do 
Hostname: 54.93.160.253:8080
Port: 22
User: 

But it looks like the code app does not like 54.93.160.253:8080
Some ideas?

**Comment by bummoblizard** [comment]
This problem is now fixed. Thanks for reporting @carstenf @solwon.
