### ISSUE TITLE
about iCoud

### ISSUE THREAD

**Issue by Sj704** [thebaselab/codeapp#898]
Hi! I just want to ask about the iCloud setting, I didn't find any settings about iCloud in the app or in the local setting. And do you provide any tutorial for setting up an SSH server for these kinds of online staff?

**Comment by bummoblizard** [comment]
Hey. You can store files at any location available in Files App. Just select open folder at the startup menu or use this button in the explorer. Then you'll be able to set an iCloud directory as the working folder.
<img width="258" alt="Screenshot 2023-08-14 at 11 51 05 AM" src="https://github.com/thebaselab/codeapp/assets/38398443/3cdd6839-096b-4842-b836-7fc9b4a538d0">

Regarding SSH, you can refer to our documentation at https://code.thebaselab.com/guides/connecting-to-a-remote-server-ssh-ftp.

**Comment by bummoblizard** [comment]
Closing as no further action is needed. Feel free to reopen if needed.
