### ISSUE TITLE
HTML Preview Error

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#90]
So, I noticed that the HTML preview has stopped working, although having worked in previous updates. Here are a few screenshots showing this. 

![image](https://user-images.githubusercontent.com/55695493/115387588-e85e3d80-a1a8-11eb-9f5c-3599edd6f0bb.jpeg)
![image](https://user-images.githubusercontent.com/55695493/115387595-eb592e00-a1a8-11eb-8c67-e627bcd8119b.png)
![image](https://user-images.githubusercontent.com/55695493/115387606-edbb8800-a1a8-11eb-9149-d9d12a3a6990.png)

**Comment by bummoblizard** [comment]
I could not reproduce it. Are the two files under the same directory? Did you try refreshing the browser?

**Comment by Lukas-Batema** [comment]
Yes, they are, and I tried refreshing the browser.

**Comment by bummoblizard** [comment]
Does this still occur on the latest release?

**Comment by Lukas-Batema** [comment]
> Does this still occur on the latest release?
As far as I can tell through testing, yes it is.

**Comment by Lukas-Batema** [comment]
> Does this still occur on the latest release? 

I guess i did:
```html
<link rel="stylesheet" type="text/css" ref="theme.css">
``` 

instead of: 
```html
<link rel="stylesheet" type="text/css" href="theme.css"
```

I will close this issue as my mistake. Sorry...
