### ISSUE TITLE
Assign as current workplace not working

### ISSUE THREAD

**Issue by bogdanripa** [thebaselab/codeapp#912]
I have a folder with a cpp file that write to an out file. Even if I assign my folder as the current workplace, it will compile and run in the Documents folder.

**Comment by bogdanripa** [comment]
If I change directory in the terminal and then hit run it will work. But this should work out of the box.

**Comment by bummoblizard** [comment]
This should be (partially) fixed in https://github.com/thebaselab/codeapp/issues/987.
