### ISSUE TITLE
c++ library

### ISSUE THREAD

**Issue by Sj704** [thebaselab/codeapp#919]
#include <bits/stdc++.h> this head file doesn’t work in the app, is this issue of IDE?

**Comment by bummoblizard** [comment]
We have added this header in a recent commit. It is now in the TestFlight build and will be available in the next release.

**Comment by bummoblizard** [comment]
https://testflight.apple.com/join/EgZ8sE2P

**Comment by Sj704** [comment]
thx,and i have another question, i m new to learning code, can this great IDE download in mac(m1 apple silicon)?

**Comment by bummoblizard** [comment]
No, Code App is not available for macOS.
