### ISSUE TITLE
CodeApp Requires Developer Mode to launch

### ISSUE THREAD

**Issue by ais-developer** [thebaselab/codeapp#920]
I am getting this message now and the app wont even launc. However I think the message only appeared after I enabled lockdown mode. I have a severe security concern that means I cannot enable developer mode on my machine.

**Comment by bummoblizard** [comment]
This is because you are building the app yourself. If you download it from TestFlight or App Store, the message will go away.

**Comment by ais-developer** [comment]
Hmm.. odd. I have more then iPad this is one is using AppStore build, I uninstalled and re installed the appstore build and the message no longer appears but the editor is not opening (that issue has been marked as fixed). Thanks for the feedback if I am able to reproduce it in later builds I will investigate thoroughly before opening the issue. I think this can be closed for now though.

**Comment by bummoblizard** [comment]
No worries! Let me know if you need help again. The Lockdown mode fix is available on https://testflight.apple.com/join/EgZ8sE2P.
