### ISSUE TITLE
SSH connection opens root filesystem instead of directory set on remote machine

### ISSUE THREAD

**Issue by thekeith** [thebaselab/codeapp#930]
Whenever an SSH connection is opened it defaults the file browser to the root directory of the filesystem for some reason. Any attempt to change this on the server side is ineffective.

**Comment by bummoblizard** [comment]
What should be the expected behaviour? How did you configure the directory on your server?

**Comment by thekeith** [comment]
* Expected behavior should be going to the user folder (home directory, in my case /Users/$USER)
* On the server I set an action in .zshrc to change directory on a new session, but in retrospect I’m not sure that would have worked anyway
* It’s only an issue as it forces the user to navigate from the root of the filesystem all the way to where they want to go; it could be a setting, with a default to ~

**Comment by bummoblizard** [comment]
Can you try this?
https://support.termius.com/hc/en-us/articles/4403215978393-How-do-I-set-a-default-SFTP-path-

**Comment by bummoblizard** [comment]
This is indeed a bug. Code App is ignoring the remote working directory. 

Fix: In `SFTPFileSystemProvider.swift`, we should call `libssh2_sftp_realpath` with `.` in libssh2 to obtain the working directory and set it as homePath.

**Comment by bummoblizard** [comment]
The changes I made in NMSSH: https://github.com/thebaselab/NMSSH/commit/2d800fca5d2da49baff1cbc061b275e33df70731

**Comment by bummoblizard** [comment]
This should work universally on different platforms as it is how the FreeBSD sftp command `pwd` works:
https://github.com/freebsd/freebsd-src/blob/6b635c74fd4135eaae68970bfc5aad9ae905fec7/crypto/openssh/sftp.c#L2237

**Comment by bummoblizard** [comment]
> Did the changes make it to 1.4.7 or is it still to be released?

It's processing and will be available on TestFlight soon.

**Comment by bummoblizard** [comment]
Because of #943, resolving home path is now an configurable option and is off by default.
