### ISSUE TITLE
FTP error NSURLERRORDOMAIN

### ISSUE THREAD

**Issue by ATLAbanana35** [thebaselab/codeapp#931]
When I try to connect by ftp the app, an error appears: NSURLERRORDOMAIN, That’s the sames ID in FileZilla.
Can you help me?
![IMG_0103](https://github.com/thebaselab/codeapp/assets/113624028/647c70c0-0d81-4fdd-a41a-c95fa09ed590)

**Comment by bummoblizard** [comment]
-1001 is a generic timeout error. Are you sure that your ftp server is configured properly?

**Comment by ATLAbanana35** [comment]
Ok, I don't know why but now that's work. Thanks
