### ISSUE TITLE
How can I download repo from github

### ISSUE THREAD

**Issue by water-in-stone** [thebaselab/codeapp#932]

**Comment by water-in-stone** [comment]
The document is vert ambiguous about how to download code from github!!!!!

**Comment by bummoblizard** [comment]
Which step are you stuck at? There is a textfield under the clone repository section where you can enter the repository's url. Just tap return on your keyboard and the repository will start cloning.

**Comment by water-in-stone** [comment]
I can not see the "source control" page, actually, I stuck at the "commit" part.

**Comment by water-in-stone** [comment]
![img_v2_900f0494-38c9-4958-8ec4-ac06afc2bacg](https://github.com/thebaselab/codeapp/assets/9940769/672f503c-3ebb-4fa8-82e2-942c8319483e)

**Comment by water-in-stone** [comment]
It seems that when someone can not return the "clone repo" step when he choose to not clone a repository,

**Comment by water-in-stone** [comment]
I contend that we necessitate a function facilitating an expedient revert to the initial state, obviating the need to redownload the application.

**Comment by bummoblizard** [comment]
You must have mistakenly initialized a repository at the `Documents`. To remove it, delete the .git folder located at `Documents`. You can do this by running `rm -rf .git` in the terminal or enabling `Shown hidden files` in the settings and delete it in the file explorer.

**Comment by water-in-stone** [comment]
Thanks. Now I download the repository from github after follow your instructions.

**Comment by bummoblizard** [comment]
I am glad it helped. I will improve the documentation on this.

**Comment by bummoblizard** [comment]
https://github.com/thebaselab/codeapp/commit/2c11ce91bd12140520fd84e1696149fdf7922b7b
