### ISSUE TITLE
SSH connection with key not working

### ISSUE THREAD

**Issue by krysalead** [thebaselab/codeapp#939]
Hi,

I am using an ssh key to connect to my remote host but the connection failed whereas using terminus I can connect using the exact same parameter. Is there a way to see logs? Obviously I can’t share the details and the only error is “authentication failed”.
Regards

**Comment by bummoblizard** [comment]
Hello. Is your ssh key password protected?

**Comment by krysalead** [comment]
Hi, not password protected, type rsa

**Comment by bummoblizard** [comment]
Possible related issue: https://github.com/libssh2/libssh2/issues/536

Potential fix is to upgrade libssh2 to `1.11.0`.

**Comment by bummoblizard** [comment]
On another note, we should also upgrade libssh2 to 1.11.0 in SwiftGit2.

**Comment by bummoblizard** [comment]
@krysalead Can you try the fix and let me know if it works? Here's the link to it: https://testflight.apple.com/join/EgZ8sE2P

**Comment by krysalead** [comment]
Hi @bummoblizard, thanks this version is fixing the issue. I tested it and I can connect using the same information as before.

**Comment by bummoblizard** [comment]
> Hi @bummoblizard, thanks this version is fixing the issue. I tested it and I can connect using the same information as before.

I'm glad it helped. Let me know if you see another problem in the future.
