### ISSUE TITLE
External monitor improvement

### ISSUE THREAD

**Issue by krysalead** [thebaselab/codeapp#942]
Hi,

I can see that some streaming apps are able to stream on external screen bigger resolution. AFAIK the external monitor is by default a mirroring of the IPad. But if other app can show a different resolution on external monitor that could be a killer feature on code app if possible. So we can imagine Having the code and running application in different screen.

**Comment by bummoblizard** [comment]
Have you take a look at Stage manager? It is the preferred way to do this. Although it needs a M1/M2 iPad.

**Comment by krysalead** [comment]
Hi, I tried stage manager but maybe I missed some configuration, it stays in my iPad m2 resolution and format. I will give it a second look

**Comment by bummoblizard** [comment]
It requires a keyboard and mouse/trackpad connection:

**Comment by krysalead** [comment]
Hi,

i tested again and I found where it was hiding, under the brightness and display menu I can stop mirroring and it works ok, you can close or keep it with the suggestion.
