### ISSUE TITLE
Ssh improvement

### ISSUE THREAD

**Issue by krysalead** [thebaselab/codeapp#943]
Hi,

It would be nice to have a remote home folder field in the SSH connection details so we are landing to the right folder. 
Right now I am using a Gitpod workspace which is located in /workspace/NAMEOFTHEWORKSPACE but I can’t navigate using code app. I am thinking about putting a symlink in the home user folder to reach the workspace folder.

**Comment by bummoblizard** [comment]
This is a regression introduced in https://github.com/thebaselab/codeapp/issues/930. We need to re-think what's the right behaviour here.

**Comment by bummoblizard** [comment]
This is a regression introduced in https://github.com/thebaselab/codeapp/issues/930. We need to re-think what's the right behaviour here.

**Comment by bummoblizard** [comment]
This is a regression introduced in https://github.com/thebaselab/codeapp/issues/930. We need to re-think what's the right behaviour here.

**Comment by krysalead** [comment]
Hi, I see the issue, using the working directory instead of user home would solve my issue but not the one from the other user. What about a switch in the UI for working dir or home dir. Or even better a button to open any remote folder and make it the root of the workspace, this will cover the case of people having a ssh connection to multiple project?.

**Comment by krysalead** [comment]
Hi,

is there a way to downgrade the application to not have the fix, I can’t work for now.

**Comment by bummoblizard** [comment]
Unfortunately not. Does symlink work for you? 

Alternatively, you can try to set the default sftp path following this guide: https://support.termius.com/hc/en-us/articles/4403215978393-How-do-I-set-a-default-SFTP-path-

**Comment by krysalead** [comment]
Hi,

I haven’t tried yet but I will, terminus is not the problem, the problem is more on Gitpod side. I will check the symlink if it solves the issue. But having a way to customise is the final solution.

**Comment by krysalead** [comment]
Hi,

I tried the symlink and the application is saying “unknown file format”. So, nothing happen.

**Comment by bummoblizard** [comment]
Resolving home path is now an configurable option and is off by default.
