### ISSUE TITLE
Bug: cellpadding attribute not working when executing code

### ISSUE THREAD

**Issue by antic-sar** [thebaselab/codeapp#948]
Try running this code. You won’t be able to see the padding 

```html
<!doctype html> 
<html>
<head>
<title>Title</title> <meta charset="utf-8">
</head> 
<body>
<h1>Hello World</h1>
<table border="1" cellpadding="100px">
<tr> 
<td>hello</td> <td>bye</td> 
</tr>
<tr>
<td>good</td> <td>nice</td>
</tr> 
</table>
</body>
</html>
```

**Comment by bummoblizard** [comment]
I am unable to reproduce this. There seems to be a typo in the ending title tag. Please make sure the syntax is right.

![Simulator Screenshot - iPad (10th generation) - 2023-09-06 at 17 56 18](https://github.com/thebaselab/codeapp/assets/38398443/5960b306-7f5f-4d66-add0-306bc26e0585)

**Comment by antic-sar** [comment]
Hey there, thanks for checking I tried to check to again multiple times..


After sometime, tried to click on reload for the safari run browser and seems to update and work fine. Seem to be a cache issue perhaps..
