### ISSUE TITLE
problem with text selection

### ISSUE THREAD

**Issue by fahadalzubaidi** [thebaselab/codeapp#958]
There is a problem with text selection, where you cannot select a whole line or you cannot select text partially as shown in the example in the image (the example is from another app just for clarification). You can only select a word by double-tapping on it.

This problem always occurs if the device is set to Arabic. It also appears in English (sometimes) for an unknown reason; at first, you can select text partially or a whole line, but as you continue programming, suddenly you cannot do that anymore for an unknown reason and to solve it you need to restart the app.

I see this as a problem that limits the capabilities of the app and hinders our work as programmers, so please prioritize it.

With much appreciation, thank you for providing the best programming app ever on iOS, you are a great programmer!

![IMG_20230927_112536_858](https://github.com/thebaselab/codeapp/assets/68612294/1e65f455-4b93-4dea-8890-1a405c3e10b5)

![IMG_20230927_112534_298](https://github.com/thebaselab/codeapp/assets/68612294/70a4bdd5-189f-41da-a8f8-4ad0355a965a)

**Comment by adamszigeti** [comment]
I was never able to select text like this on this app, but it would be really nice to (the attached image shows what I get by double tapping a word - I can't grab the blue indicator, it seems to be doing mothing). I also noticed that I can't move the cursor by holding the space, like on other apps.

![image](https://github.com/thebaselab/codeapp/assets/5877606/5db270cc-f9c5-4008-835f-1a7e3059e60c)

**Comment by WobL256** [comment]
I can confirm, there is a problem with text selection that I am also experiencing. When double tapping a word, the selection handles can't be moved. I think it's worth noting that I'm experiencing this on my iPhone, not on an iPad, I don't own one so I can't check if it also happens there but I see people are reporting this kind of problem on their iPads as well.

**Comment by bobikon** [comment]
Confirm this issue on iPhone 12 mini & iOS 17.2.1

**Comment by AhmedOubah** [comment]
Ican confirm there is a serious problem with the text selection, you can’t select a partial text, even the selection grabbers cant be move like other apps …
Please concern to solve this problem as soon as possible….thank you in advance
