### ISSUE TITLE
Link See Wiki in the readme doesn't work

### ISSUE THREAD

**Issue by Flmob** [thebaselab/codeapp#959]
It just returns back to the readme

**Comment by bummoblizard** [comment]
Thanks for noticing. It's now fixed.

**Comment by Flmob** [comment]
@bummoblizard , the link is still not working, BTW

**Comment by Flmob** [comment]
I was going to propose PR with a fix but unfortunately got an 404 error =(

**Comment by bummoblizard** [comment]
@Flmob It should be working now.

**Comment by Flmob** [comment]
That's it. Thank you
