### ISSUE TITLE
Code App availability on Chinese App Store

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#960]
Due to a government policy change in China, Code App might not be available on the Chinese App Store starting from April 2024.

> Apple began last Friday requiring app developers to submit the "internet content provider (ICP) filing" when they publish new apps on its App Store, it said on its website for developers.

> To get an ICP filing licence, developers need to have a company in China or work with a local publisher, which has been an obstacle for a large number of foreign apps.

As we have many Chinese users, I'm creating the issue to allow discussion on this.
https://www.reuters.com/technology/apple-enforces-new-check-apps-china-beijing-tightens-oversight-2023-10-03/

Update: While I am still working on obtaining an ICP license, the app is still available on China's App Store as of April 3.

**Comment by cat-my-earn** [comment]
Is it possible to get a Chinese company as a partner to submit the ICP?
(Maybe it is a stupid question)

**Comment by cat-my-earn** [comment]
在中国，按理来说网站也是无法以个人身份备案（ICP）的，但是如果购买了云服务商的服务（比如阿里云），它们会给你提供一个申请通道，提交备案的材料之后，云服务商会以公司的身份代理你的备案申请，于是就可以用个人身份而非公司身份成功备案。也许app的备案也会有类似的公司可以提供代理备案的服务。

In China, it is reasonable that websites cannot ICP as individuals, but if you buy the services of cloud service providers (such as Alibaba Cloud), they will provide you with an application channel. After submitting the filing materials, the Cloud Service Chamber of Commerce will represent your filing application as a company, so you can use your personal identity. Successful filing of non-company identity. Perhaps there will be similar companies that can provide agent filing services for app filing.

I don't know how to translate it in some places.( ´▽｀)

**Comment by Farewe1ll** [comment]
所以 code app在中国大陆还有继续上架的想法吗?
So, would code app still up on the Chinese App Store after some adjustments like using Cloud Service?

**Comment by bummoblizard** [comment]
> 所以 code app在中国大陆还有继续上架的想法吗?
> 
> So, would code app still up on the Chinese App Store after some adjustments like using Cloud Service?

我们正在申请ICP许可证。

**Comment by bummoblizard** [comment]
Unfortunately it seems to be incredibly difficult for us to obtain an ICP registration as a non Chinese entity. If anyone from China can offer help, please contact me.

While I'm still looking into it, it is unclear whether the app will be available on the Chinese App Store after March.

**Comment by luni-moon** [comment]
I know I haven't been here in a while, but I’m hoping and praying you can get it to work out! I loved this project, and may start using it again as I no longer work remotely. Thankfully I am American, but sadly I know there is no way around the Chinese Government. I wish I could help, but can't.

**Comment by cat-my-earn** [comment]
我知道了，谢谢在 2024年4月23日，23:28，Chung Shing Hin ***@***.***> 写道：﻿
Closed #960 as completed.
