### ISSUE TITLE
can not draw a graph using python’s lib like ”Mathplotlib” in Code

### ISSUE THREAD

**Issue by debugging-art** [thebaselab/codeapp#966]
![IMG_1219](https://github.com/thebaselab/codeapp/assets/74086126/07fabddc-fafe-4186-b9bb-2e4f24c003f8)

I really need this function!
“Mathplotlib”

**Comment by bummoblizard** [comment]
Use plt.savefig('graph.png') instead.

**Comment by debugging-art** [comment]
It works. Thank you!
