### ISSUE TITLE
Keyboard toolbar in the terminal 

### ISSUE THREAD

**Issue by PouriaTolouei** [thebaselab/codeapp#968]
Hey,

I’ve noticed that when editing a file , there is a toolbar with arrow keys and other buttons. However, this disappears when typing into the terminal. I think it’ll be useful to have a similar toolbar with keys that are not available on the on-screen keyboard. Up and down arrows are particularly useful when going through previous terminal commands. A control key will also be useful to evoke various commands in combination with letter keys.

**Comment by bummoblizard** [comment]
Thank you for your suggestion. I will implement this in a future update.

**Comment by bummoblizard** [comment]
This feature is now available.
