### ISSUE TITLE
Java input problem

### ISSUE THREAD

**Issue by 15357957173** [thebaselab/codeapp#969]
I don’t know how to use the terminal or how to input.
![IMG_0081](https://github.com/thebaselab/codeapp/assets/148949550/3d0603a8-c9c0-4fe9-a0b1-87eeb06730a3)

**Comment by bummoblizard** [comment]
The code you wrote tries to parse the command line arguments. You'll need to read from stdin using the scanner function instead as custom arguments are not supported for remote compiling.

**Comment by 15357957173** [comment]
> The code you wrote tries to parse the command line arguments. You'll need to read from stdin using the scanner function instead as custom arguments are not supported for remote compiling.

Thank you for your reply. I'm a novice and I'm not familiar with these yet.Thank you very much.
