### ISSUE TITLE
Minimap & Line Numbers

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#97]
So, when I turn on line numbers and minimap, it works for the time before you relaunch the app, but it stays toggled in settings, after re-springing, but doesn't actually show them.

https://user-images.githubusercontent.com/55695493/116086646-04148880-a66e-11eb-8e8d-806792907e58.MP4

**Comment by bummoblizard** [comment]
I can confirm and it only affects iPhones. I'll fix it in the next TestFlight build.

**Comment by Lukas-Batema** [comment]
> I can confirm and it only affects iPhones. I'll fix it in the next TestFlight build. 

Also, sometimes when tapping on the top navigation bar, when in the code editor tab, it sometimes will not respond when trying to switch to a different file, even when it is within the same directory.

**Comment by bummoblizard** [comment]
Minimap & Line Numbers fixed in https://github.com/thebaselab/codeapp-source/commit/263379b21fbd42dce5a78edabfe8805bb6de3f3a

**Comment by Lukas-Batema** [comment]
> Minimap & Line Numbers fixed in [thebaselab/codeapp-source@263379b](https://github.com/thebaselab/codeapp-source/commit/263379b21fbd42dce5a78edabfe8805bb6de3f3a)

Thanks, I can confirm it is, as I tested it when the build came out.

**Comment by Lukas-Batema** [comment]
Shifted the remaining issue to another issue page
