### ISSUE TITLE
Running programs in C

### ISSUE THREAD

**Issue by badson18** [thebaselab/codeapp#971]
Everything compiles like it should but after some time terminal just stops compiling and running program, there's no error message or anything just blank space until i restart the app and everything's works normal again.

**Comment by p-xiexin** [comment]
希望能加入一个功能：在只读模式下，不会出现ipad的键盘。
我在只读模式就是想单纯看一看代码，但是每次碰到屏幕都会出现键盘，非常影响使用体验。

**Comment by RaviSekhon** [comment]
Same here.

**Comment by bummoblizard** [comment]
Should be fixed by #612.
