### ISSUE TITLE
SSH Proxy / Jump 

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#976]
From support email:
```
我希望可以在远程SSH与SFTP中加入通过跳板机连接的功能！
```

**Comment by TangChenTom** [comment]
Hello there! Is the function of SSH Proxy / Jump from gateway server to internal machine available now?

**Comment by bummoblizard** [comment]
> Hello there! Is the function of SSH Proxy / Jump from gateway server to internal machine available now?
> 
> 

Hi. This is the next thing I will be working on.

**Comment by TangChenTom** [comment]
Thank you! Wish Code App could be better and better.

**Comment by bummoblizard** [comment]
@TangChenTom This feature is now available on App Store.
