### ISSUE TITLE
External localhost Error

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#98]
So when I click the icon to go to an external browser in the localhost preview of an HTML file, it takes two tries. The first just doesn't load, the second works (also does this on Safari, except it states that it cannot connect to the server for the first attempt).

https://user-images.githubusercontent.com/55695493/116087041-77b69580-a66e-11eb-9da4-c7be16301a98.MP4

**Comment by bummoblizard** [comment]
This is expected, as iOS apps generally cannot run in the background. You'll need an iPad to launch the browser side-by-side.

**Comment by Lukas-Batema** [comment]
What is weird, is that it works the second time, as the video shows.
