### ISSUE TITLE
How to clone code from GitHub?

### ISSUE THREAD

**Issue by zhanhui2020** [thebaselab/codeapp#983]
I couldn’t clone the code from GitHub. It tells that http error 403.

**Comment by bummoblizard** [comment]
Hi. Please make sure you have configured the correct credentials. Specifically, you'll need to set up personal access token (PAT) instead of regular password for GitHub. You can read more at: https://code.thebaselab.com/guides/version-control

**Comment by zhanhui2020** [comment]
This is my automatic reply! I have received your email and will reply you soon!Thank you!
