### ISSUE TITLE
Does “Code App” uses local network?

### ISSUE THREAD

**Issue by jonlinquent** [thebaselab/codeapp#985]
I have problems with this for a long time ago. Don’t judge but i use “Code App” for discord bot or discord.py, and somehow my “ping” is over 200+? Can you tell me why its like this. My wifi is faster than this like. Im using the testflight version, and i dont know if its different than the paid version. But can you fix this problem
![IMG_3518](https://github.com/thebaselab/codeapp/assets/128697050/ff80cd8f-08ef-47af-ae5a-c270e91648b6)
- my wifi speed test
![Uploading IMG_3519.jpeg…]()
- discord ping???

**Comment by bummoblizard** [comment]
This doesn't seem right as Python runs locally. Is the problem specific to Code App? Have you try running your bot on a computer?

**Comment by jonlinquent** [comment]
no i have not. my Mac is broke so i just code in ur app. i had this problem months ago but i didnt bother opening an issue

**Comment by bummoblizard** [comment]
Thanks for getting back to me. Although I'm not familiar with discord bots, I can think of two possibilities for this:
- Network latency between your network and discord's server
- Poor performance of your code (could be because it is running on a mobile device)

Hope this helps.
