### ISSUE TITLE
Terminal unpredictably defaults to ~

### ISSUE THREAD

**Issue by pedromzadeh** [thebaselab/codeapp#987]
## Versions
- iPadOS 17.2
- Code App 1.5.1 Build 234

## Description
Regardless of the project folder opened, the terminal _sometimes_ defaults to the home directory, i.e., `pwd` --> `~`.

I can sometimes fix this issue by closing and reopening the app. But behavior is unpredictable.

**Comment by bummoblizard** [comment]
Thanks for opening the issue. I can confirm this bug.

**Comment by bummoblizard** [comment]
Should be fixed in https://github.com/thebaselab/codeapp/commit/3c28796325a42eed5e0130871193d28875b690bf. TestFlight build available soon.

**Comment by bummoblizard** [comment]
Fix released on App Store.
