### ISSUE TITLE
Adapt to iPadOS‘keyboard cursor

### ISSUE THREAD

**Issue by superwfox** [thebaselab/codeapp#997]
Hping that the code app team can adapt the software to the keyboard that comes with iPadOS. The function of long pressing the space and sliding cursor is very practical, especially for users without a physical mouse，which could greatly enhance the typing experience🌹

**Comment by bobikon** [comment]
Confirm this issue on iPhone 12 mini an iOS 17.2.1

**Comment by bummoblizard** [comment]
Native text selection is now supported through Runestone editor. See https://github.com/thebaselab/codeapp/issues/169#issuecomment-2162955555.
